### ISSUE TITLE
timeout issue - this.imageElement is undefined

### ISSUE THREAD

**Issue by peterzytkiewicz** [zxing-js/ngx-scanner#100]
When leaving component with ngx-scanner (on ngDestroy) get 'TypeError: this.imageElement is undefined';

it's cause by the fact that many setTimeouts are being created, but not being cleaned.
(@zxing/ngx-scanner/esm2015/zxing-ngx-scanner.js:186).

at least this is how I get that.
I fixed it by wrapping 'decodeWithDelay' method like below:
```
    const reader = ((this.scanner as any).codeReader as any);
    if (reader) {
      const original = reader.decodeWithDelay;
      reader.decodeWithDelay = (callbackFn) => {
        if (reader.timeoutHandler) {
          clearTimeout(reader.timeoutHandler);
        }

        original.call(reader, callbackFn);
      };
    }
```
Well, that's just a hack, it would be better to fix it properly.

Linux 16.04 LTS
FireFox 60.0.1

**Comment by odahcam** [comment]
Solved by 8a14238bd8ee801ca759185041b8ebcc59d66b4c because there are no timeouts anymore. 🙂
