### ISSUE TITLE
Laser scanner while identifying QR code

### ISSUE THREAD

**Issue by vugar005** [zxing-js/ngx-scanner#101]
Hi
Thanks for great project. I would like to offer a new feature which is similar to Whatsapp QR code scanner.
While camera is identifying QR code , it would be cool to show laser from to bottom.
This would improve user experience.
Thanks!

**Comment by odahcam** [comment]
This is very nice, we'd love to have this as an example! But it should not be coded into the core, the component is ment to be as simple as possible so users can just plug-and-play an then add their styles.

If you'd like to PR an **example** with this implemented, please, do it!

**Comment by odahcam** [comment]
Okay, yw! I repeat, we will not mege any interface customization at the core, but we would love an customization example on top of `zxing-scanner` component at our examples. 🙂
