### ISSUE TITLE
@zxing/ngx-scanner/zxing-ngx-scanner"' has no exported member 'NgxZxingComponent'.

### ISSUE THREAD

**Issue by jack750155** [zxing-js/ngx-scanner#102]
Hello,

I tried to implemented the exemple as describe on the github page (https://embed.plnkr.co/MN4riU/).
But I always got the same probleme with my app.component.ts page, at the line:
`import { NgxZxingComponent  } from '@zxing/ngx-scanner';`

Error:
`/@zxing/ngx-scanner/zxing-ngx-scanner"' has no exported member 'NgxZxingComponent'.`

Maybe someone already had this problem and fixed it :)

thanks in advance

Jacques

**Comment by odahcam** [comment]
I'm afraid your `config.js` file is not right:

```javascript
  '@zxing/ngx-scanner': 'npm:@zxing/ngx-scanner@latest/bundles/ngx-scanner.umd.js',
  '@zxing/library': 'npm:@zxing/library@latest'
```

This seems wrong.

Also, take a look at a working example at https://minhahavan.com and https://zxing-ngx-scanner.stackblitz.io. 🙂

**Comment by jack750155** [comment]
Hello Odahcam

Im working on Angular  6 so I don't think I have an config.js file.
Do you know if I have to place you code somewhere else?
```
 '@zxing/ngx-scanner': 'npm:@zxing/ngx-scanner@latest/bundles/ngx-scanner.umd.js',
  '@zxing/library': 'npm:@zxing/library@latest'
```

Thx :)

**Comment by odahcam** [comment]
Well, the file is in the Plunkr example you sent. Now I'm confused. 😕

**Comment by odahcam** [comment]
Whats the error?

**Comment by odahcam** [comment]
No follow up, so closing.

**Comment by andy82302** [comment]
you must use import { ZXingScannerComponent } from '@zxing/ngx-scanner';

not import { NgxZxingComponent } from '@zxing/ngx-scanner';  in angular6
