### ISSUE TITLE
Support Angular 6?

### ISSUE THREAD

**Issue by ajaxsys** [zxing-js/ngx-scanner#105]
It seams that only change one line can make it work with angular6 / rxjs6

In `zxing-ngx-scanner.js` Change 

     import { BehaviorSubject } from 'rxjs/BehaviorSubject';

to

     import { BehaviorSubject } from 'rxjs';

**Comment by odahcam** [comment]
It supports ng6 at v1.1.0. Also the dev version supports it too.

**Comment by entspannt** [comment]
I get these warnings with angular 6...

`npm WARN @zxing/ngx-scanner@1.1.0 requires a peer of @angular/core@>= 2.0.0 < 6 but none is installed. You must install peer dependencies yourself.
npm WARN @zxing/ngx-scanner@1.1.0 requires a peer of @angular/common@>= 2.0.0 < 6 but none is installed. You must install peer dependencies yourself.
npm WARN @zxing/ngx-scanner@1.1.0 requires a peer of @angular/forms@>= 2.0.0 < 6 but none is installed. You must install peer dependencies yourself.`

Am I missing something?

**Comment by ajaxsys** [comment]
But i got 

ERROR in ./node_modules/@zxing/ngx-scanner/esm5/zxing-ngx-scanner.js
Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in 'C:\...\node_modules\@zxing\ngx-scanner\esm5'

So i have to manually change 

      import { BehaviorSubject } from 'rxjs/BehaviorSubject';

to 

      import { BehaviorSubject } from 'rxjs';

**Comment by odahcam** [comment]
v1.1.0 uses the `rxjs-compat` package to work properly, the `dev` version doesn't need it anymore. Also, v1.2.0 is already in Angular 6, so it's release gonna solve that problem once for all. You can still use the dev version if you don't wanna install the `rxjs-compat` package. Thanks.

**Comment by ajaxsys** [comment]
Thanks for your answer. Waiting for v1.2.0.

**Comment by SandeepThomas** [comment]
Please release 1.2.0 soon, or update 1.1 to Angular 6. Thanks

**Comment by odahcam** [comment]
We're working to release it ASAP.
