### ISSUE TITLE
using ZXingScannerComponent and not able to scan barcode. Only QR code is working

### ISSUE THREAD

**Issue by PravJha** [zxing-js/ngx-scanner#106]
I am using zxing-scanner. However I am only able to scan QR codes successfully. I am not able to scan Barcode. Please,  I need help on this immediately. Since I have already existing Angular 5 app. I cannot use Cordova or Ionic Framework. My application should scan UPCs or 1D barcodes. Pleas elet me know what changes should I make for this to work.

Here is what I have used my **app.component.html**
<zxing-scanner #scanner class="test-class" start="true" [device]="selectedDevice" (scanSuccess)="handleQrCodeResult($event)"></zxing-scanner>

Imported ZXingScannerModule.forRoot() in my **App.module.ts**

in **my app.component.ts**
import {ZXingScannerComponent } from '@zxing/ngx-scanner'

@ViewChild('scanner')
  scanner: ZXingScannerComponent;
  hasCameras = false;
    hasPermission: boolean;
    qrResultString: string;
    availableDevices: MediaDeviceInfo[];
    selectedDevice: MediaDeviceInfo;

    ngOnInit(): void {

        this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {
            this.hasCameras = true;

            console.log('Devices: ', devices);
            this.availableDevices = devices;

            // selects the devices's back camera by default
            // for (const device of devices) {
            //     if (/back|rear|environment/gi.test(device.label)) {
            //         this.scanner.changeDevice(device);
            //         this.selectedDevice = device;
            //         break;
            //     }
            // }
        });

**Comment by odahcam** [comment]
We rely on https://github.com/zxing-js/library which doesn't supports UPC decoding. 😞 

I cannot implement that for ya now, but you can still PR there the UPC port.

**Comment by PravJha** [comment]
It does not even support nay barcode. I tried using 128 barcode but it also was not scanned. Can you list for me which barcode formats it cab be reading. For now it scans only QR code.

**Comment by odahcam** [comment]
Yes, it scans only QR code, at the time of writing our core wasn't able to scan other formats of barcodes, we'r working to bring our core decoders as options, so you can use all scanning features, but for now we can scan only QR codes. PRs are always welcome.

**Comment by odahcam** [comment]
Supported formats list: https://github.com/zxing-js/library#supported-formats
