### ISSUE TITLE
Can't serve the project!

### ISSUE THREAD

**Issue by vaibhav16** [zxing-js/ngx-scanner#108]
Apart from a few peer dependencies being skipped, the project overall installed easily with "npm install"
However, I'm getting an error when I try to run "ng serve".

```
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'zone.js/dist/zone' in 'C:\workspace\New folder\ngx-scanner-master\src'
```

Any ideas how to handle this?

**Comment by odahcam** [comment]
Yas, just `npm i zone.js`. 😉

**Comment by werthdavid** [comment]
Also you should run from the root-directory and not "src"
