### ISSUE TITLE
Camera not closing when exiting qr scanner in ionic application

### ISSUE THREAD

**Issue by jainAdijain** [zxing-js/ngx-scanner#110]
Using the module in ionc-angular application, 
The camera stills open and not geting closed.

**.html**

```
  <div>
    <zxing-scanner [scannerEnabled]="scannerEnabled" [device]="selectedDevice" [cssClass]="'small-video'" (camerasFound)="displayCameras($event)"
      (scanSuccess)="handleQrCodeResult($event)"></zxing-scanner>
  </div>
```

**Comment by odahcam** [comment]
Can you provide information about Angular and the package? Or some part of the package.json?

**Comment by jainAdijain** [comment]
Below is some part of my `package.json`

```
"dependencies": {
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
    "@ngrx/store": "^5.2.0",
    "@ngrx/store-devtools": "^5.2.0",
    "@types/socket.io-client": "^1.4.31",
    "@types/uuid": "^3.0.0",
    "@zxing/ngx-scanner": "^1.0.2"
}
```

**Comment by odahcam** [comment]
Intrigating, can you update the `"@zxing/ngx-scanner": "^1.0.2"` to `"@zxing/ngx-scanner": "^1.1.0"` and try again?

**Comment by jainAdijain** [comment]
Hi, updated the version number as you mentioned. when leaving the qr scanner page without scanning the camera is not getting off now too.

**Comment by odahcam** [comment]
Link offline. 🙁

**Comment by jainAdijain** [comment]
I might be I was sleeping, the timezone does not match with us try using https://clevert.me
If this dont work then we will be mactching our timezones. :)

**Comment by odahcam** [comment]
Seems that when switching tabs, the previous tab is not destroyed by Ionic, you gotta track what events are being triggered and pause yourself the scanner. Unfortunatelly the scanner can't know when the tab is actived or not. I will close as this is not a scanner's bug or something, but feel free to keep discussing the ideias.
