### ISSUE TITLE
Not working in iOS 11.4

### ISSUE THREAD

**Issue by tomcheney** [zxing-js/ngx-scanner#113]
**Describe the bug**
In Safari with iOS 11.4 camera can be selected but no preview is drawn and there is no result 

**To Reproduce**
1. Go to https://zxing-js.github.io/ngx-scanner/
2. Allow camera access
3. Select front or rear camera
4. Nothing happens

**Comment by odahcam** [comment]
Have you tryied to run with the LTS version? 

> This example uses a dev version, because SB is with some kinda bug that prevents us to update.

**Comment by odahcam** [comment]
Closing due to no follow up.
