### ISSUE TITLE
The module includes text-encoding which bloat the size

### ISSUE THREAD

**Issue by jainAdijain** [zxing-js/ngx-scanner#115]
Using ` "@zxing/ngx-scanner": "^1.1.0"` in ionic-angular application.
The source maps of a module which uses qr scanner displyas as follows: 

![image](https://user-images.githubusercontent.com/27722458/42316112-9b459b8a-8066-11e8-99fe-19ed58a807bf.png)

It includes text-encoding without this the production build is not made.
How to fix this - it affects largely in terms of performance.

**Comment by odahcam** [comment]
I'm working on that for a while, seems that some decoders doesn't work without text encoding features, but as JS only supports UTF-8, there's gotta be something we can do, I just couldn't remove it yet. Any help would be appreciated.

**Comment by odahcam** [comment]
Oh, I was already tracking this, please follow https://github.com/zxing-js/library/issues/54 for more info, thanks!
