### ISSUE TITLE
how to improve scanner power

### ISSUE THREAD

**Issue by nikhilsyam** [zxing-js/ngx-scanner#116]
it is not working when scanning the QR code under light

**Comment by odahcam** [comment]
That's too broad, there's lot's of things that can be done, but this is to much for one answer, and of course it will depend on the camera and the illumination. 😕

**Comment by nikhilsyam** [comment]
I am also agreed with you @odahcam , but the thing is when in dark area the image processing is very slow.

**Comment by odahcam** [comment]
Sorry, but are you telling me that you know how to improve?

**Comment by nikhilsyam** [comment]
No @odahcam
