### ISSUE TITLE
Barcode or QR Code?

### ISSUE THREAD

**Issue by danielehrhardt** [zxing-js/ngx-scanner#120]
i am not able to scan Barcodes like
![image](https://user-images.githubusercontent.com/19570043/43344220-50b7b596-91e9-11e8-9c17-ea11eb0901a2.png)

but you write here 
![image](https://user-images.githubusercontent.com/19570043/43344265-63511fe4-91e9-11e8-8e25-18ad2975bf2a.png)

so what can we scan?

**Comment by odahcam** [comment]
At v1.1.0? QR codes
At v1.2.0? Everything our base library does.
