### ISSUE TITLE
Detect qr code within certain rectangular area of camera

### ISSUE THREAD

**Issue by ajaxsys** [zxing-js/ngx-scanner#122]
**Is your feature request related to a problem? Please describe.**
Hi, it is difficult while scanning one of many qr codes in same page(e.g. https://goo.gl/LZ6Sx3).

**Describe the solution you'd like**
Is it posible to detect qr code within certain rectangular area of camera(not the whole camara)?
Image like:
https://i.stack.imgur.com/lMxRq.jpg

Thank you.

**Comment by odahcam** [comment]
Not yet. 😞  Some folks has done it for the `BrowserCodeReader` in the library package, they implemented a method override where they crop the image stream before sending it to the decoder method. But here we didn't done anything like that yet.

**Comment by odahcam** [comment]
I'll have to search for it, I'll post here ASAP, you're also welcome to the Gitter chat. 🙂

**Comment by linusbrolin** [comment]
Is there any reason for why BrowserCodeReader is re-implemented in ngx-scanner instead of just extended from zxing-js/library?
In library, a protected drawImageOnCanvas method was created, so that it could be extended to allow for example custom cropping functionality to be added by extending it.
But since ngx-scanner does not extend BrowserCodeReader from library, we lose that feature here. :/

**Comment by bestbelief** [comment]
@ajaxsys Hello,Have you solved this problem? I am also full screen scan now. I want to sweep the code collection area only in the center part. Thank you.

**Comment by ajaxsys** [comment]
@bestbelief 
I fix this problem by create a dynamic canvas(crop a square area) for BinaryBitmap. 
It's not the best way, but works. 

Sample code(a bit dirty):

https://gist.github.com/ajaxsys/cf18c534e1455c737278c74770edc9be

**Comment by bestbelief** [comment]
@ajaxsys      Thank you for your reply, though the link you gave is not open.

**Comment by ajaxsys** [comment]
@bestbelief It's a public gist...

**Comment by bestbelief** [comment]
OK, I think it's possible to restrict access elsewhere. Thank you for your reply.

**Comment by bestbelief** [comment]
I think so. It seems that I need to find out why.

**Comment by odahcam** [comment]
Good luck then. 🙂

**Comment by odahcam** [comment]
As I said in #139:

> We could implement some injection token for the MultiformatCodeReader so you could implement your own code reader (maybe by extending the default) and adding the custom crop functionality before the decode.

The base library and the crop as implemented there: https://github.com/zxing-js/library/issues/39

**Comment by zhanglongchina** [comment]
@ajaxsys  how can I use you patch, do you have a demo ?

**Comment by odahcam** [comment]
There's  no patch, he just overwritten one method from the library, as his gist shows.

**Comment by fletchsod-developer** [comment]
Since #172 is marked as duplicare if this bug.  So here's this issue we ran into.

--snip--
I ran into this same issue with multiple barcodes & am in the same boat as you guys are. (This snapshot use barcode "code39" for vin scanning)
--snip-- 

See attach snapshot below (once I figure out why this post isnt the picture the upload)

**Comment by fletchsod-developer** [comment]
Since #172 is marked as duplicare if this bug.  So here's this issue we ran into.

--snip--
I ran into this same issue with multiple barcodes & am in the same boat as you guys are. (This snapshot use barcode "code39" for vin scanning)
--snip-- 

See attach snapshot below (once I figure out why this post isnt the picture the upload)

https://github.com/zxing-js/ngx-scanner/issues/172#issuecomment-472605705

**Comment by odahcam** [comment]
Since some of you guys are having some trouble to access the [workaround gist](https://gist.github.com/ajaxsys/cf18c534e1455c737278c74770edc9be) by @ajaxsys, I'm pasting it here:

```javascript
// Patch for node_modules/@zxing/ngx-scanner/esm5/zxing-ngx-scanner.js
BrowserCodeReader.prototype.createBinaryBitmap = function (mediaElement) {
        if (undefined === this.canvasElementContext) {
            this.prepareCaptureCanvas();
        }
        this.canvasElementContext.drawImage(mediaElement, 0, 0);
        // FIXME byHo
        // var luminanceSource = new HTMLCanvasElementLuminanceSource(this.canvasElement);
        // var hybridBinarizer = new HybridBinarizer(luminanceSource);
        // return new BinaryBitmap(hybridBinarizer);
        
        const allWidth = this.canvasElement.width;
        const allHeight = this.canvasElement.height;
        const left = allWidth/4;
        const top = Math.min(allWidth, allHeight)/4;
        const squareSize = Math.min(allWidth, allHeight) / 2;
        // const crop = all.crop(left, top, squareSize, squareSize);

        var canvas1 = document.createElement("canvas");
        canvas1.width = squareSize;
        canvas1.height = squareSize;
        var ctx1 = canvas1.getContext("2d");
        ctx1.rect(0, 0, squareSize, squareSize);
        ctx1.fillStyle = 'white';
        ctx1.fill();
        // ctx1.putImageData(crop.binarizer.source, 0, 0);
        ctx1.putImageData(
            this.canvasElementContext.getImageData(left, top, squareSize, squareSize), 
            0, 0);

        $('.dstImg').attr('src', canvas1.toDataURL("image/png"));
        // $('.dstImg').each((i, img) => 
        //     this.canvasElementContext.drawImage(img, left, top, squareSize, squareSize, 0, 0, squareSize, squareSize));

        var luminanceSource = new HTMLCanvasElementLuminanceSource(canvas1);
        var hybridBinarizer = new HybridBinarizer(luminanceSource);

        // hybridBinarizer.source.buffer = crop.binarizer.source;
        // hybridBinarizer.source.width = squareSize;
        // hybridBinarizer.source.height = squareSize;
        return new BinaryBitmap(hybridBinarizer);
    };
```

**Comment by fletchsod-developer** [comment]
One problem is we're using NPM.  It's not like we can patch it this way.  The cloud web app we're using is too integrated

**Comment by zhanglongchina** [comment]
look forward to the new release which will add the feature

**Comment by odahcam** [comment]
@fletchsod-developer you can patch this way even with NPM. It is not a clean way to solve the issue, but you can use it 'till there's a better way of doing it.

**Comment by nikolawan** [comment]
O found short workaround. Example for upper half canvas

```
HTMLCanvasElementLuminanceSource.makeBufferFromCanvasImageData = function (canvas) {
  let w = canvas.width
  let h = canvas.height / 2
  const imageData = canvas.getContext('2d').getImageData(0, 0, w, h / 2);
  return HTMLCanvasElementLuminanceSource.toGrayscaleBuffer(imageData.data, w, h);
}
```

**Comment by pedromsfernandes** [comment]
Hello @odahcam! Where should the workaround go? Do we have to edit the `ngx-scanner` code in `node_modules`? Thanks!

**Comment by odahcam** [comment]
> Do we have to edit the ngx-scanner code in node_modules?
No

> Where should the workaround go?
Place it in the component .ts file where you gonna use `<zxing-scanner>` component.

**Comment by takashi1kun** [comment]
> Place it in the component .ts file where you gonna use `<zxing-scanner>` component.

How? Where inside the class or outside? ts is complaining that it lacks a lot of classes, etc.

**Comment by developer-temple** [comment]
Trying to solve this problem as well.  I attempted to use the workaround gist but it says that BrowserCodeReader and HTMLCanvasElementLuminanceSource are deprecated.  I tried to fix the workaround by adding @zxing/browser but I couldn't get it to work.  Please help!

**Comment by odahcam** [comment]
This package is not making use of the zxing/browser yet, so it won't work with that one now. Just ignore the deprecations for this workaround, it is not a clean solution anyways. To really solve this issue we will have to implement zoom and cropping controls in the zxing/browser so it can be used by this package in future versions.

**Comment by SgElite** [comment]
Any status update on the above ? I have been trying to get the scanner to work with a rectangle box eg using sample code (test.component.ts, test.component.scss and test.component.html). Am I missing something here ?

**Comment by fletchsod-developer** [comment]
@SgElite - If all else fail then try this similiar script at the very bottom on this link https://github.com/zxing-js/library/issues/39 .  It should be too hard to rewrite it in TypeScript.

**Comment by SgElite** [comment]
> @SgElite - If all else fail then try this similiar script at the very bottom on this link for example written by bburns at [zxing-js/library#39](https://github.com/zxing-js/library/issues/39) . It should not be too hard to rewrite it in TypeScript. I will add another script example there shortly.

**Comment by SgElite** [comment]
@fletchsod-developer - Thanks for your help, appreciated. Looking forward to see the typescript example.

**Comment by SgElite** [comment]
> @SgElite - If all else fail then try this similiar script at the very bottom on this link for example written by bburns at [zxing-js/library#39](https://github.com/zxing-js/library/issues/39) . It should not be too hard to rewrite it in TypeScript. I will add another script example there shortly.

@fletchsod-developer - Any update on the above in typescript ?

**Comment by fletchsod-developer** [comment]
@SgElite - You'll have to convert it to TypeScript & modified the script for Angular 2+ .   I wont be able to work on it for a year or two.  The manager pulled me away from the Angular 8 webapp project & re-assigned me to help the dev team to get the falling apart ASP.NET WebForm webapp project moving cuz they have fallen behind.

**Comment by moiseswasted** [comment]
> [@bestbelief](https://github.com/bestbelief) I fix this problem by create a dynamic canvas(crop a square area) for BinaryBitmap. It's not the best way, but works.
> 
> Sample code(a bit dirty):
> 
> https://gist.github.com/ajaxsys/cf18c534e1455c737278c74770edc9be





https://stackdev.space/questions/when-using-squarespace-custom-code-will-not-be-shown-during-ajax-loading
