### ISSUE TITLE
SCRIPT438: Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by thanhphuocdang** [zxing-js/ngx-scanner#123]
**Describe the bug**
When I run Project be used ZXingScannerModule, I got this error.
I did try with new project Angular6.1.0 and IE11 on windows.
I also got this problem when try with IE on Android 5.1 Lollipop and Apk run on this android.
When I remove ZXingScannerModule out of module, It is running well but I can't use scan barcode feature! 🍡 
It has resolved or new?
ngx-scanner 1.2.0
library0.7.0@dev
Kind regards,
thanhphuochfs@gmail.com

**Comment by thanhphuocdang** [comment]
I found it at @GlobalHistogramBinarizer
private static LUMINANCE_BITS = 5;
    private static LUMINANCE_SHIFT = 8 - GlobalHistogramBinarizer.LUMINANCE_BITS;
    private static LUMINANCE_BUCKETS = 1 << GlobalHistogramBinarizer.LUMINANCE_BITS;
    private static EMPTY = Uint8ClampedArray.from([0]);
From @xzing-scanner/library

**Comment by odahcam** [comment]
Sorry, I didn't understand very well what you're saying. But can you try to delete de `node_modules` folder and `package.lock` or `yarn.lock` file and install our modules again? Strange errors use to happen when npm handles upgrades with a lot of changes.

**Comment by thanhphuocdang** [comment]
I try to run with new project but look like ZXingmodule still not access any devices (camera).
 - Angular 6.1.0 vs IE11. Safari on IP5 is too.

However it is running well on chome and firefox latest version.
Iam just testing it. If you would not support for this old browsers, dismiss that.

**Comment by odahcam** [comment]
We have to include some polyfill for old ones, are you including them?

**Comment by odahcam** [comment]
I didn't tested IE for a while, so I can't say much here. But the method from probably is not available because IE doesn't supports `Uint8ClampedArray`, so you gonna need some extra `core-js` polyfill, be sure you included everything you need.

**Comment by odahcam** [comment]
As in the `polyfills.ts` file:

```typescript
/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
// import 'core-js/es6/symbol';
// import 'core-js/es6/object';
// import 'core-js/es6/function';
// import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/string';
// import 'core-js/es6/date';
// import 'core-js/es6/array';
// import 'core-js/es6/regexp';
// import 'core-js/es6/map';
// import 'core-js/es6/weak-map';
// import 'core-js/es6/set';
```

**Comment by redplane** [comment]
I have the same issue with `IE 11` - `Angular 6`

**Comment by odahcam** [comment]
Thanks @redplane , as it was just a missing polyfill, I'm closing. :)
