### ISSUE TITLE
Your browser does not support this feature, please upgrade it.

### ISSUE THREAD

**Issue by hoangnguyen208** [zxing-js/ngx-scanner#125]
#### Bug, feature request, or proposal:
I use angular 6 with the latest version of this library. I tried on several popular browsers with latest versions too, but no video camera shows up like in the demo. I inspected the element and below video element, it shows the texts 'Your browser does not support this feature, please upgrade it.'.

#### What are the steps to reproduce?
Here is the screenshot: https://imgur.com/a/fRiuzdk

**Comment by odahcam** [comment]
Does the demo works with the same browsers you tested?

**Comment by hoangnguyen208** [comment]
Yes, I meant the demo works fine, but when integrating into my angular app, the camera does not show. Do you know what the root cause is?

**Comment by odahcam** [comment]
In your print I can see autoplay set to `false`, so I think that's the cause, you gotta start the camera stream / scanner by yourself.

> 'Your browser does not support this feature, please upgrade it.'.

This is a text shown in the rendered document when the browser dosn't supports the `video` tag, written by ourselves. You just found it in the source, there's nothing wrong.

I will close as this isnot a bug, but I'm still able to help.

**Comment by hoangnguyen208** [comment]
But in your demo, camera still plays and I checked the `video` element that is : `<video class="customClass" autoplay="false" muted="true" playsinline="true" autofocus="true"></video>`

**Comment by odahcam** [comment]
All right, please try to download the demo and execute it locally.

**Comment by hoangnguyen208** [comment]
I just tried, then it threw an error: `formats.map is not a function
    at ZXingScannerComponent.set [as formats] (zxing-scanner.component.ts:91)`

**Comment by odahcam** [comment]
I think it is something with your local development environment, the same source is building fine at Travis and on my machine. 🤔

**Comment by odahcam** [comment]
Ah, `formats.map` is a way to discover/create hints to the decoder to increase decoding speed and chances to get a successful scan.

**Comment by hoangnguyen208** [comment]
Yes, you are probably right, I tried on another machine, it works well. Thank you so much for your help

**Comment by odahcam** [comment]
You are welcome, get in touch if something else happens, and feel free to join us on Gitter.

**Comment by PaulAhuevo** [comment]
Hi, I experience the same problem (Angular6). Did someone find a way to fix that problem?

**Comment by odahcam** [comment]
Please, provide OS, Browser and library verions.

**Comment by PaulAhuevo** [comment]
Version: "@zxing/ngx-scanner": "^1.2.1",
OS: MacOS
Browser: Chrome / Firefox / Safari, each latest version

**Comment by PaulAhuevo** [comment]
High Sierra, 10.13.6.

![image](https://user-images.githubusercontent.com/24651513/45978195-90d4b100-c043-11e8-9ab8-b5629469f05b.png)

**Comment by odahcam** [comment]
Please take a look at https://github.com/zxing-js/ngx-scanner/issues/125#issuecomment-410540442 I think it's the same case.

**Comment by acarbonellb** [comment]
Hello.

Suddenly not a single app that uses camera works under `Chrome 69.0.3497.100` in `MacOS 10.13.6` (my setup). I've tried a bunch of random websites that uses the camera and not a single one works:

https://hangouts.google.com
https://web.whatsapp.com/
https://webrtc.github.io/samples/src/content/getusermedia/gum/ ("official" test)

Here is the live demo from this repo -- same result :(
https://zxing-ngx-scanner.stackblitz.io/

No error from console, no HTMLElement.onloadedmetadata event fired, no nothing into <video>.
Maybe something has been updated and broken for good, but not in this repo.

Note: Safari is not working either.

Cheers.

**Comment by odahcam** [comment]
Working on Chrome 71.0.3558.0 and 71.0.3560.0 and MacOS 10.13.6. Safari is working fine btw. We can investigate this if you want, but we should go to another issue to discuss that, since this issue here has nothing to do with the real possible problem.

**Comment by acarbonellb** [comment]
Working now. Please check if your computer is not up for like a month like mine was. A stupid reboot and all working now. Rookie basics...

@odahcam sorry for wasting your time, and thanks for your help. Case closed for me.

**Comment by tonowie** [comment]
I keep having this issue in both chrome (Version 71.0.3578.80 (Official Build) (64-bit)
) and firefox. I see camera LED on my laptop blink once when page loads but  that is it. at first I thought it was because of Angular7 but I get the same thing with Angular6. Running on Linux.
I am trying to move from AngularJS where my scanner works fine so I believe it is not issue with my laptop. Am I missing something? 

None of the demos work for me but they do not even get as far as to even try the camera

- https://zxing-js.github.io/ngx-scanner/ dies on plenty of 404s
- https://zxing-ngx-scanner.stackblitz.io/ dies on cross origin red blocking
- https://embed.plnkr.co/MN4riU/ dies just with Error logged to console and keeps displaying loading

So it is nice I got as far as having the video element placed to DOM but how do I make it work?

**Comment by odahcam** [comment]
Damn, I'm definitely not happy with these examples. Have you tried to clone the repo and `ng serve` it?

**Comment by odahcam** [comment]
Also, StackBlitz is VERY slow, but it is working after some time of loading.

**Comment by tonowie** [comment]
npm install fails with this

> npm ERR! file /home/.../ngx-scanner/package.json
> npm ERR! code EJSONPARSE
> npm ERR! JSON.parse Failed to parse json
> npm ERR! JSON.parse Unexpected token } in JSON at position 3375 while parsing near '...nner"
> npm ERR! JSON.parse    }
> npm ERR! JSON.parse   }
> npm ERR! JSON.parse }
> npm ERR! JSON.parse '
> npm ERR! JSON.parse Failed to parse package.json data.
> npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

**Comment by odahcam** [comment]
In future versions it will autoselect the first available camera, I disabled it by mistake some time ago and it stayed like that. Thanks for your patience.

**Comment by tonowie** [comment]
sorry for bugging you, hopefully it will help someone :) once the demo got working it was easy to understand what is wrong but without it I was clueless

**Comment by odahcam** [comment]
Yeah, I wanna fix the demo with #150, that's **very** needed.
