### ISSUE TITLE
formats.map is not a function

### ISSUE THREAD

**Issue by Jutosa** [zxing-js/ngx-scanner#128]
**Describe the bug**
I cloned and ran the repository and get an error saying that formats.map is not a function. The application then stops and the device list remains empty.

I assume this has to do with 
`<zxing-scanner #scanner start="true" [device]="currentDevice" (scanSuccess)="handleQrCodeResult($event)" formats="['CODE_39', 'CODE_128', 'QR_CODE']"></zxing-scanner>` 

When I remove formats, the application runs but it doesn't get any results. Maybe it doesn't know what it is looking for anymore?

I did not change the files, I tried to ran them as is.

**To Reproduce**
1. Clone the current master
2. npm install
3. ng serve --open

**Expected behavior**
I can select a device, the video feed starts and results are found for the defined formats.

**Screenshots**
* https://i.imgur.com/gdgtFcc.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 61.0.2, Chrome  68.0.3440.106 
 - Angular: 6.1.2

**Comment by odahcam** [comment]
That's very strange, `formats` should be an `array`.  🤔 

I'll try it.

**Comment by odahcam** [comment]
I found the error, looks like I wrongly binded the formats attribute in the template. Your solution is very valid. Thanks. :)

**Comment by odahcam** [comment]
Well, it is fixed, I just didn't released it yet.
