### ISSUE TITLE
 Excuse me, how can I quote this library in the angular project, thank you.

### ISSUE THREAD

**Issue by bestbelief** [zxing-js/ngx-scanner#131]

**Comment by odahcam** [comment]
What you mean with example? This is not just an example, it's a module/package you install in your application.

**Comment by bestbelief** [comment]
Thank you. I am a rookie. So I just saw README before, I don't feel very detailed and I don't know how to use it. I saw Wiki just now, I feel much better.

**Comment by odahcam** [comment]
Nice! I'll be closing this for now, feel free to open new issues or get in touch in [Gitter](https://gitter.im/zxing-js/ngx-scanner). 🙂
