### ISSUE TITLE
How do we get permission from users to use cameras?

### ISSUE THREAD

**Issue by bestbelief** [zxing-js/ngx-scanner#133]
I'm sorry to disturb you again. How do you get permission from users to use the camera? I looked at your code carefully, but I still couldn't read it. I hope you can give us some guidance.

**Comment by bestbelief** [comment]
ok,thank you verymuch!

**Comment by odahcam** [comment]
Just to make things clear, the component itself asks the user for permissions the time it tries to start scanning, that should be automatic for you 😄

**Comment by ManiyanKarthi** [comment]
What was the issue there, is the device not supported?

**Comment by odahcam** [comment]
He wanted to manually get the user's media input devices.

**Comment by sawrubgupta** [comment]
But in some browser it doesnt ask for permission !

**Comment by sawrubgupta** [comment]
Hey !
Thank you for your library !
I am facing a issue, Its not able to open the camera permission in some browser, like in my android chrome, its working fine but in my other embeded browser - its not opening the camera, i am using undefine on devicee id to open default back camera.
![image](https://user-images.githubusercontent.com/55241111/131205957-df19ad93-0dfb-4cce-a744-e82280919fca.png)
