### ISSUE TITLE
The component is not notifying any failure or error event on stream

### ISSUE THREAD

**Issue by odahcam** [zxing-js/ngx-scanner#135]
**Describe the bug**
As title says, plus this occours because some `catchError` in the `browser-code-reader` is suppressing the exception visibility from the scanner component.

**To Reproduce**
1. Just try with the demo.

**Expected behavior**
Events to be notified.

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version 1.2

**Additional context**
~I like puppies.~

**Comment by sriharsha566** [comment]
any update on this?

**Comment by odahcam** [comment]
For the reasons I reported, it's solved.
