### ISSUE TITLE
Return Promise or Observable in methods that access the hardware

### ISSUE THREAD

**Issue by acarbonellb** [zxing-js/ngx-scanner#138]
**Is your feature request related to a problem? Please describe.**
Some methods like scan(), changeDevice(), etc, don't take effect in an instant fashion due to hardware access. For example, when changing the device (i.e. toggling front/back camera), there is a gap of time between the method returning and the actual video being displayed, so in code we're unable to determine _when_ the "whole" action is completed. That gap, also, depends on hardware specs and performance, so it's always a variable time.

**Describe the solution you'd like**
It would be nice having those methods returning a promise when the video is actually playing.

**Describe alternatives you've considered**
A new EventEmitter (i.e. `@Output() videoReady`) to notify whenever a new stream becomes visible, independently of the fore-mentioned methods, so no need to change them.

**Additional context**
A direct benefit  would be the possibility of making smooth transitions between this states, fading-out/in the video container, triggering animations, etc, vs the current abrupt video transition with no control over it.

Btw, thanks for such a nice component :)

**Comment by acarbonellb** [comment]
I've workarounded this by listening to the `HTMLElement.onloadedmetadata` event, like this:

```
<zxing-scanner #scanner ...></zxing-scanner>

...

@ViewChild('scanner')
private scanner: ZXingScannerComponent;
private video: HTMLVideoElement;

ngAfterViewInit(): void {
    this.video = document.getElementsByTagName('video')[0];
}

function startScan(deviceId: string) {
  this.scanner.scan(deviceId);
  new Promise(resolve => this.video.onloadedmetadata = resolve)
    .then(() => console.log('Video is displaying')) // Here! Fire an event or do whatever you want.
    .catch(e => console.error(e));
}
```

This also works when changing cameras.
Feels a bit hacky, tho.

**Comment by acarbonellb** [comment]
I've workarounded this by listening to the `HTMLElement.onloadedmetadata` event, like this:

```
<zxing-scanner #scanner ...></zxing-scanner>

...

@ViewChild('scanner')
private scanner: ZXingScannerComponent;
private video: HTMLVideoElement;

ngAfterViewInit(): void {
    this.video = document.getElementsByTagName('video')[0];
}

public startScan(deviceId: string) {
  this.scanner.scan(deviceId);
  new Promise(resolve => this.video.onloadedmetadata = resolve)
    .then(() => console.log('Video is displaying')) // Here! Fire an event or do whatever you want.
    .catch(e => console.error(e));
}
```

This also works when changing devices.
Feels a bit hacky, tho.

**Comment by odahcam** [comment]
While I agree with all you said, I must say that the animation should not live here inside the component, of course animations are cool, but it's not the focus of this component, you should be able to implement your own animations on the top of our API, so maybe we should do some work on that API to make it possible instead of forcing every user to have some choosen-by-us animation inside its project.

**Comment by odahcam** [comment]
Also, I forgot to say that I'm aware of this problem and I'm working to achieve this in every version, but I couldn't get there yet. That said, if you wanna make a PR then we would be very thankful. Thanks for the issue btw.

**Comment by acarbonellb** [comment]
Of course animations are independent of this component! I agree with you. Maybe I didn't explained myself well:

My request was for a mechanism to notify when the video is ready, *only that*, so we can implement our own callbacks based on that event, including but not limited to animations. Animations was only an example of things we could do in our own UI when listening to the events of this component.

I think I could do a PR but I'm not sure if there are some side effects with my workaround, because I'm overwriting the HTMLElement.onloadedmetadata property. I don't know if it's used internally for something, although to be honest it seems to be working just fine.

**Comment by odahcam** [comment]
![](https://i.imgur.com/0AXlBTh.gif)

Just do the PR then, I can fix any breaking change.
