### ISSUE TITLE
Resize area of searching for QRCode

### ISSUE THREAD

**Issue by renatomullerventura** [zxing-js/ngx-scanner#139]
Hi.

I've been working on a project to search prices in a physical showcase using qrcode on each product. I realized that in one page there are so many qrcode that I can't scan just one without my camera loosing focus/blurring.

When I get the camera close to the codes, it blurs, when I pull away it gets more than one qrcode and it doesn't work.

Is there a chance/way to resize the scan area to get just what you want? Like croping an image, but with a video.

**Comment by odahcam** [comment]
Yes, you can crop the video stream. But no, I don't think our component supports that at this moment. Some months ago, some folks have done that with the base library, so I know you can do that with our code, but I think that this is not possible yet with the component.

We could implement some injection token for the `MultiformatCodeReader` so you could implement your own code reader (maybe by extending the default) and adding the custom crop functionality before the decode.

This is a very complex feature to implement by myself right now, so I'm afraid that's all I can do at the moment. 🙁

**Comment by odahcam** [comment]
This is a duplate of #122 BTW, so I see you there.
