### ISSUE TITLE
IOS12 iphone/ipad

### ISSUE THREAD

**Issue by AndyTUYR** [zxing-js/ngx-scanner#140]
There seems to be an issue on IOS12 when the scanner is reset and started again that qr codes are no longer detected. (replicated on numerous iphones and ipads with IOS12 installed)

This can be replicated in the demo.  

**To Reproduce**
1. Go to https://zxing-js.github.io/ngx-scanner/
2. Select a camera
3. Scanning Qr codes works
4. Toggle scanning off and then on again
5. Scanning Qr codes no longer works

You can also replicate by going to the url, selecting a camera which scans, however if you change the camera to no device and back to the camera again scanning no longer works.

If you follow the above on an IOS 11.4.1 device it works correctly.

Any advice on the above would be appreciated.

**Comment by odahcam** [comment]
I experienced something similar to that. I'm rewriting the continuous scanning algorithm, so I expect to fix this the next patch. :)

**Comment by odahcam** [comment]
This is probably related to #126.
