### ISSUE TITLE
Unable to scan Data matrix on the back of Swedish driverslicenses

### ISSUE THREAD

**Issue by mattiaskagstrom** [zxing-js/ngx-scanner#141]
**Describe the bug**
Unable to scan Data matrix

**To Reproduce**
try to scan
![image](https://user-images.githubusercontent.com/3661126/46906020-d70f8880-cefc-11e8-81c3-c1ffe3cccd35.png)

on demo page (or in you own app) https://zxing-js.github.io/ngx-scanner/

**Expected behavior**
The value should be outputted

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 69

**Comment by odahcam** [comment]
I'm afraid the DataMatrix reader was disabled on the demos. 

![image](https://user-images.githubusercontent.com/3942006/46923240-87f45100-cfeb-11e8-9985-17b75b05d4fa.png)

Was this the expected result?

**Comment by mattiaskagstrom** [comment]
Yupp, and im able to scan my card in the stackblitz demo aswell. issue may be marked as solved.

Is there anything special i need to do to activate it in my own code?

**Comment by odahcam** [comment]
By default only the QR code decoder comes enabled, there's some options to enable the others, I think the most simple is this one:

```html
<zxing-scanner [formats]="['QR_CODE', 'EAN_13', 'CODE_128', 'DATA_MATRIX']"></zxing-scanner>
```

As you can see, you can use the `formats` property to achieve that.

If you want to read more: https://github.com/zxing-js/ngx-scanner/pull/112#issuecomment-403974038

Good luck! 🍻

**Comment by mattiaskagstrom** [comment]
Great!

Could you add that to: https://github.com/zxing-js/ngx-scanner/wiki/Getting-Started and/or https://github.com/zxing-js/ngx-scanner/wiki/Advanced-Usage ??

**Comment by odahcam** [comment]
Of course: https://github.com/zxing-js/ngx-scanner/wiki/Getting-Started#choosing-what-decoders-to-run

*I should've already added that before anyway.*

**Comment by mattiaskagstrom** [comment]
Thats why I thought it didn't work when I added <zxing-scanner></zxing-scanner> to my app ;)

is there a list of all avalible formats?

**Comment by odahcam** [comment]
Yeah! This feature relies directly on the ZXing's core, so you can find it here: https://github.com/jojastahl/library/blob/master/src/core/BarcodeFormat.ts

**Comment by mattiaskagstrom** [comment]
Sweet, you have made my monday :D
