### ISSUE TITLE
createObjectURL soon to be deprecated for media streams

### ISSUE THREAD

**Issue by mrz5018** [zxing-js/ngx-scanner#144]
**Describe the bug**
Looks like one of the methods used is going to be deprecated (as per the Chrome inspector):

```
modules.js?hash=... [Deprecation] URL.createObjectURL with media streams is deprecated 
and will be removed in M71, around December 2018. Please use HTMLMediaElement.srcObject 
instead. See https://www.chromestatus.com/features/5618491470118912 for more details
```

**To Reproduce**
1. Nothing in particular, just have a `zxing-scanner` in a template.

**Expected behavior**
Just need to do what the 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs Mojave
 - Browser: Chrome
 - Version: V69

**Additional context**
I can make this change if you guys want me to open up a pull request just let me know.  Thanks.

**Comment by odahcam** [comment]
This problem lives in this method:

https://github.com/zxing-js/ngx-scanner/blob/d4a0c32c4aae2bc43355162b761c50ffc48a5792/src/app/modules/zxing-scanner/browser-code-reader.ts#L170-L179

As you can see, it should be only used as a workaround/fallback for browsers not supporting `srcObject`.

Now I think that if we remove that, we gonna lose the fallback and also the support for older browsers, or am I wrong?

**Comment by mrz5018** [comment]
You're right, that is a good idea to keep in as a backup for old browsers.  In attempting to recreate my issue again, I think I got to the root cause of my warning.  

My browser does implement `HTMLMediaElement.srcObject`, but the warning occurs when I destroy the component while `bindVideoSrc()` is running.  It looks like the async call of `startDecodeFromStream()` runs after the component is destroyed.  During that call the `this.videoElement` is undefined.

I think that this would be a good place for an observable (instead of the promise).  Maybe as a short term fix (because the failure doesn't create too much of a problem) there can just be an if check thrown around the code:

```
private startDecodeFromStream(stream: MediaStream, callbackFn?: (result: Result) => any): void {
    this.stream = stream;
    this.checkTorchCompatibility(this.stream);
    if ( this.videoElement) {
       this.bindVideoSrc(this.videoElement, this.stream);
       this.bindEvents(this.videoElement, callbackFn);
    }
  }
```

**Comment by odahcam** [comment]
I'm trying yo eliminate those "`callback`" parameters and make everything Promisible, but I agree that in some places Observables does apply better than Promises. Before changing the returned object, I think we should get rid of that callback to have a better perspective of what the function does and needs.

Maybe for the solution, intead of checking for the `this.videoElement` we could just call `this.prepareVideoElement(this.videoElement);`. What you think?
