### ISSUE TITLE
401 Unauthorized when trying to install the package

### ISSUE THREAD

**Issue by alijohn** [zxing-js/ngx-scanner#147]
Hi mate,

Thanks you for this wonderful library. I was trying to have a go and install the package via

'npm i @zxing/ngx-scanner@latest --save'

And I am getting 

npm ERR! code E401
npm ERR! 401 Unauthorized: @zxing/ngx-scanner@latest

Help!!

**Comment by alijohn** [comment]
Please ignore or delete - User error :(

**Comment by odahcam** [comment]
No problem. :)
