### ISSUE TITLE
Could not start video source when place zxing in modal and change to back camera

### ISSUE THREAD

**Issue by redplane** [zxing-js/ngx-scanner#151]
Hi,

I'm using `zxing/ngx-scanner` for my web app.
Everything seems to be fine until I put `zxing/ngx-scanner` in a [ngx-bootstrap modal](https://valor-software.com/ngx-bootstrap/#/modals)

The exception that thrown back was: 

**DOMException: Could not start video source**

This is my debugger image:
![error](https://user-images.githubusercontent.com/7974095/47960215-61e22f80-e032-11e8-8b32-5644138545e7.png)

I have made a repo on [stackbliz](https://stackblitz.com/edit/angular-playground-cztk8r?file=app%2Fmodules%2Fdashboard%2Fdashboard.component.html)

Could anyone help please ?

Thanks,

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: Android Xperia XA1
 - Browser [e.g. stock browser, safari]: Chrome 70

**Comment by redplane** [comment]
As far as I know I haven't stopped the stream which has been initialized when I used `getUserMedia` at the first time.

When I stopped that stream, everything seems to be fine.
I already modified the stackbliz repo.
Perhaps that's why you can see it worked :D .

I think this can be closed.
Thank you for your response.

**Comment by odahcam** [comment]
No problem. 🙂
