### ISSUE TITLE
Do not automatically ask for camera permission when ngx-scanner is initialized.

### ISSUE THREAD

**Issue by redplane** [zxing-js/ngx-scanner#152]
Hi,

I want to submit a new feature request.
When I added `zxing/ngx-scanner` in to my component, I realized that as long as I access the component, `zxing/ngx-scanner` automatically asks for camera access permission.

That doesn't make sense, because sometimes, I just want to place `zxing/ngx-scanner` as a hidden component, when a condition met, it will be shown up and that time, it will ask for camera access permission.

I would like to suggest that, `zxing/ngx-scanner` should look for `[scannerEnabled]`. When `[scannerEnabled]` is true, `zxing/ngx-scanner` will ask for camera permission.

This is my [repo](https://stackblitz.com/edit/angular-playground-cztk8r?file=app%2Fmodules%2Fdashboard%2Fdashboard.component.html), in my example I would like when the modal is shown up, that time `ngx-scanner`  will ask for camera permission.

Thank you,

**Comment by odahcam** [comment]
That should be the expected behaviour.
