### ISSUE TITLE
When I run npm run build --prod, it does not work

### ISSUE THREAD

**Issue by peterramaldes** [zxing-js/ngx-scanner#153]
**Describe the bug**
I made a fork of the project, I ran a npm run build:prod, I uploaded it to the web server.
When I went to test both in the computer browser and on the mobile phone, neither works.

I am trying to apply the qrcode scanner on my Angular 6 PWA project.

**To Reproduce**
1. Fork this project
2. Run npm install
3. Run npm run build:prod
4. Grab the generated files in the dist folder and push to the web server

**Expected behavior**
Device camera is not detected

**Screenshots**
http://prntscr.com/lex39k

**Desktop:**
 - OS: Windows 10
 - Browser : Chrome
 - Version: 70.0.3538.77

**Smartphone:**
 - Device: Asus Zenfone 4 Selfie
 - OS: Android 8.1.0
 - Browser: Chrome
 - Version: 70.0.3538.80

**Comment by odahcam** [comment]
The component seems to be working as expected. As I see, you're probably not under HTTPS, which is required for `getMediaDevices` API access.

Please note that forking the project is not the recomended way to use it, you should prefer using it trough some package manager as npm or yarn.

Thanks.

**Comment by peterramaldes** [comment]
Thanks for the feedback.

I will make the necessary corrections

**Comment by odahcam** [comment]
You're welcome, feel free to ask anytime. :)
