### ISSUE TITLE
Message "No permission" still display beside the camera name when scanning with android application (APK)

### ISSUE THREAD

**Issue by thanhphuocdang** [zxing-js/ngx-scanner#155]
**Describe the bug**
The message "No permission" still display when I allowed application access camera and it is ready to scan.
**Screenshots**
![img_0330](https://user-images.githubusercontent.com/41668114/48456064-30b2ed80-e7f0-11e8-9c8d-be9052493b5d.JPG)
**Smartphone (please complete the following information):**
 - OS: [Android]
 - Browser [APK]

**Comment by odahcam** [comment]
Whats that, Ionic?

**Comment by thanhphuocdang** [comment]
By Cordova

**Comment by odahcam** [comment]
Maybe you should check your android for permission. Theres a permission API in draft that Im considering to implement here, do you have any ideia if that works inside Cordova? If it works we can make some tests.

**Comment by odahcam** [comment]
Understood, do you have any console logs of it?

**Comment by thanhphuocdang** [comment]
I have not the console logs yet, I still do not know how to get it.
Do you know that?

**Comment by odahcam** [comment]
Sorry, I don't know much about Cordova. :/

Can you post this kinda info here when you get it?

**Comment by thanhphuocdang** [comment]
Sure, I will notify you when new information arrives.

**Comment by odahcam** [comment]
Maybe `getUserMedia` is not supported in this WebView you're using, have you tested it?

**Comment by tonowie** [comment]
Well the scanner works fine for me. I can scan and I can switch between cameras. I just do not get the labels of devices. So it kind of works and does not work at the same time

**Comment by odahcam** [comment]
I see a problem like this before in some browsers that asked for permission to list the cameras, but not enough to list its names, the funny fact is that every time I selected a camera, the browser always asked me the camera permission again. Maybe it could be something like this.

**Comment by thatham** [comment]
i'm gettting the same problem

**Comment by thanhphuocdang** [comment]
I am going to leave this one now. If there is no problem, you can close this topic.
