### ISSUE TITLE
#### Why is not support PWA?

### ISSUE THREAD

**Issue by NiwatTipboonchu** [zxing-js/ngx-scanner#156]
#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/fork/zxing-ngx-scanner<br/>

**Comment by odahcam** [comment]
We do support, but Apple doesn't. Read https://caniuse.com/#search=getusermedia .
