### ISSUE TITLE
Decode Image Feature

### ISSUE THREAD

**Issue by KarishImrith** [zxing-js/ngx-scanner#158]
I need to be able to read a barcode from an image (in Base64).

Your library works so well and supports many formats, I think the feature belongs here instead of using another library.

I am sure that it will be easy for you to allow us to use a "decode" function from your libary so that we can decode an image.

Kindly assist.

**Comment by odahcam** [comment]
I think it's already possible. 🤔 

There's a decode method in browser layer that accepts a URL, so the base64 can be passed as a URL as well. But there's one problem, there's a few bugs in the browser layer so I don't know how it will behaves, I'm trying to improve that but I still no lucky. 😞 

Anyway, [here](https://github.com/zxing-js/library) you gonna find what you need, it's the base library for this scanner, see you there.

**Comment by KarishImrith** [comment]
Hi, 

Thanks for the information.

Unfortunately the link you sent does not support PDF417 which is one of my requirements.

Could you possibly send me some code so that I can try through the browser later :)

Your assistance is much appreciated.

**Comment by odahcam** [comment]
Well, I do not know of any PDF417 supporting library until now, sorry.

Fun fact: if you've installed this component, @zxing-js/library is already installed in your project, so you can just start using it.

I'd appreciate if you could go to the PDF417 issue (https://github.com/zxing-js/library/issues/59) on the base lib and make your voice there, maybe some of the commenters can help you. :)

**Comment by KarishImrith** [comment]
Thanks, I will follow it up.

And Lol! Thanks for the fun fact that I completely missed.

Appreciate your prompt assistance.

**Comment by odahcam** [comment]
You're welcome.
