### ISSUE TITLE
ERROR DOMException: "Index or size is negative or greater than the allowed amount

### ISSUE THREAD

**Issue by exasky** [zxing-js/ngx-scanner#159]
**Describe the bug**
When displaying ngx-scanner, there is a chance that this exception is thrown:
'DOMException: "Index or size is negative or greater than the allowed amount"' leading to an impossibility to decode qrcodes

**To Reproduce**
1. add ngx-scanner in html like:
 <zxing-scanner [device]="foundCamera"
                           [scannerEnabled]="scannerEnabled"
                           (scanSuccess)="scanSuccessEvent($event)"></zxing-scanner>
2. Make the scannerEnabled var change
3. Repeat until seeing the error
4. Try to decode qrcode

**Expected behavior**
This error shouldn't be displayed and qr codes should be decoded

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 64.0 (64 bits)

**Smartphone (please complete the following information):**
N/A

**Additional context**
I'm using angular material tabs to display content.
In one of the tabs, there is the scanner.
But, when I'm leaving/going back on the tab container the scanner, it freezes and doesn't decode qrcodes anymore. That's why I tried with scannerEnabled input to unfreeze the scanner.

Also, to bypass the error, I tried using  resetCodeReader(), restartScan() and refreshCodeReader() methods

**Comment by odahcam** [comment]
I see, this all may be bound to recent introduced behaviors. I will take a look on that as soon as possible.

**Comment by amielouise2** [comment]
any fix on this?  I'm getting the same error

**Comment by amielouise2** [comment]
I am under the gun, I'm wondering if it has to do with passing in a string video element id to decodeFromInputVideoDevice.  Is there a way I can send an actual HTMLVideoElement instead?  I've set my video element to same widths as your code (200 x 200) but that made no difference.
