### ISSUE TITLE
Correct version for Angular 4.

### ISSUE THREAD

**Issue by sauravgaursmith** [zxing-js/ngx-scanner#160]
Hi Guys

What version should use for Angular 4 to maintain compatibility ?

Thanks

**Comment by odahcam** [comment]
The last one I know is v0.3.4, but I must say we don't support Angular 4 for a while so I hope everything works for you. :)

**Comment by sauravgaursmith** [comment]
Thanks buddy for your quick answer.

**Comment by odahcam** [comment]
You're welcome. 😉
