### ISSUE TITLE
Karma tests breaks after installing zxing library.

### ISSUE THREAD

**Issue by sanidz** [zxing-js/ngx-scanner#162]
#### Bug:
After installing package in angular 5 cli project, karma tests breaks

#### What is the expected behavior?
Karma tests work.

#### What is the current behavior?
When running > npm run test
I get error with description:

> ng test

 10% building modules 1/1 modules 0 active14 01 2019 12:58:19.938:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
14 01 2019 12:58:19.940:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
14 01 2019 12:58:19.950:INFO [launcher]: Starting browser14 01 2019 12:58:42.143:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: Connected on socket twrGnxerksiI2pufAAAA with id 37695310
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'Uint8ClampedArray.from([0])')
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:8955
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'Uint8ClampedArray.from([0])')
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:8955
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'Uint8ClampedArray.from([0])')
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:8955

PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'Uint8ClampedArray.from([0])')
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:8955

PhantomJS 2.1.1 (Windows 8.0.0): Executed 0 of 0 ERROR (1.228 secs / 0 secs)

#### What are the steps to reproduce?
-> npm run test

#### What is the use-case or motivation for changing an existing behavior?
Usage of barcode scanner as library.

#### Which versions of Angular, `ngx-scanner`, OS, TypeScript, browsers are affected?
 "dependencies": {
        "@angular/animations": "~5.1.3",
        "@angular/cdk": "~5.0.3",
        "@angular/common": "~5.1.3",
        "@angular/compiler": "~5.1.3",
        "@angular/core": "~5.1.3",
        "@angular/forms": "~5.1.3",
        "@angular/http": "~5.1.3",
        "@angular/material": "~5.0.3",
        "@angular/platform-browser": "~5.1.3",
        "@angular/platform-browser-dynamic": "~5.1.3",
        "@angular/router": "~5.1.3",
        "@ngx-translate/core": "^9.0.2",
        "@ngx-translate/http-loader": "^2.0.0",
        "@ngxs/logger-plugin": "^3.2.0",
        "@ngxs/store": "^2.0.0",
        "@zxing/ngx-scanner": "^1.3.0",
        "angular-calendar": "^0.23.1",
        "angular2-signaturepad": "^2.8.0",
        "classlist.js": "^1.1.20150312",
        "core-js": "~2.5.1",
        "intl": "^1.2.5",
        "material-design-icons": "^3.0.1",
        "md2": "0.0.29",
        "rxjs": "~5.5.2",
        "web-animations-js": "^2.3.1",
        "zone.js": "~0.8.18"
    },
    "devDependencies": {
        "@angular/cli": "~1.5.0",
        "@angular/compiler-cli": "~5.1.3",
        "@angular/language-service": "~5.1.3",
        "@angular/service-worker": "^1.0.0-beta.16",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "codelyzer": "~4.0.1",
        "cross-env": "^5.2.0",
        "increase-memory-limit": "^1.0.6",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "karma-phantomjs-launcher": "^1.0.4",
        "karma-scss-preprocessor": "^3.0.0",
        "karma-spec-reporter": "0.0.32",
        "node-sass": "^4.5.3",
        "protractor": "~5.1.2",
        "ts-mockito": "^2.2.5",
        "ts-node": "~3.3.0",
        "tslint": "~5.8.0",
        "typescript": "~2.4.2"
    }

#### Is there anything else we should know?
I searched and maybe jasmine version makes problems, but even with 2.5.2 or 2.4.1 I got the same error.
Any hints what could be causing this issue is much much appreciated because I want to implement barcode scanning as library and not by using intent filters and callback urls with native app since they dont have needed behavior in angular PWA on multiple android devices!

**Comment by sanidz** [comment]
I reinstalled the package again but no luck, however I did found a workaround.

1. Do not import ZXingScannerComponent 
import { ZXingScannerComponent } from '@zxing/ngx-scanner';

2. Use any for dom component reference type:
@ViewChild('scanner') scanner: any;

Thats it, testing with PhantomJS works (dont ask why I dont migrate to Chrome).

**Comment by sanidz** [comment]
After some testing these are results:
@zxing/ngx-scanner couldnt trigger scanComplete event so I tried installing @zxing/library.

Library does work, but issue with failing PhantomJS + karma tests remains.

> ng test
 10% building modules 1/1 modules 0 active14 01 2019 17:05:22.420:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/14 01 2019 17:05:22.440:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency14 01 2019 17:05:22.448:INFO [launcher]: Starting browser PhantomJS                     14 01 2019 17:05:43.020:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: Connected on socket qMlqinEyHK7mXrIJAAAA with id 91574190PhantomJS 2.1.1 (Windows 8.0.0) ERROR  TypeError: undefined is not a constructor (evaluating 'Uint8ClampedArray.from([0])')
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:9187PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'Uint8ClampedArray.from([0])')
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:9187
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'Uint8ClampedArray.from([0])')  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:9187
PhantomJS 2.1.1 (Windows 8.0.0) ERROR  TypeError: undefined is not a constructor (evaluating 'Uint8ClampedArray.from([0])')
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:9187

**Comment by odahcam** [comment]
Whats your node version?

**Comment by odahcam** [comment]
Adicional note: https://github.com/mobxjs/mobx/issues/160#issuecomment-196573831

> Thats it, testing with PhantomJS works (dont ask why I dont migrate to Chrome).

Maybe, just maybe, you should give it a try. Or try upgrading Phaton or even maybe inject some TypedArray polyfill.

**Comment by sanidz** [comment]
Thank you kind Sir, your answer helped me to research more and to include polyfils.
Solution is to modify polyfills.ts file in Angular 5 project and to include typed in which Uint8ClampedArray is.

import 'core-js/es6/typed';

All the best :)

**Comment by odahcam** [comment]
Thanks and good luck. :)
