### ISSUE TITLE
No device were found iphone 5s ios 10.3.3 in Safari

### ISSUE THREAD

**Issue by HamzaDevz** [zxing-js/ngx-scanner#163]
#### Bug:
No device were found, i'm using an iPhone 5s in ios 10.3.3 with Safari.

#### What is the expected behavior?
The scanner ask the permission to access to the camera, then it displays.

#### What is the current behavior?
The camera is not found, no permission is asking...

#### What are the steps to reproduce?
In the starter https://stackblitz.com/fork/zxing-ngx-scanner<br/>
I got the message no device were found...

#### Hardware
Iphone 5s

#### Software
IOS 10.3.3
SAFARI

**Comment by HamzaDevz** [comment]
Okay after a little search in https://caniuse.com/#search=getusermedia
Safari with iOS <= 10.x.x is unsupported... I close this issue.

**Comment by odahcam** [comment]
Maybe an unsupported message should be added.

**Comment by HamzaDevz** [comment]
I have a bug only with the iPhone 6s and iOS 12, it doesn't display camera... blank screen..

**Comment by odahcam** [comment]
Would you like to file a new issue?
