### ISSUE TITLE
Doesn't work. Blank Page on iPhone and Desktop.

### ISSUE THREAD

**Issue by lipidfish** [zxing-js/ngx-scanner#164]
**Describe the bug**
Pages with this component display nothing. 
Browsers: Chrome (Mac) v 71.0.3578.98
Safari (Mac) v 12.0.2
Mobile Safari (ios 12.1.2)
Angular v 6.1.0
Angular cli v 6.1.5

**To Reproduce**
1. use npm to install: npm i @zxing/ngx-scanner@latest --save
2. Imported to module: import { ZXingScannerModule } from '@zxing/ngx-scanner';
3. Added to Imports array in module
4. Added line to component's html file: <p>Scanner:</p> <zxing-scanner></zxing-scanner>
5. ng serve
6. Navigate to path displaying the component
7. Observe that the only thing on the page is "Scanner:"

**Expected behavior**
I expected to see "Scanner:" followed by a camera image allowing me to scan a barcode.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2 (Mojave)
 - Browser Chrome (Mac) v 71.0.3578.98, Safari 12.0.2

**Smartphone (please complete the following information):**
 - Device: iPhone 10xs
 - OS: iOS 12.1.2
 - Browser Safari, Chrome

**Comment by vincentbouillart** [comment]
i have the same issue

**Comment by odahcam** [comment]
That's really a problem, the following line expects a value that's not already defined:

https://github.com/zxing-js/ngx-scanner/blob/742574321b3d284557d1f0bcc00dc08a87904432/src/app/modules/zxing-scanner/zxing-scanner.component.ts#L300

**Comment by Luukschoen** [comment]
Experienced the same problem. Was pretty easy to solve by just listening to the camerasFound event and then set the desired device id to the scanner.

```
  <zxing-scanner #scanner (camerasFound)="camerasFoundHandler($event)" (scanComplete)="scanCompleteHandler($event)"></zxing-scanner>

  camerasFoundHandler(event) {
      this.scanner.scan(event[0].deviceId);     
  }
```

**Comment by odahcam** [comment]
Thanks for all the patience with this error, we really need e2e tests to avoid this kind of regression. 🙁

**Comment by naiduashok** [comment]
I have used 
camerasFoundHandler(event) {
      this.scanner.scan(event[0].deviceId);     
  }

but on ios not opening the camera. It is asking for the permission, but not sure why it is not opening the camera. I am using IOS 12.3. Not showing any log

On Android device it works fine

**Comment by sohlich** [comment]
On Chrome:
Google Chrome	75.0.3770.103 (Official Build) stable (64-bit)
Revision	237c346ae93b...
OS	iOS
User Agent	Mozilla/5.0 (iPhone; CPU iPhone OS 12_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/75.0.3770.103 Mobile/15E148 Safa

Seems the MediaDevices.getUserMedia() API is not supported. Logs:
WARNING: zxing-scanner device Unselected device.
ERROR: zxing-scanner askForPermission Can't get user media, this is not supported.
ERROR: zxing-scanner enumarateVideoDevices Can't enumerate devices, method not supported.

**Comment by odahcam** [comment]
Only Safari supports `getUserMedia` in iOS.

**Comment by Neknail** [comment]
Regards supporting others browsers in iOS, I found a workaround from [qrsnapper](https://qrsnapper.appspot.com/). It uses a hidden input element with its 'capture' attribute as 'camera' instead. If `getUserMedia` is not supported, then the button will display. The system camera will be loaded after user click it.

`<input type="file" accept="image/*" capture="camera" id="qrcode-input" name="qrcode" class="CameraFallback-input">`

It's not perfect, since decoding only be triggered in the callback handler after user clicks the capture button, which means user might try several times until he/she finds the right angle or distance to get the detectable shot. Obviously, it's not convenient enough, but it gives users/developers another choice when they have to use other mobile browsers.

@odahcam, could you consider this workaround? Please refer to its [repo](https://github.com/PaulKinlan/qrcode) mentioned above.

**Comment by odahcam** [comment]
Yes, this could be a workaround, but unfortunately I have no time to develop this now. PRs still welcome.

**Comment by sohlich** [comment]
I've personally implemented that in my app. But the result and user experience are very poor. I would not recommend integrating this into the lib, maybe just mention in the wiki as a workaround.

**Comment by odahcam** [comment]
I liked this idea, maybe a demo code it this workaround would be enough.

**Comment by Sireini** [comment]
I checked the answers here but when I am implementing this it throws me this error: this.scanner.scan is not a function

I am also not able to see the camera active

**Comment by odahcam** [comment]
Please open a new issue and provide some demo code or something, thanks.

**Comment by Neknail** [comment]
Good news, the issue has been fixed by WebKit dev. team. Please refer to below links
https://bugs.chromium.org/p/chromium/issues/detail?id=752458#c41
https://bugs.webkit.org/show_bug.cgi?id=208667
