### ISSUE TITLE
Support fo Aztec

### ISSUE THREAD

**Issue by ghost** [zxing-js/ngx-scanner#166]
I've tried to scan Aztec Code. I've added aztec format to allowed format like this:

<zxing-scanner [formats]="['QR_CODE', 'EAN_13', 'CODE_128', 'DATA_MATRIX', 'AZTEC']"></zxing-scanner>

Although the Aztec Code type is available BarcodeType.ts I'm not sure that aztec is already supported. 

I will be grateful for confirmation.

**Comment by odahcam** [comment]
Hello, this is not supported yet, this issue depends on https://github.com/zxing-js/library/pull/123 .

Once library's PR is merged and a version with it get's published, this scanner will automatically support the Aztec format.

**Comment by 10eputzen** [comment]
any update?

**Comment by odahcam** [comment]
Just this: https://github.com/zxing-js/library/pull/123#issuecomment-502456023
