### ISSUE TITLE
Use Component in Cordova App

### ISSUE THREAD

**Issue by pilz97** [zxing-js/ngx-scanner#167]
Hello,

I'm developing a angular cordova app.. I tried to use this plugin but i didn't got it to work!

When I use the plugin I can only see a "black box", from the permission Response I get null as a answer!

That's why i wanted to ask: Is it possible to use the plugin with cordova and if yes how do I get the permission?

Thanks!

**Comment by odahcam** [comment]
Could you post some print or logs for us to understand the issue better?

**Comment by pilz97** [comment]
Thanks for the quick reply!

The big Play smybol you can see on the screenshot is all i get when i use: 
`<zxing-scanner #scanner start="true" [device]="selectedDevice"></zxing-scanner>`
For selecting a Device I subscribed to the camerasFound:
`this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {
            this.hasCameras = true;

            console.log('Devices: ', devices);
            this.selectedDevice= devices[0];

        });`

![screenshot_2019-02-06-07-56-29-377_at apro](https://user-images.githubusercontent.com/42172207/52325350-00d94780-29e5-11e9-9be3-4e4518d1c949.png)

**Comment by odahcam** [comment]
What happens if you hit the play?

**Comment by odahcam** [comment]
Related: #155

**Comment by pilz97** [comment]
nothing happens :( 
There is also no popup which asks for the permission.. could this be the reason?

**Comment by odahcam** [comment]
The scanner can’t play anything from stream without permission to access it, so I'd say yes. Can you make a test by running `navigator.mediaDevices.getUserMedia({ video: true })` to see what happens?

**Comment by thanhphuocdang** [comment]
Try adding the cordova-plugin-camera,
If it does not work, try phonegap-plugin-barcodescanner
Then check your android xml to see  permision

**Comment by odahcam** [comment]
It would be nice to add to documentation in case it's the case, hehe.

**Comment by pca1987** [comment]
@thanhphuocdang if I go to my app information (android settings) I do se camera permission but it's always OFF once I do a fresh install. If it turn it on manually, camera works within the app, but the app never asks for permission after a fresh install. I do have cordova-plugin-camera plugin installed.

**Comment by thanhphuocdang** [comment]
The permission for the scanner on native application is belong to the Cordova Plugin.
Perhap you can make a yourself plugin and then upload on cordova library.
Then I also use it too, hehe Lol

**Comment by benbrownlol** [comment]
See https://github.com/zxing-js/ngx-scanner/issues/210 for fix if anyone else is having trouble with this.

**Comment by odahcam** [comment]
Thanks for pointing out @benbrownlol . I'll close this, anyone looking for a solution can take a look [here](https://github.com/zxing-js/ngx-scanner/issues/210#issuecomment-508488434).
