### ISSUE TITLE
WebApp does not ask for camera permission

### ISSUE THREAD

**Issue by Cruik** [zxing-js/ngx-scanner#169]
Hey,

i am trying to get the github angular demo working on my machine.
i am using angular 7.2.4.

The problem here is that it works all fine when i use my pc with firefox and browse to my website. Then they show me my available cameras, ask for the permissions and finally after granting permissions i can see the camera view.

but if i try to enter the website on my samsung galaxy s8 via the browser, the camera list shows me my available cameras, but when i select one its not asking for permission, so nothing is shown. :/

except for the angular version i didn´t change a thing, maybe the 7.2.4 is the problem?

**Desktop (please complete the following information):**
 - Browser :firefox

**Smartphone (please complete the following information):**
 - Device: samsung galaxy s8
 - OS: android 8
 - Browser chrome 
 - Version 72.0.3626.105

Am i missing anything here?

**Comment by odahcam** [comment]
The problem happens on Mobile Chrome?

**Comment by Cruik** [comment]
Exactly, also with the samsung internet browser

**Comment by Razgort** [comment]
Hello, same issue here

**Comment by Razgort** [comment]
Testing working on firefox android but not chrome

**Comment by odahcam** [comment]
That's **odd**, I'm using this in production and it's working fine here. Does this happens even with the demo?

**Comment by Razgort** [comment]
Demo is working ... I have only 12h left :(

**Comment by Razgort** [comment]
Which version is the demo using of your package ?

**Comment by Cruik** [comment]
i checked the demo out and pushed it to my site.
didn´t change anything and its still not working on chrome

**Comment by Razgort** [comment]
Ye my code is really the same as https://embed.plnkr.co/MN4riU/

**Comment by odahcam** [comment]
Take a look:

<details>
  <summary>Images</summary>
  
  ![screenshot_20190218-092406](https://user-images.githubusercontent.com/3942006/52951098-a1bdf000-335f-11e9-8fb6-b152d0374a18.png)

  ![screenshot_20190218-092338](https://user-images.githubusercontent.com/3942006/52951103-a2ef1d00-335f-11e9-8b31-29d967d5d4ff.png)

  ![screenshot_20190218-092313](https://user-images.githubusercontent.com/3942006/52951104-a4204a00-335f-11e9-8e1f-9cdb8ed6c243.png)

</details>

I'm on Android 9 with Chrome 72 and everything is ok so maybe could it be a Samsung related issue?

**Comment by Cruik** [comment]
well i guess i solved it. after i enabled 'Https only' for my webapp it worked as expected

**Comment by Razgort** [comment]
not for me =(

**Comment by odahcam** [comment]
Well any permission API needs to be run under HTTPS in order to work.

**Comment by viniferlima** [comment]
> well i guess i solved it. after i enabled 'Https only' for my webapp it worked as expected.
> 
> Thanks for your help! :)

How is it done? How do I enable 'https only' for my webapp? I am having the same trouble as the author of the question.

**Comment by Cruik** [comment]
> 

since my webapp was hosted in azure i just enabled HTTPS only in the App Service -> TLS/SSL settings -> and just enable it there
