### ISSUE TITLE
Reading qr code from a file input

### ISSUE THREAD

**Issue by benceHornyak** [zxing-js/ngx-scanner#171]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would like read qr code from an input (file type).
After choosing a file from the input the scanner should be able to parse the given qr code 

**Additional context**
I saw this: https://github.com/zxing-js/library#scanning-from-image and I was wondering if it is possible using this scanner.

**Comment by odahcam** [comment]
This scanner uses the one you saw, here we have only an Angular layer so @zxing/library is already installed if you installed @zxing/ngx-scanner. Given that, you can just use what you saw. 🙂
