### ISSUE TITLE
Missing callback on error in decodeFromInputVideoDevice

### ISSUE THREAD

**Issue by DrorBuhnik** [zxing-js/ngx-scanner#175]
Where there is an issue inside `decodeFromInputVideoDevice`, the error is not propagate up via scanFailure observable, this leave the library user in undefined state without any option to recover
https://github.com/zxing-js/ngx-scanner/blob/master/src/app/modules/zxing-scanner/browser-code-reader.ts#L143-L146

This came up when testing on iPad which (for some reason known only to apple) doesn't like to use the back ("environment") camera

**To Reproduce**
1. Find the environment camera (via this.scanner.camerasFound.subscribe)
2. Instruct ngx-scanner to use the environment camera (e.g. if label contains 'back' string)
3. Get an error in console:
`OverconstrainedError { message: "Invalid constraint", constraint: "deviceId" }`
4. No other feedback, no knowledge is passed to library user in any callback/observables

**Expected behavior**
The library user should receive an error via scanFailure observable

**Smartphone**
Device: Apple iPad Mini 2
OS: 12.1.4
Browser: Safari
Version: 12

**Comment by odahcam** [comment]
I can confirm this behavior once I experienced it lots of times in recently. I'm sorry I couldn't fix it yet, I'm pretty out of time.

**Comment by DrorBuhnik** [comment]
Right now I have a manual workaround that takes this code
https://github.com/zxing-js/ngx-scanner/blob/8ff38b6c55957c40623d1b92f5a324dbb2991c76/src/app/modules/zxing-scanner/browser-code-reader.ts#L143-L146
and add
```javascript
            catch (err) {
                /* handle the error, or not */
                console.error(err);
                callbackFn();
            }
```

Is that a sufficient fix for you?
