### ISSUE TITLE
Set zoom/scale

### ISSUE THREAD

**Issue by kimdah3** [zxing-js/ngx-scanner#176]
**Is your feature request related to a problem? Please describe.**
Trying to make the scanning more effective, I think by increasing the scale/zoom of the camera could make it better. I'm scanning really small data matrix codes which makes them hard to scan.

**Describe the solution you'd like**
Ideally an attribute to set it up on the component. 
Is it possible to fork and change a setting of some sort?

**Comment by zhanglongchina** [comment]
i need the feature too

**Comment by odahcam** [comment]
> Is it possible to fork and change a setting of some sort?

Teorically you can develop something over the existing code, but zooming without camera support isn't that simple:

- It depends on the screen pixel density of the device for next items.
- It depends on the scanner visible area so when the user zooms the image the scanner only tries to read user-visible area, so you need to crop and calculate area based on the component's visibility to make sense.
- It depends on positioning the video correctly on the screen, considering portrait and landscape.

Cropping the video right is kinda hard. You can always try some native devices API like the torch (flashlight) API we use. Keep in mind that a PR will be welcome.

**Comment by Cristuker** [comment]
I also need this feature. Someone have idea why i start to help this? I never develop using camera api.
