### ISSUE TITLE
Devices have status "without permission" when tested in a local environment

### ISSUE THREAD

**Issue by jeremysangroni** [zxing-js/ngx-scanner#178]
I tested the application through a Wi-Fi network from my laptop to my phone, everything is perfect, but running the application with the ip address of my laptop on the phone throws me that the devices do not have permissions, this is because the domain is not valid to be in a local environment?

**Comment by thanhphuocdang** [comment]
Too less information.
I guess that is an error happens with your SSL,
Try to connect your phone to laptop by cable line and run with localhost to fix that.
Or using GAE if you would like to test your app via the address with a secure certificate.

**Comment by odahcam** [comment]
There's no way to point a problem here, it could be one of the permissions layers, network, SSL, domain, device, etc., so I'm closing, sorry.
