### ISSUE TITLE
Autofocus doesn't work

### ISSUE THREAD

**Issue by andersonkoester** [zxing-js/ngx-scanner#179]
Hi guys, I'm trying to apply autofocus, but it doesn't work. 
`<zxing-scanner #scanner [device]="currentDevice" [autofocusEnabled]="true" (scanSuccess)="handleQrCodeResult($event)" [formats]="allowedFormats"></zxing-scanner>` 

Result:
`<video _ngcontent-c12="" autoplay="true" muted="true" playsinline="true" autofocus="true" style="object-fit: cover;"><p _ngcontent-c12=""> Your browser does not support this feature, please try to upgrade it. </p><p _ngcontent-c12=""> Seu navegador não suporta este recurso, por favor tente atualizá-lo. </p></video>`

![autofocus](https://user-images.githubusercontent.com/1521013/56379872-2655af00-61e7-11e9-9b6f-42231fb988de.png)

Tablet
 - Device: Samsung Tab E 9.6 Wifi T560
 - OS: Android 4.4.4
 - Browser Chrome 72.0.3626.105

**Comment by odahcam** [comment]
Autofocus is by default enabled. I can't see a reason on why it wouldn't work. Could you set up an example at StackBlitz?

**Comment by odahcam** [comment]
No follow up.
