### ISSUE TITLE
method to control time between scans

### ISSUE THREAD

**Issue by cnps** [zxing-js/ngx-scanner#183]
First of all, thanks for a super component.

I've created a method on the ZXingScannerComponent class to be able to control the time between scans, as 500 milliseconds were simply to fast for my use case.

I can imagine others could use this feature, so if you would like, I can submit a pull request. Otherwise it would be really nice if you could implement it, so I don't have to "hack it".

**Comment by odahcam** [comment]
I would gladly accept a PR that adds a new prop to the component where the user can control the `timeBetweenScans` value.
