### ISSUE TITLE
Since last update (1.5.0) can't import @zxing/library

### ISSUE THREAD

**Issue by mhosman** [zxing-js/ngx-scanner#184]
`import { BarcodeFormat } from '@zxing/library';`

> Can't find module '@zxing/library'.ts(2307)

Also it could be great to have access to the change log in GitHub (not updated since v1.2.1)

**Comment by odahcam** [comment]
Please be aware that `@zxing/library` is a peer dependency:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/3942006/58060377-912c3a00-7b47-11e9-9dcf-6a0f7212f5a0.png">

So you should always remember to install it (like `npm i @zxing/library`).
