### ISSUE TITLE
ZXingScannerComponent method not exist since updated to ver. 1.5.0

### ISSUE THREAD

**Issue by tsukune1106** [zxing-js/ngx-scanner#185]
After updated to version 1.5.0, some of the method are been said they are not exist in ZXingScannerComponent. It also said that the component could not find the module @zxing/library even though last version does not have this issue.

**Comment by cnps** [comment]
Same issues here.

**Comment by Noapte** [comment]
The same with my project, I had to downgrade to 1.3.0

**Comment by odahcam** [comment]
You can see that the class `ZXingScannerComponent` is found here: https://stackblitz.com/edit/zxing-ngx-scanner

Could you delete the package locker (`package-lock.json` or `yarn.lock`) and `node_modules` and try installing the packages again?

**Comment by jziggas** [comment]
same issue from fresh angular app

**Comment by odahcam** [comment]
Well, it wasn't like that before. I think it was a mistake letting `@zxing/library` become a peer dependency.
