### ISSUE TITLE
What happened with getDeviceById method?

### ISSUE THREAD

**Issue by franciscovelez** [zxing-js/ngx-scanner#187]
Hi there, 

I was using the 1.3.0 version and today I have updated it to 1.5.0. After that, I have found that the `getDeviceById` method from the `ZXingScannerComponent` class does not exists anymore. So my question is what happened with this method? Have you changed the name or removed it? If it has been removed, is there any other method to get the device ID?

I did my code following your plunker demo (https://embed.plnkr.co/MN4riU/) and it is something like this: 
```html
  <zxing-scanner #scanner start="true" [device]="selectedDevice"
                 (scanSuccess)="handleQrCodeResult($event)"
                 (scanError)="handleQrCodeResult($event, true)"
                 (camerasNotFound)="camerasNotFound($event)"
                 (camerasFound)="camerasFound($event)"
                 (permissionResponse)="permissionResponse($event)"></zxing-scanner>
```
```javascript
@Component({
  selector: 'app-qr-reader',
  templateUrl: './qr-reader.component.html',
  styleUrls: ['./qr-reader.component.scss']
})
export class QrReaderComponent implements OnInit {
  @ViewChild('scanner') scanner: ZXingScannerComponent;

  onDeviceSelectChange(selectedValue: string) {
      this.selectedDevice = this.scanner.getDeviceById(selectedValue);
  }

  [..]
```

Thanks for your help!

**Comment by ymallikreddy521** [comment]
same problem here. I used 1.3 version for now

**Comment by ingeJulianLasso** [comment]
I have the same problem here. I have used version 1.3 for now. I hope the team will fix it soon :)

**Comment by odahcam** [comment]
team: me (hey!) 😆 

Get device by ID is out, it was removed from 1.3 to 1.5. You can still filter devices by ID like this:

```TS
    this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {
      // selects the devices's back camera by default
      for (const device of devices) {
          if (device.id === myDeviceId) {
            return device;
          }
      }
    });
```

**Comment by franciscovelez** [comment]
Thank you for your answer, we will change our code accordingly. Just a tip: It would be wonderful if you publish a list of changes within the next releases, in that way we can figure out if there is something we should change.

Regards.

**Comment by odahcam** [comment]
Yes, my fault. It happens that I didn't remember that there was such changes, it was a long time since I coded this release. Looks like a lot more people is using this lib now so I gotta be careful.

**Comment by ingeJulianLasso** [comment]
Thank you very much for your reply. I based myself on an example that you published in plunker.

**Comment by ingeJulianLasso** [comment]
Thank you for answering. One last request regarding the library, could it be possible to update the demo example?
https://embed.plnkr.co/MN4riU/

**Comment by odahcam** [comment]
That Plunkr example is not maintained anymore, so for future updates, you should keep an eye at the StackBlitz one. Thanks.
