### ISSUE TITLE
Not display the camera facing back

### ISSUE THREAD

**Issue by raphaelramos** [zxing-js/ngx-scanner#188]
Hello. Congratulations to the developers for the amazing component.

Console displays error message "The `device` must be a valid MediaDeviceInfo or null". Can anyone tell me why?

And by selecting the back camera on the Android device, it does not display the "camera 0, facing back" image. Camera 1 displays.

Code was copied from
https://stackblitz.com/edit/zxing-ngx-scanner

**Comment by odahcam** [comment]
When did you copied that code?

**Comment by j-651** [comment]
I am experiencing the exact same issue as Raphael.  Used the StackBlitz example which errors to "The `device` must be a valid MediaDeviceInfo or null". I am unable to switch cameras.

Additionally, `this.scanner.changeDevice(device);` included in the StackBlitz to default to the device's rear camera  returns "Property `changeDevice` does not exist on type 'ZXingScannerComponent'."

The code I am referencing is currently on the StackBlitz in the `app.component.ts` file.  Any assitance would be greatly appreciated!

**Comment by raphaelramos** [comment]
> When did you copied that code?

4 days ago

**Comment by j-651** [comment]
> Additionally, `this.scanner.changeDevice(device);` included in the StackBlitz to default to the device's rear camera returns "Property `changeDevice` does not exist on type 'ZXingScannerComponent'."

As per [here](https://github.com/zxing-js/ngx-scanner/issues/26#issuecomment-496739966), I have been able to solve this issue by removing `this.scanner.changeDevice()` (which now prevents the console error) and replacing it with a `[(device)]="currentDevice"` implementation as is also already in the StackBlitz.  I am now able to properly change cameras.

**Comment by odahcam** [comment]
> Console displays error message "The device must be a valid MediaDeviceInfo or null". Can anyone tell me why?

It's just a bad implementation, where `currentDevice` from StackBlitz demo is `undefined` when it should be `null`. 

The StackBlitz demo is fixed now.

**Comment by odahcam** [comment]
This should be solved by now.
