### ISSUE TITLE
Camera does not stop on Safari and sometimes on Chrome

### ISSUE THREAD

**Issue by SergeyMell** [zxing-js/ngx-scanner#189]
**Describe the bug**
We were using scanner on one of our angular routes. After moving to another route camera sometimes remain working on Chrome and always on Safari

**To Reproduce**
1. Go to the example to reproduce
https://stackblitz.com/edit/angular-tyqjz9?file=src%2Fapp%2Fscanner%2Fscanner.component.ts
2. Just navigate between `home` and `scanner` routes via links in the bottom.

**Expected behavior**
Camera should be turned off after scanner component has been destroyed.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.4
 - Browser [Safari 12.1]

**Comment by odahcam** [comment]
Your StackBlitz demo is not working:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3942006/61346244-56d0d780-a82e-11e9-937a-2d18ce23aab0.png">

The `core-js` dependency never gets installed.

**Comment by SergeyMell** [comment]
@odahcam, I see. I'll fix it today.

**Comment by odahcam** [comment]
I could reproduce it with the current demo (v2.0.0), but the StackBlitz demo would be handful anyway. Thanks.

**Comment by SergeyMell** [comment]
StackBlitz demo is fixed for now

**Comment by odahcam** [comment]
Looks like the device is not released when the component gets destroyed **before** finish fetching the device. 

Probably the Promise stills alive and the `then` generated code gets called even after the component is destroyed, keeping the device instead of releasing it.

To fix that we could check for some control variable before proceeding and if we verify the component was destroyed, the code should clean the device reference releasing it.

**Comment by visurel** [comment]
^bump - Any update on this?

**Comment by natanaelfiorilla** [comment]
Any resolution to this problem? I have the same problem, the scanner reads a string and a navigation is executed but the camera stays on, even when I call scanner reset .

**Comment by Grasscropper** [comment]
Hey guys, any progress on this front? i tried a bunch of things to work around this to no avail...

**Comment by Grasscropper** [comment]
Okay i found one not so ideal workaround, but is considerably a better user experience than what was happening (seeing the webcam light on and  showing recording on the tab). It involves blocking for 2000ms route changes or any other events that causes the component to be destroyed while the scanner is just initializing. This gives it enough time to fetch the device (camera) completely as this issue only occurs (chrome) when you destroy the component in that time frame.

**Comment by alexthelion** [comment]
Hi, Any resolution to this problem?

**Comment by Mereo4** [comment]
The problem is still present (Windows 11 23H2 x64, Chrome 121.0.6167.185 & Firefox 122.0.1).
