### ISSUE TITLE
Back camera not being used as default

### ISSUE THREAD

**Issue by gregwm** [zxing-js/ngx-scanner#191]
**Describe the bug**
Back camera not being selected by default on Samsung Galaxy S9.

**To Reproduce**
https://zxing-ngx-scanner.stackblitz.io

**Expected behavior**
Switching cameras works (most the time), but it appears something is setting the camera after `_selectBackfaceCamera` is called.

**Smartphone (please complete the following information):**
 - Device: Samsung S9 Galaxy
 - OS: Android 8.0.0
 - Browser: Chrome

**Comment by odahcam** [comment]
> Back camera not being used as default

This is not a expected behavior for this lib, it just opens the first available camera.

**Comment by mhosman** [comment]
Hey @odahcam how about this code in the example?

```
for (const device of devices) {
          if (/back|rear|environment/gi.test(device.label)) {
            this.currentDevice = device;
            break;
          }
        }
```

It should be get the back camera by default but is not working (worked in the past).

**Comment by odahcam** [comment]
As you said, that's an [not-working] example, it is not the intended behavior for the component [yet]. That's something I'm working on, expect it in near future. Thanks for the patience.

**Comment by mhosman** [comment]
I did not know it did not work. It could be great to get that feature. Thank you very much for your response!!

**Comment by odahcam** [comment]
You're welcome, I'll always do my best to answer good.

**Comment by Vitaly1025** [comment]
HI, can you describe how i can make select  my camera default?

**Comment by odahcam** [comment]
Please open a new issue.
