### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by odahcam** [zxing-js/ngx-scanner#193]
**Describe the bug**

This used to happen after a loon time and amout of failed scan attempts, but after upgrading RxJS it happens right after changing the device and the first `scanFailure` is fired. After that `RangeError`, no scan is done and the stream remains dead-like.

**To Reproduce**
1. Open the demo.
2. Wait.
3. See error

or in certain RxJS versions it may:

1. Open the demo. 
2. See the error. 
3. Also happens when changing devices.

**Expected behavior**
Not to exceed any call stack.

**Screenshots**

![image](https://user-images.githubusercontent.com/3942006/58710769-76519500-8393-11e9-86dd-e6815660833a.png)

**Desktop (please complete the following information):**

 - Device: desktop
 - OS: Windows 10
 - Browser: Chrome - 74.0.3729.169 64 bits
 - Version: development 1.6

**Additional context**

**Comment by odahcam** [comment]
Also happens on macOS.

**Comment by aeslinger0** [comment]
@odahcam, I'm still seeing this in the StackBlitz. Could this be updated?

**Comment by odahcam** [comment]
Done.

**Comment by aeslinger0** [comment]
Hmm, the error is gone, but I can't get it to scan. The demo link works for me, but not the StackBlitz link. What could be different?

**Comment by odahcam** [comment]
Yes, this code is all asynchronous and has some problems, it happens that when I fix something an error explodes somewhere else and everytime I have to rewrite a lot of code to make it work again. So that makes the situation a good one for new bugs to born. I'm working on a fix for this.
