### ISSUE TITLE
scanSuccess event not fired

### ISSUE THREAD

**Issue by bassManAlex** [zxing-js/ngx-scanner#195]
**Describe the bug**
The scanSuccess event is not fired

**To Reproduce**
1. Go to https://stackblitz.com/edit/zxing-ngx-scanner
2. Try to scan a barcode

**Expected behavior**
scanSuccess event is fired.

**Desktop:**
 - OS: Windows 10 
 - Browser Chrome 
 - Version 74.0.3729.169

**Smartphone:**
 - Device: Samsung Galaxy S4
 - OS: Android 8
 - Browser Chrome
- Version 74.0.3729.157

**Comment by Kerbel** [comment]
+1

**Comment by odahcam** [comment]
Please refer to #193. It's an odd RxJS bug that happens after certain version.
