### ISSUE TITLE
Property 'resetCodeReader' does not exist on type

### ISSUE THREAD

**Issue by ymallikreddy521** [zxing-js/ngx-scanner#196]
After upgrade to latest version, I am getting below exception.

Property 'resetCodeReader' does not exist on type

Is this property removed.

**Comment by odahcam** [comment]
Probably removed long ago, perhaps `scanner.codeReader.reset()` may solve your problem. Let me know if you have any more issue.

**Comment by ymallikreddy521** [comment]
Thank you. I will give a try.
