### ISSUE TITLE
Error TS1039: Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by GorganGabi** [zxing-js/ngx-scanner#202]
ERROR in node_modules/@zxing/library/esm5/browser/VideoInputDevice.d.ts(10,21): error TS1039: Initializers are not allowed in ambient contexts.

*Steps to reproduce the behavior:*
ng serve --watch

 Angular CLI version: ~6.0.0
Typescript version: ^2.7.2
@zxing/ngx-scanner: ^1.7.1

Maybe it's something related to typescript/angular version?

**Comment by odahcam** [comment]
Probably is, the 1.7 version is built with TS 3.x and Angular 7, please try using 1.3.

**Comment by GorganGabi** [comment]
Updated to Angular 8 and Typescript 3.4 and the 1.7 version works fine.

Thank you!

**Comment by odahcam** [comment]
Nice to know that, I did not upgraded the lib itself to Angular 8, good to know they're compatible.
