### ISSUE TITLE
Angular 8: warning messages

### ISSUE THREAD

**Issue by ymallikreddy521** [zxing-js/ngx-scanner#204]
Hi there,

I am getting below warning messages.

 Permissions not set yet, waiting for them to be set to apply device change.
Setting is the same device is not allowed
Trying yo play video that is already playing.

Here is the HTML

```html
   <zxing-scanner  #scanner  [autofocusEnabled]="true" [autostart]="true" [enable]="true"  [device]="currentDevice"
          (scanComplete)="handleScanComplete($event)" [formats]="allowedFormats"
          [tryHarder]="true"></zxing-scanner>
```

Here is TS

```TS
 private initCamera(): void {
    this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {
      this.hasDevices = true;
      this.availableDevices = devices;
      this.currentDevice = null;
      if (this.availableDevices.length > 1) {
        const defaultCamera = this.availableDevices.filter(e => e.label.toLocaleLowerCase().indexOf('back') > -1);
        if (defaultCamera !== null && defaultCamera !== undefined) {
          this.currentDevice = defaultCamera[0];
        } else {
           this.currentDevice = this.availableDevices[0];
        }
      } else {
        this.currentDevice = this.availableDevices[0];
      }
    });
  }
  stopScan(): void {
    this.currentDevice = null;
    this.scanner.codeReader.reset();
    this.onhideCamScanner.emit(this.camScanTrackingList);
  }
```

**EDIT:** added syntax highlighting.

**Comment by odahcam** [comment]
Thanks for reporting, this is not Angular 8 specific. 

Some of these warnings are just telling you that things that shouldn't be happening are happening, so you can work on your code to disappear with them. The `Trying yo play video that is already playing.` is a bad implementation inside the code reader, which will be solved in the future with #177 and #175.

**Comment by ymallikreddy521** [comment]
which version of it solved the code reader issue. I am using 1.7.1

**Comment by odahcam** [comment]
Follow both #175 and #177 for updates, thanks.
