### ISSUE TITLE
Angular 7 unable to  build 

### ISSUE THREAD

**Issue by dejooo13** [zxing-js/ngx-scanner#206]
Hello,
i have a problem when building up project, we have 3 env dev, qa and prod, on dev and prod it all goes well and on qa i get:

> ERROR in : Can't bind to 'scannerEnabled' since it isn't a known property of 'zxing-scanner'.
1. If 'zxing-scanner' is an Angular component and it has 'scannerEnabled' input, then verify that it is part of this module.
2. If 'zxing-scanner' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          </div>
        </div>
        <zxing-scanner #scanner [ERROR ->][scannerEnabled]="scannerEnabled" [device]="currentDevice" (scanSuccess)="handleQrCodeResult($event)"")
src/app/components/shop-panel/qr-code/qr-code.component.ts(45,28): error TS2339: Property 'changeDevice' does not exist on type 'ZXingScannerComponent'.

**Comment by odahcam** [comment]
Hello, are you importing ZXingScannerModule in the module your component that uses it is declared?

**Comment by dejooo13** [comment]
Yes, it's all fine and all worked as it should, just out of sudden, before few days started to bug. I think it's maybe due to some changes in plugin because i didn't touch code and even that component (it was working) and now i can't build up project.

`<zxing-scanner #scanner [device]="currentDevice" (scanSuccess)="handleQrCodeResult($event)" [formats]="['QR_CODE', 'EAN_13', 'CODE_128', 'DATA_MATRIX']"></zxing-scanner>`


`
  @ViewChild('scanner')
  scanner: ZXingScannerComponent;

  hasDevices: boolean;
  hasPermission: boolean;
  qrResult: Result;
  scannerEnabled: boolean;

  currentDevice: MediaDeviceInfo;

    this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {
      this.hasDevices = true;
      this.currentDevice = devices[0];

      for (const device of devices) {
          if (/back|rear|environment/gi.test(device.label)) {
              this.currentDevice = device;
              break;
          }
      }
      this.scannerEnabled = true;
    });`

**Comment by dejooo13** [comment]
I forgot to write, this code above throws me this error: 

> ArgumentException: The `device` must be a valid MediaDeviceInfo or null.

**Comment by odahcam** [comment]
That's fine, just change it like that:

```diff
-  currentDevice: MediaDeviceInfo;
+  currentDevice: MediaDeviceInfo = null;
```

You need to explicit say you defining no device, otherwise futher device settings validation could fail.

**Comment by dejooo13** [comment]
@odahcam that's it. Thanks for your help.

**Comment by odahcam** [comment]
You're very welcome.
