### ISSUE TITLE
zxing-scanner not working in Cordova Web View

### ISSUE THREAD

**Issue by Abul4u** [zxing-js/ngx-scanner#210]
I am using zxing-scanner in **Angular Web App** and that Web App will load in **Cordova App's Web View**.
Scanner working fine in Chrome(Desktop/Tablet/Mobile) but its not working in Cordova App's Web View.

Note:
Camera permission already granted to the Cordova App.

zxing-scanner askForPermission TypeError:
navigator.mediaDevices.getUserMedia is not a function(...)

@zxing/ngx-scanner I was not able to define if I have permission for camera or not. TypeError: navigator.mediaDevices.getUserMedia is not a function(...)

![zxingWeb APP in Cordova APP WebView](https://user-images.githubusercontent.com/9959021/59846181-b088d380-934e-11e9-9d6d-4dfb91bb7ebb.png)

**Comment by benbrownlol** [comment]
You don't have your permissions properly set. Do the following:

1. Install https://www.npmjs.com/package/cordova-plugin-android-permissions
2. Add `xmlns:android="http://schemas.android.com/apk/res/android"` to the `<widget>` tag in your config.xml
3. Add the following snippet inside your `<platform name="android">` tag in your config.xml:
```
<config-file parent="/manifest" target="AndroidManifest.xml">
    <uses-permission android:name="android.permission.CAMERA" />
</config-file>
```
4. Add the following code to the location that you wish to access the camera inside your app:
```
const permissions = window.cordova.plugins.permissions;

permissions.checkPermission('android.permission.CAMERA', (status) => {
  if (!status.hasPermission) {
    permissions.requestPermission('android.permission.CAMERA', (request) => {
      console.log('Success requesting CAMERA permission:', request);
    }, (error) => {
      console.log('Failed to set permission:', error);
    });
  }
});
```

**Comment by odahcam** [comment]
Thanks @benbrownlol.

**Comment by wstrik** [comment]
Anybody got to work on iOS?

**Comment by odahcam** [comment]
I'm not sure with Cordova, but inside a PWA it's impossible until now.

**Comment by wstrik** [comment]
Hi Obahcam, thx for your reply.
PWA isn't support by iOS enough indeed, although it does work fine in a browser. But it is why I'm trying with Cordova.
I'll open a seperate issue for it.
