### ISSUE TITLE
Copied code from wiki doesn't work for me

### ISSUE THREAD

**Issue by JuSteph93** [zxing-js/ngx-scanner#211]
HI, I've just discovered this amazing tool that could be useful for my web app but i copy/paste your demo code and the scanner can't read the code. I tested on the demo my barcode and there works but in my local don't. What did I do wrong? Here's the code

```TS
import { Component, ViewChild, OnInit } from '@angular/core';
import { ZXingScannerComponent } from '@zxing/ngx-scanner';

import { Result } from '@zxing/library';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit{


  hasCameras = false;
  hasPermission: boolean;

  availableDevices: MediaDeviceInfo[];
  selectedDevice: MediaDeviceInfo;

  @ViewChild('scanner')
  scanner: ZXingScannerComponent;

  ngOnInit(): void {
    this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {
      this.hasCameras = true;

      console.log('Devices: ', devices);
      this.availableDevices = devices;
      this.selectedDevice = this.availableDevices[0];

  });

  this.scanner.camerasNotFound.subscribe((devices: MediaDeviceInfo[]) => {
      console.error('An error has occurred when trying to enumerate your video-stream-enabled devices.');
  });

  this.scanner.permissionResponse.subscribe((answer: boolean) => {
    this.hasPermission = answer;
  });

  }
  title = 'BarcodeScanner';
  barcode = "";

  showBarcode(resultString: string) {
      console.log('Result: ', resultString);
      this.barcode = resultString;
  }
}
```

----

**EDIT by @odahcam:** added proper code highlighting.

**Comment by odahcam** [comment]
Could you link the Wiki page?

**Comment by JuSteph93** [comment]
First of all, thank you for formatting my code I appreciate that.

Here the link to the wiki 

https://github.com/zxing-js/ngx-scanner/wiki

**Comment by odahcam** [comment]
You're welcome. About the link, I mean the wiki page where you got the code.

**Comment by JuSteph93** [comment]
It's there, in the "Getting started" section

**Comment by JuSteph93** [comment]
Sorry, I remember that it was on the wiki page, but it is here https://embed.plnkr.co/MN4riU/

**Comment by odahcam** [comment]
All right, please, take a look in the [example](https://zxing-ngx-scanner.stackblitz.io) available on [StackBlitz](https://stackblitz.com/edit/zxing-ngx-scanner). It will solve your problems.
