### ISSUE TITLE
error when trying to change device

### ISSUE THREAD

**Issue by WEBhicham** [zxing-js/ngx-scanner#212]
**Describe the bug**
whenever I try to set a new device it resets back to the first available device, and I get a lot of erros
**To Reproduce**
see code

**Expected behavior**
to just switch device without any errors or resetting back

**Screenshots**
![HFBHjx5Iiy](https://user-images.githubusercontent.com/27362642/60084006-05559100-9737-11e9-8334-c3d5f30c66fb.png)
![msedge_5CVC728h7t](https://user-images.githubusercontent.com/27362642/60084007-05559100-9737-11e9-9194-0fcec356b197.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 pro]
 - Browser [Firefox and Edge canary]
 - Version [FF67.0.4, edge 77]

**Additional context**
I am just trying to have a button switch devices and save the last used one for the next use.
here is my code: https://gist.github.com/WEBhicham/5e9f7931ec461e1fbae67b100cd5f723
I am on version 1.7.1.

**Comment by odahcam** [comment]
Well, this has nothing to do with the scanner, sorry.

For solving this you could try to move some of your code from `ngOnInit` to `ngAfterViewInit` and, mainly, avoid setting values to the component manually via TS, just let the template parser handle what it can.

Also, I did a switch button myself, maybe you could get a cleaner code if you use `shift` and `unshift` methods on the available devices array and, by treating it as a FIFO list, you could get rid of index comparisons and then your code would just get the first available device, then put the one it was using as the last element of the list and so on.

**Comment by FelixStumvoll** [comment]
The same error exists in the scanner-demo,
could you please update the demo i have got the same issue and i have no idea how to fix it since there is no working version where i could check how it is done correctly.
