### ISSUE TITLE
device becomes null

### ISSUE THREAD

**Issue by kgatan** [zxing-js/ngx-scanner#215]
**Describe the bug**
Setting new device causes this.device to become null

**To Reproduce**
Toggle devices
https://angular-9kjspu.stackblitz.io

**Expected behavior**
scanner.device should always reflect active device

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version Latest

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 9+
 - OS: Android 9
 - Browser Chrome
 - Version Latest

**Additional context**
https://angular-9kjspu.stackblitz.io
https://stackblitz.com/edit/angular-9kjspu

**Comment by odahcam** [comment]
That's because this is not the correct way to keep tracking of the current device. You should just bind to the component `device` attribute instead.

**Comment by kgatan** [comment]
Sorry, made an error in above report. Should of course be this.scanner.device not this device.
