### ISSUE TITLE
Cameras not found in mobile browser

### ISSUE THREAD

**Issue by VinothMathi** [zxing-js/ngx-scanner#216]
I have used zxing scanner with angular 7 to scan qr codes. It is working with the desktop browser. But when I tried with the mobile browser both android and iOS, I am getting cameras not found event. It is not even asking for permission. Please help me with this.

**Comment by odahcam** [comment]
Please provide the requested information in the issue creation so we can help.

**Comment by odahcam** [comment]
No follow up.

**Comment by leonardolondono** [comment]
I have the same issue, I put on the my web app
<zxing-scanner [formats]="['QR_CODE', 'EAN_13', 'CODE_128', 'DATA_MATRIX']" 
 (scanSuccess)="scanSuccessHandler($event)" class="col-8 col-sm-6 mx-auto"></zxing-scanner>

But when I use my mobile, nothing happends

**Comment by odahcam** [comment]
You gotta provide debugging information or nothing will be done, I can't guess the problem, sorry. Please open a new issue with the minimum required information if you still need help. Thanks.
