### ISSUE TITLE
Rear camera in portrait mode doesn't works correctly

### ISSUE THREAD

**Issue by yerayrm** [zxing-js/ngx-scanner#217]
**Describe the bug**
When I tried to capture using the back camera in portrait mode, this camera doesn't rotate correctly in windows 10 tablets like surface. 

**To Reproduce**
1. Go to the sample page https://zxing-js.github.io/ngx-scanner/
2. Click on spinner to select back camera
3. See error

**Expected behavior**
I expect that the camera preview is oriented correctly

**Screenshots**
https://imgur.com/9zCndKw

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75
 - Device: surface

**Comment by odahcam** [comment]
Camera works fine, I think this is more like a feature request, because we did not coded anything to recognize device orientation for rotating the image.
