### ISSUE TITLE
Can't get user media, this isnt supported

### ISSUE THREAD

**Issue by ramdanegie** [zxing-js/ngx-scanner#218]
I found error Can't get user media, this isnt supported.  In domain or other device  cant detected camera , but in my localhost project nothing bugs. please help ! thanks
![image](https://user-images.githubusercontent.com/38318462/60581491-835e0b80-9db9-11e9-812d-0cf9faac8714.png)

**Comment by ramdanegie** [comment]
or my domain must secure (https)
?

**Comment by ManiyanKarthi** [comment]
Hi ramdanegie, 
 
https://github.com/zxing-js/ngx-scanner/issues/133


Is this similar issue  ,if you find the solution comment below

**Comment by odahcam** [comment]
Hello!

You **need** SSL to access the user devices or explicit server the application from **localhost**. I can see in your print, you're under a IP address, which requires SSL.

**Comment by ramdanegie** [comment]
Thank u so much is very helfull 😊😊

**Comment by ManiyanKarthi** [comment]
Hi Luiz Machado odahcam, 
              If My site is secured, able to access the camera but barcode is not scanning , is the below code is correct. Do you have any videos about how the code works.

<zxing-scanner  (scanSuccess)="onCodeResult($event)" ></zxing-scanner>


            onCodeResult(resultString: string) {
		 alert("onCodeResult"+resultString)
		}

**Comment by odahcam** [comment]
@ramdanegie you're welcome. :)

@ManiyanKarthi can you open a new issue and detail a bit more what's happening? Like is the component showing any camera images, or it's doing nothing at all...

I'm closing this one as the original issue is solved.
