### ISSUE TITLE
PDF417 is not getting scanned

### ISSUE THREAD

**Issue by hemchudgar** [zxing-js/ngx-scanner#219]
Adding 'PDF_417' in formats doesn't scan the pdf417 barcode

**Comment by odahcam** [comment]
Hello. PDF 417 is not supported yet. Please check https://github.com/zxing-js/library/issues/59

**Comment by adam-nagle-customreg** [comment]
> Hello. PDF 417 is not supported yet. Please check [zxing-js/library#59](https://github.com/zxing-js/library/issues/59)

It looks like its supported now.  March 4 -- "Good news everyone. Mission accomplished."

**Comment by odahcam** [comment]
Yep, it is not perfect, but is now supported!
