### ISSUE TITLE
VideoInputDevice.d.ts: error : Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by lobnazakaria93** [zxing-js/ngx-scanner#220]
scanner work fine but it throw an error that from it i cannot build my application

i use angular 6  

ERROR in node_modules/@zxing/library/esm5/browser/VideoInputDevice.d.ts(10,21): error TS1039: Initializers are not allowed in ambient contexts.

![Capture](https://user-images.githubusercontent.com/52527565/60970484-6201a000-a322-11e9-9bab-1ddd934b9bc2.PNG)
.

**Comment by mobouafas** [comment]
I have the same error and i'm using angular 6 too with typescript 2.9.2
I read here https://github.com/valor-software/ngx-bootstrap/issues/5220 that a solution is to upgrade to a more recent version (something that I can't do for now.. ).

**Comment by odahcam** [comment]
What's the version of the scanner you're using?

**Comment by ninonextix** [comment]
I have also experienced the same problem. 
![image](https://user-images.githubusercontent.com/45283709/61204135-0ae33d00-a71f-11e9-9f2d-ec45657d4717.png)
![image](https://user-images.githubusercontent.com/45283709/61204155-13d40e80-a71f-11e9-9d1d-960e3235096a.png)

I think it might be related to the versions I am using. I hope this one gets solved.

**Comment by odahcam** [comment]
Try using a less recent version of the scanner. The latest version was not tested with Angular 6, but only v7 and v8.
