### ISSUE TITLE
Error using on All Android devices: "Can't get user media, this is not supported"

### ISSUE THREAD

**Issue by chelinho139** [zxing-js/ngx-scanner#226]
**"Can't get user media, this is not supported."
Pc version works fine, when we try on android phones we get an error that says:

@zxing/ngx-scanner Can't get user media, this is not supported.

**Smartphone (please complete the following information):**
 - Device: [e.g. Moto Z3, Moto X Gen 1]
 - OS: [Android different versons]
 - Browser [chrome, brave browser]

**Comment by chelinho139** [comment]
It was a matter that it needed SSL. 
Solved

**Comment by odahcam** [comment]
Thanks for the feedback. I labelled this issue so other users can easily find it.
