### ISSUE TITLE
Stackblitz Demo not working

### ISSUE THREAD

**Issue by Reda1000** [zxing-js/ngx-scanner#227]
**Describe the bug**
Stackblitz Demo not working / loading. But Stackblitz available in general.

**To Reproduce**
1. Go to ngx-scanner Readme.md
2. Click on Stackblitz-Demo under Demo section
3. Wait for page to load
4. Page will load forever - Logs indicate Promise rejection handling issue

**Expected behavior**
Stackblitz Demo version to show so that I figure out how to use ngx-scanner in my Angular project or verify correct include of ngx-scanner.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/14124903/61946538-25c97300-afa3-11e9-97e7-65a14cc15f91.png)

**Desktop (please complete the following information):**
 - OS: 
![grafik](https://user-images.githubusercontent.com/14124903/61946649-750fa380-afa3-11e9-8853-45b338d3a562.png)

 - Browser 
![grafik](https://user-images.githubusercontent.com/14124903/61946669-7fca3880-afa3-11e9-9b2c-09d1d33719ee.png)

 - Version Current Master-Branch

**Comment by odahcam** [comment]
![image](https://user-images.githubusercontent.com/3942006/61987822-eecd7e80-afef-11e9-806f-2e6ccbe44794.png)

I think StackBlitz may be with some weird problem. I downloaded and fixed the application and it stills not running. 🤔

**Comment by odahcam** [comment]
The repository project, in case anyone has wanna take a look: https://github.com/odahcam/ngx-scanner-stackblitz-demo

**Comment by Reda1000** [comment]
Thanks for the link to look at - i just did.

I just found the issue in angular.json. Some parts of the path for polyfills.ts etc. were duplicated.
![grafik](https://user-images.githubusercontent.com/14124903/61992571-7fdc3e00-b060-11e9-85be-32c7fdd40aad.png)
In picture you can see on the far right in browser logs the including path for polyfills ist something like '~/projects/ngx-scanner-demo/projects/ngx-scanner-demo/src' - i removed the "projects/ngx-scanner-demo/" one time.

I will now prepare a pull request once I got to know stackblitzs github integration.

**Comment by Reda1000** [comment]
Unfortunately stackblitz integration is kinda weird - Had to clone in github and then copy and paste successful changes from stackblitz to github project manually.

Created Pull request https://github.com/odahcam/ngx-scanner-stackblitz-demo/pull/1

Waiting for @odahcam approval. Afterwards issues should be closable.

**Comment by mplawley** [comment]
If I first go to the Stackblitz edit page:

`https://stackblitz.com/edit/zxing-ngx-scanner?file=projects%2Fzxing-scanner-demo` 

Then install the missing packages (`hammerjs`, `tslib`, `@angular/service-worker`), then the Stackblitz demo works.

**Comment by odahcam** [comment]
Thanks for the report @mplawley , the problem we had was that SB wasn't showing anything and when showing packages to install, it would never finish installing. It have been fixed now, thanks again.
