### ISSUE TITLE
In Angular 8 barcode scanner not working error TS2339: Property 'getDeviceById' does not exist on type 'ZXingScannerComponent'.

### ISSUE THREAD

**Issue by praveen-routhu** [zxing-js/ngx-scanner#231]
'import { Component, OnInit, ViewChild, Output, EventEmitter, Input, VERSION } from '@angular/core';
import { ZXingScannerComponent } from '@zxing/ngx-scanner';
import { Result } from '@zxing/library';

@Component({
  selector: 'mes-barcode-scanner',
  templateUrl: './mes-barcode-scanner.component.html',
  styleUrls: ['./mes-barcode-scanner.component.css']
})

export class MesBarcodeScannerComponent implements OnInit {

  @ViewChild('scanner', {static:true})
  scanner: ZXingScannerComponent;
  hasDevices: boolean;
  hasPermission: boolean;
  qrResult: any;
  availableDevices: MediaDeviceInfo[];
  currentDevice: any;
  //supportedFormat: any;
  //isScanEnable: boolean = false;
  popupVisible: boolean = false;
  searchName: string;

  @Input('withIcon') withIcon: boolean;
  @Output() qrResultString = new EventEmitter<any>();

  constructor() { }
  ngOnInit() {
    
        this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {
          this.hasDevices = true;
          this.availableDevices = devices;
          //console.log(this.availableDevices);
          
          // selects the devices's back camera by default
          // for (const device of devices) {
          //     if (/back|rear|environment/gi.test(device.label)) {
          //         this.scanner.changeDevice(device);
          //         this.currentDevice = device;
          //         break;
          //     }
          // }
        });
    
         this.scanner.camerasNotFound.subscribe(() => this.hasDevices = false);
         this.scanner.scanComplete.subscribe((result: any) => this.qrResult = result);
        this.scanner.permissionResponse.subscribe((perm: boolean) => this.hasPermission = perm);
 }
 closeOnOutsideClick() {
  this.popupVisible = false;
  this.currentDevice = this.scanner.getDeviceById('');
  //return e.target === document.getElementById("someElement");
 }  
  displayCameras(cameras: MediaDeviceInfo[]) {
    console.debug('Devices: ', cameras);
    this.availableDevices = cameras;
  }
  
  scanCode(){
    //this.isScanEnable = true;
    this.popupVisible = true;
    // for (const device of this.availableDevices) {
    //   if (/back|rear|environment/gi.test(device.label)) {
    //       this.scanner.changeDevice(device);
    //       this.currentDevice = device;
    //       break;
    //   }
 // }
    this.currentDevice = this.scanner.getDeviceById(this.availableDevices[0].deviceId);
  }

  handleQrCodeResult(resultString: string) {
    this.searchName = resultString;
    this.qrResultString.emit(this.searchName);
    if(this.qrResultString){
      this.closingScannerPopup();
    }
  }

  // onDeviceSelectChange(selectedValue: string) {
  //   console.debug('Selection changed: ', selectedValue);
  //   this.currentDevice = this.scanner.getDeviceById(selectedValue);
  // }

  closingScannerPopup() {
    this.popupVisible = false;
    this.currentDevice = this.scanner.getDeviceById('');
  }
}

 <zxing-scanner #scanner start="true" [device]="currentDevice" (scanSuccess)="handleQrCodeResult($event)" [formats]="['AZTEC', 'CODABAR', 'CODE_39', 'CODE_93', 'CODE_128', 'DATA_MATRIX', 'EAN_8', 'EAN_13', 'ITF', 'MAXICODE', 'PDF_417', 'QR_CODE', 'RSS_14', 'RSS_EXPANDED', 'UPC_A', 'UPC_E', 'UPC_EAN_EXTENSION']"></zxing-scanner>

We upgraded to Angular 8 and getting below error.
Please advice on this on error TS2339: Property 'getDeviceById' does not exist on type 'ZXingScannerComponent'.

**Comment by odahcam** [comment]
This method was removed and now only exists in the base library:

https://github.com/zxing-js/library/blob/be06578976773f901e25b6711d321b72445da5ed/src/browser/BrowserCodeReader.ts#L197-L209

**Comment by praveen-routhu** [comment]
Hi Team,

PLease provide alternate solution for above one.

**Comment by odahcam** [comment]
```typescript
import { BrowserCodeReader } from '@zxing/library';

async function getMyDevice() {
    const device = await (new BrowserCodeReader()).findDeviceById(YOUR_DEVICES_ID);
}
```

**Comment by facunob1974** [comment]
Hi!



About: new BrowserCodeReader()

Error:
Expected 1-3 arguments, but got 0

Do you have any solution?

**Comment by odahcam** [comment]
Yes, you need to provide a reader to read the barcode, e.g. `new BrowserCodeReader(new QRCodeReader())` or you can use some shorthand like `new BrowserQRCodeReader()`.

**Comment by facunob1974** [comment]
it worked for me!
Thanks!

**Comment by odahcam** [comment]
You are welcome!
