### ISSUE TITLE
CODABAR being Removed ?

### ISSUE THREAD

**Issue by Razgort** [zxing-js/ngx-scanner#232]
Hi guys, 
I just updated my app using your version 1.7.2.
But since then i can't scan barcode 1D
And i saw in your format library it has been removed ...
Why ? is that normal ?
Thanks in advance !

**Comment by odahcam** [comment]
Hey! Sorry, but CODABAR was never supported. You can keep an eye [here](https://github.com/zxing-js/library/pull/195) for more info.
