### ISSUE TITLE
ERROR in src/app/zxing-scanner-impl/zxing-scanner/src/lib/zxing-scanner.component.ts(76,27): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.   Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.

### ISSUE THREAD

**Issue by Priya-mk** [zxing-js/ngx-scanner#235]
**Describe the bug**
Hi, i am getting this issue and not able to solve this--ERROR in src/app/zxing-scanner-impl/zxing-scanner/src/lib/zxing-scanner.component.ts(76,27): error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.
  Object literal may only specify known properties, and 'static' does not exist in type '{ read?: any; }'.

i am using angular 6

**Screenshots**
![image](https://user-images.githubusercontent.com/53892536/62680318-d3596080-b96b-11e9-8527-6bb3ce213688.png)

 - OS: windows 10
 - Browser : chrome
 - Version : angular 6

**Comment by odahcam** [comment]
You forgot to mention what version of the scanner you are using, I believe you're using an ng6 incompatible version BTW.

**Comment by odahcam** [comment]
Well, for Angular 6 please use v1.2.x or v1.4.x, please test if one of these works with your application. Still, I strongly recommend you to update to Angular 8 and the v2 of the scanner.
