### ISSUE TITLE
Qr Scanner doesnt work in firefox

### ISSUE THREAD

**Issue by Magu0013** [zxing-js/ngx-scanner#236]
The QR Scanner works well for me in Chrome, and even Edge, but in firefox there is no camera window. The Browser asks for permission, but after that, nothing happens.

The Demo works in Firefox for me, while the stackblitz demo doesnt, its quite confussing. Is there some special code i need to add for firefox?

**Comment by odahcam** [comment]
StackBlitz demo is with some problems, we unfortunately couldn't properly fix it yet.
