### ISSUE TITLE
Add link to CSS documentation

### ISSUE THREAD

**Issue by dev-mansonthomas** [zxing-js/ngx-scanner#243]
**Describe the bug**
I'm migrating from angularjs to angular8 and some concepts are not obvious.

can you add to this page : 
https://github.com/zxing-js/ngx-scanner/wiki/Advanced-Usage

in the Styling section a link to here:
https://angular.io/guide/component-styles

so that other newbees like me can  understand.

**Comment by dev-mansonthomas** [comment]
Oh, it's also marked as deprecated : 

https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by odahcam** [comment]
Thanks for the feedback, the link was added.
