### ISSUE TITLE
Local build not working on iOS

### ISSUE THREAD

**Issue by lexlix** [zxing-js/ngx-scanner#244]
**Describe the bug**

I really like the ngx-scanner and the [demo](https://zxing-js.github.io/ngx-scanner/) is working grate on my mac and also on my iPhone 7.
First I tried to implement the ngx-sanner in a new angular project which worked fine in chrome on my mac. 
When I tried to access the page on my phone over the local wifi network the part where the camera should be was just empty space.

To minimise the chance that my project had an error I cloned the repo.

**To Reproduce**

I cloned the repo. Ran `npm install` and `ng serve zxing-scanner-demo`
With the same result. Working on my mac and could not check for devices error on my iPhone. 

Currently I ran out of ideas how to debug this problem as it is working fine on the desktop and the demo link is also working fine on my phone. Maybe I'm missing something basic here.

![IMG_4104](https://user-images.githubusercontent.com/6112217/64563672-331e9f00-d350-11e9-9a04-8fe487aa9c93.jpeg)
![IMG_4103](https://user-images.githubusercontent.com/6112217/64563673-331e9f00-d350-11e9-8c3a-a8da58c1eb72.jpeg)

**Desktop:**
 - OS: 10.14.6
 - Browser: Chrome
 - Version: 76.0.3809.87

**Smartphone:**
 - Device: iPhone7
 - OS: 13.1 Beta
 - Browser: Safari

**Comment by odahcam** [comment]
You need HTTPS for that kind of hosting.

**Comment by lexlix** [comment]
Thank you! 
Would have search forever to fix this.
