### ISSUE TITLE
Angular 8 - ngx-scanner takes wide angle camera in Triple Camera Mobiles

### ISSUE THREAD

**Issue by azurehari** [zxing-js/ngx-scanner#245]
I have recently updated my app to Angular 8. 

I used zxing-scanner older version in my app and recently i updated to @zxing/ngx-scanner,

After updating that, i am facing with some problems..
1). I can't set the previewFitMode. In older version it set as 'cover' and i mentioned like below
    <video #preview [style.object-fit]="previewFitMode"> ..... </video>
    ( Note : i can't set the width and height of the video element ) 
    i have tried the below one,
   :host zxing-scanner::ng-deep video {
    max-height: 100%;
    width: 100%;
    object-fit: cover;
}
 
 but it is not working for me..

2). I am using vivo y17( tripple camera mobile). in my mobile ngx-scanner takes the wide angle of the back camera. 

please explain me and reply back ASAP

**Comment by odahcam** [comment]
Can't you select another camera?

**Comment by azurehari** [comment]
i can select cameras but front and rear cameras only showing.
