### ISSUE TITLE
Angular : MediaDeviceInfo is not defined

### ISSUE THREAD

**Issue by azurehari** [zxing-js/ngx-scanner#246]
Hi,
ngx-scanner working fine when i run my angular project in 'localhost'.

But, i am facing 'Mediadeviceinfo is not defined' when i run my project in host.

(i.e)
working : ng serve -o

not working : ng serve --host <my-ip> --port <my-port>

please give me explanation and solution...

**Comment by odahcam** [comment]
Explanation: you need HTTPS.
Solution: Add an SSL certificate to your host.

**Comment by odahcam** [comment]
BTW this is a dupe of #244 and some other issues I can't search now.
