### ISSUE TITLE
It was not possible to play the video.

### ISSUE THREAD

**Issue by nicolaskobelt** [zxing-js/ngx-scanner#248]
#### Bug, feature request, or proposal:
![Screen Shot 2019-09-17 at 10 40 16](https://user-images.githubusercontent.com/17903423/65046851-c1d68180-d937-11e9-841f-34101b03dabb.png)
Hello! I'm trying use the scanner but I have this error, I don't understand whats the problem.

**Comment by odahcam** [comment]
Please provide at least debug information.
