### ISSUE TITLE
Can't get user media, this is not supported.

### ISSUE THREAD

**Issue by stillanoob** [zxing-js/ngx-scanner#251]
**Describe the bug**
zxing-ngx-scanner.js:496  @zxing/ngx-scanner Can't get user media, this is not supported.
it was all working fine when i run the project using : "ng s"
but when i used : "ng serve --host 192.168.1.4 --port 4202"
it doesn't work on pc neither does it on phone
could please lead me how to correct this issue?

**Comment by stillanoob** [comment]
You need SSL to access the user devices or explicit server the application from localhost. I can see in your print, you're under a IP address, which requires SSL.
i confirmed it's the same problem it works on local host but it doesn't when hosting on ip
so can you guide me how to get ssl to access user devices?

**Comment by odahcam** [comment]
In short, SSL won't access anything, but the website needs to serve it so the browser can recongnize and use it for the user security. Take a look here: https://medium.com/@rubenvermeulen/running-angular-cli-over-https-with-a-trusted-certificate-4a0d5f92747a

**Comment by stillanoob** [comment]
thank you that really solved it 
although seeing the go back to security page everytime is disturbing
but it will still work for presentation thanks odahcam

**Comment by odahcam** [comment]
Yw, you can add the generated certificate to your OS's trusted certificates, so the OS will trust the self-signed certificate and won't show the untrusted dialog-page. Remember that for production you should use real SSL certificates. Good luck!

**Comment by lano-vargas** [comment]
I've stumbled upon this error when using --host IP address, with -ssl has resolved the issue for me!
