### ISSUE TITLE
Defaulting integrated webcam as the bar-code scanner does not work.

### ISSUE THREAD

**Issue by tilakdewangan-gep** [zxing-js/ngx-scanner#254]
Hi Team,

I am using this library (version - 2.0.1) as the bar-code scanner in my angular 5 (web) project. When I set integrated webcam as the default scanning device then it does not work meaning opens the scanner but it does not read the barcode. (please see below how I am setting the default scanning device). 

`

        onCamerasFound(devices: MediaDeviceInfo[]): void {
            this.availableDevices = devices;  
            this.hasDevices = Boolean(devices && devices.length);
            if (this.hasDevices)
                this.currentDevice = this.availableDevices[0];
                this.scanner.device = this.currentDevice; //this.scanner is template reference variable of type ZXingScannerComponent
            }
        }  

`

Below is the `html` code for the scanner
`<zxing-scanner #zxingScanner  [torch]="torchEnabled" [formats]="formatsEnabled"
        [tryHarder]="tryHarder" (permissionResponse)="onHasPermission($event)" (camerasFound)="onCamerasFound($event)"
        (torchCompatible)="onTorchCompatible($event)" (scanSuccess)="onCodeResult($event)">
      </zxing-scanner>`

Please help me to fix this issue as soon as possible.

**Comment by odahcam** [comment]
Whats your `formatsEnabled` variable value?

**Comment by tilakdewangan-gep** [comment]
This is what I have as `formatEnabled` - 

`formatsEnabled: BarcodeFormat[] = [
        BarcodeFormat.CODE_128
 ];`

**Comment by odahcam** [comment]
Oh I noticed now, the version 2.0.1 does not officially supports  Angular 5, you should either downgrade your scanner version or upgrade Angular. Thanks for reaching out.

**Comment by suriyaJaay** [comment]
@odahcam can you pls open stackblitz on this same thread.? currently using Angular 10 and but struggling to set default ingratiated camera on laptop
