### ISSUE TITLE
Scan once & default square img

### ISSUE THREAD

**Issue by AlexisP98** [zxing-js/ngx-scanner#256]
Hi everyone,
is there any way to make the scanner trigger only once and avoid it to listen every second?
Further more, is there any default square like the img which I put.

PS. Screenshots below.

<img width="1245" alt="Schermata 2019-10-14 alle 12 24 22" src="https://user-images.githubusercontent.com/35902161/66744999-2d036d00-ee7e-11e9-900c-dba202a41244.png">
<img width="437" alt="Schermata 2019-10-14 alle 12 23 48" src="https://user-images.githubusercontent.com/35902161/66745000-2d036d00-ee7e-11e9-935d-056416b41df9.png">

Thank you for your time!

**Comment by odahcam** [comment]
This is a dupe of #122 .

For decoding only once, you can both stop the scanner or simply ignore subsequent scans.

Thanks for reaching out.
