### ISSUE TITLE
Property 'toJSON' is missing in type 'VideoInputDevice' but required in type 'MediaDeviceInfo'

### ISSUE THREAD

**Issue by ymallikreddy521** [zxing-js/ngx-scanner#257]
We updated the angular to 8.2.9

and we get below error

ERROR in ../node_modules/@zxing/library/esm5/browser/VideoInputDevice.d.ts:6:22 - error TS2420: Class 'VideoInputDevice' incorrectly implements interface 'MediaDeviceInfo'.
  Property 'toJSON' is missing in type 'VideoInputDevice' but required in type 'MediaDeviceInfo'.

6 export declare class VideoInputDevice implements MediaDeviceInfo {
                       ~~~~~~~~~~~~~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:9927:5
    9927     toJSON(): any;
             ~~~~~~~~~~~~~~
    'toJSON' is declared here.

**Comment by ymallikreddy521** [comment]
updated to 2.0.1 and works.

**Comment by Asif-Ferdous** [comment]
@ymallikreddy521 which one u updated? can you mention please?
