### ISSUE TITLE
iOS 13 not switching back camera?

### ISSUE THREAD

**Issue by ethangong0809** [zxing-js/ngx-scanner#258]
I tried two iOS devices,  one is iOS 12, iphone 6, the back camera automatically turned on when I open the scanner, however another one (iOS 13, iphone X) only shows front camera.

Codes may affect:
      // selects the devices's back camera by default
      for (const device of devices) {
        if (/back|rear|environment/gi.test(device.label)) {
          // this.scanner.deviceChange(device);
          this.currentDevice = device;
          break;
        }
      }

**Comment by ethangong0809** [comment]
Worked on latest version for iOS 13, closed the issue.

**Comment by chetana1997** [comment]
Hello, i am facing the same issue at my end and was wondering how to fix it.
Can you please share the solution @ethangong0809. 

Thanks in advance.
