### ISSUE TITLE
Rectangular dimension marks during barcode scanning will make this zxing scanner the best out of all..

### ISSUE THREAD

**Issue by jnjaga24** [zxing-js/ngx-scanner#259]
During barcode scanning we are not able to identify where is the focus area in the camera frame. 
If some rectangular indication is available during barcode scanning it will help non-tech users during scanning.

**Comment by jnjaga24** [comment]
Can we expect this feature roll out?

**Comment by odahcam** [comment]
Not so soon, sorry. I've been very busy lately, so I couldn't contribute to the project as much as I'd like.
