### ISSUE TITLE
iPhone native Safari is reporting "You denied the camera permission"

### ISSUE THREAD

**Issue by mplawley** [zxing-js/ngx-scanner#260]
**Describe the bug**
Visit `https://zxing-js.github.io/ngx-scanner/` on iOS Safari and see the "You denied the camera permission" message.

**To Reproduce**
1. In iOS settings, ensure that Safari camera access is set to "Ask" or "Allow."
2. Go to `https://zxing-js.github.io/ngx-scanner/`
3. Observe that the `*ngIf="hasPermission === false` div content is displayed
4. Note that on a desktop in either Chrome or Safari, `https://zxing-js.github.io/ngx-scanner/` works as expected.

**Expected behavior**
I can go to `https://zxing-js.github.io/ngx-scanner/` and see the scanner work as usual.

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 13.1.2
 - Browser: Safari

Of course it's possible that there's something idiosyncratic on my end because it's hard to imagine that such a popular module would experience this error without it being reported already, especially since @odahcam has access to an iPhone 7 as reported elsewhere in this repo's Issues. And as a side note, ngx-scanner is great: thank you for building this.

**Comment by odahcam** [comment]
Sorry, but o Macbook I found no problems:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/3942006/69100506-18496480-0a3c-11ea-9cb5-7e675e0d296f.png">

I'm not with that iPhone now, hehe, but we do can investigate further.

Have you ever denied the camera access before on the iPhone?

**Comment by mplawley** [comment]
Same here: on MacBook, no problems (including on Safari). But still not working on my iPhone. I never have denied the camera access before. Very curious about the results you get when you try on iOS on your end.

**Comment by mplawley** [comment]
Solution: I was able to fix this issue by upgrading iOS to version 13.2.3.

**Comment by odahcam** [comment]
That's odd, what version were you using before?
