### ISSUE TITLE
Ability to scan inverted (white on black) codes

### ISSUE THREAD

**Issue by kevincorizi** [zxing-js/ngx-scanner#261]
**Is your feature request related to a problem? Please describe.**
I had the need to scan an inverted QR code: although not standard, it is a quite common use case and as far as I could read on the Internet, other libraries do have support for it.

**Describe the solution you'd like**
What i implemented in my local project is an extension of the BrowserMultiFormatReader class to reimplement the createBinaryBitmap changing the luminanceSource as found in this link: https://github.com/zxing-js/library/issues/135.
To support both modes, this extended class has a mode toggling variable.
I then assign the scanner.codeReader.createBinaryBitmap method to the one of the extended class.

**Describe alternatives you've considered**

**Additional context**
This is clearly a hack (although a working one). I would like this to be implemented in the BrowserMultiFormatContinuousReader class, maybe with a "enableInverseRead" method that could be exposed to let users decide how to handle the two modes.

I would be very glad to contribute with my solution so far, let me know if it is something you would like to add to the library and I can create a PR to show you what i have so far :)

**Comment by AdrienPoupa** [comment]
I would be glad to see such as PR :) Let me know if I can help!

**Comment by odahcam** [comment]
We should first implement this on the zxing/library package, so we could just use the feature here, without the need for creating more hacks. I'm also the maintainer of the library, so I can say this feature would be very welcome there too.

**Comment by beyerleinf** [comment]
Any news on this?

**Comment by qrsolve** [comment]
> **Is your feature request related to a problem? Please describe.**
> I had the need to scan an inverted QR code: although not standard, it is a quite common use case and as far as I could read on the Internet, other libraries do have support for it.
> 
> **Describe the solution you'd like**
> What i implemented in my local project is an extension of the BrowserMultiFormatReader class to reimplement the createBinaryBitmap changing the luminanceSource as found in this link: [zxing-js/library#135](https://github.com/zxing-js/library/issues/135).
> To support both modes, this extended class has a mode toggling variable.
> I then assign the scanner.codeReader.createBinaryBitmap method to the one of the extended class.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> This is clearly a hack (although a working one). I would like this to be implemented in the BrowserMultiFormatContinuousReader class, maybe with a "enableInverseRead" method that could be exposed to let users decide how to handle the two modes.
> 
> I would be very glad to contribute with my solution so far, let me know if it is something you would like to add to the library and I can create a PR to show you what i have so far :)

Hi, could you share this solution?

**Comment by Romanizat** [comment]
Any new development on this? 

I saw the mentioned issue by elmi82, but it does not solve my current requirement.

I use your library to activate video scanning from a device and it's active until it scans the QR code, and it works great, thanks!

But...

Like [kevincorizi](https://github.com/kevincorizi) mentioned, I require scanning of inverted QR codes (white code on black background), and I've been trying all kinds of hacks to get it to work, but apparently it only registers black code on white background.

If there isn't any development on this requested feature, is there someone who could help me implement some sort of hack to be able to scan the inverted codes?

I have been trying to invert the input video, but to no avail.

**Comment by Romanizat** [comment]
Any new development on this? 

I saw the mentioned issue by elmi82, but it does not solve my current requirement.

I use your library to activate video scanning from a device and it's active until it scans the QR code, and it works great, thanks!

But...

Like [kevincorizi](https://github.com/kevincorizi) mentioned, I require scanning of inverted QR codes (white code on black background), and I've been trying all kinds of hacks to get it to work, but apparently it only registers black code on white background.

If there isn't any development on this requested feature, is there someone who could help me implement some sort of hack to be able to scan the inverted codes?

I have been trying to invert the input video, but to no avail.

**Comment by anbaran** [comment]
Is this issue fixed?

**Comment by anbaran** [comment]
In case someone needs it...

With a little help from AI , here is a workaround which can scan normal and inverted QR codes. This code below works for me

```
import { Component, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import { Component, ViewChild, AfterViewInit, OnDestroy } from '@angular/core';
import { ZXingScannerComponent } from '@zxing/ngx-scanner';
import { BrowserMultiFormatReader, Result } from '@zxing/browser';

@Component({
  selector: 'app-qr-scanner',
  templateUrl: './qr-scanner.component.html',
  styleUrls: ['./qr-scanner.component.css']
})
export class QrScannerComponent implements AfterViewInit, OnDestroy {
  @ViewChild('scanner') scanner!: ZXingScannerComponent;

  device: MediaDeviceInfo | undefined;
  private codeReader = new BrowserMultiFormatReader();
  private animationFrameId?: number;
  private canvas!: HTMLCanvasElement;
  private ctx!: CanvasRenderingContext2D;

  ngAfterViewInit() {
    // Prepare hidden canvas for processing
    this.canvas = document.createElement('canvas');
    this.ctx = this.canvas.getContext('2d')!;

    // Get the video element from zxing-scanner
    const videoEl = this.scanner.previewElemRef.nativeElement as HTMLVideoElement;
    this.startCustomLoop(videoEl);
  }

  onCamerasFound(devices: MediaDeviceInfo[]) {
    if (devices.length > 0) {
      this.device = devices[0]; // pick default camera
    }
  }

  private startCustomLoop(video: HTMLVideoElement) {
    const loop = async () => {
      if (video.readyState === video.HAVE_ENOUGH_DATA) {
        this.canvas.width = video.videoWidth;
        this.canvas.height = video.videoHeight;
        this.ctx.drawImage(video, 0, 0);

        // 1️⃣ Try normal decode
        let result: Result | null = await this.tryDecodeCanvas();

        // 2️⃣ If failed, try inverted decode
        if (!result) {
          const frame = this.ctx.getImageData(0, 0, video.videoWidth, video.videoHeight);
          this.invertImage(frame.data);
          this.ctx.putImageData(frame, 0, 0);
          result = await this.tryDecodeCanvas();
        }

        // 3️⃣ If found, handle the result
        if (result) {
          console.log('Scanned:', result.getText());
           cancelAnimationFrame(this.animationFrameId!);
          return;
        }
      }
      this.animationFrameId = requestAnimationFrame(loop);
    };
    loop();
  }

  private async tryDecodeCanvas(): Promise<Result | null> {
    try {
      const result = await this.codeReader.decodeFromCanvas(this.canvas);
      return result;
    } catch {
      return null;
    }
  }

  private invertImage(data: Uint8ClampedArray) {
    for (let i = 0; i < data.length; i += 4) {
      data[i] = 255 - data[i];       // R
      data[i + 1] = 255 - data[i + 1]; // G
      data[i + 2] = 255 - data[i + 2]; // B
    }
  }

  ngOnDestroy() {
    if (this.animationFrameId) {
      cancelAnimationFrame(this.animationFrameId);
    }
  }
}

```

```
<zxing-scanner
  #scanner
  [device]="device"
  (camerasFound)="onCamerasFound($event)">
</zxing-scanner>
```
