### ISSUE TITLE
Videostream Update Stream

### ISSUE THREAD

**Issue by fvgack** [zxing-js/ngx-scanner#262]
**Describe the bug**
The update speed of the video stream element is to fast. 

**Expected behavior**
Make it possible to set the update speed or the time when the scanner detects a new barcode.

**Comment by odahcam** [comment]
It is possible to control the time between scan attempts in the base library and it's also possible to control the time after a successful scan. Is anything like that you need?

**Comment by fvgack** [comment]
Yes. Thats what I need. Can you name the file and the variable where i can change that?

**Comment by odahcam** [comment]
Sorry, you can't change that via `zxing-ngx-scanner` element, you would need to customize the library or use the base library for that. Is that possible for ya?
