### ISSUE TITLE
Get barcode type scanned

### ISSUE THREAD

**Issue by JuanPeWork** [zxing-js/ngx-scanner#264]
Any way to get the scanned barcode type? Scanner component return only barcode in text.

**Comment by odahcam** [comment]
Yes, the `scanComplete` receives the `Result` object as a parameter, which contains the barcode type. It emits every scan, no matter there's a result or not.

**Comment by JuanPeWork** [comment]
Thank you so much for everything.
Regards.

**Comment by odahcam** [comment]
You're welcome.
