### ISSUE TITLE
Rear Camera opening issue with different iOS Versions

### ISSUE THREAD

**Issue by manish-raana** [zxing-js/ngx-scanner#268]
**Describe the bug**
I am trying to implement a qr code scanner, earlier it was working fine but after update, I'm getting some unexpected results, it is opening front camera for some ios versions and back camera for some other ios versions, 
How can I deal with this issue?

**Comment by odahcam** [comment]
You can use the `camerasFound` property to get a list of all found cameras, select the camera you want to scan with and then set the `device` property with the desired camera.

**Comment by deepender87** [comment]
Not working

**Comment by odahcam** [comment]
@deepender87 do you want me to fix it for you?

**Comment by Xenoage** [comment]
I noticed that the labels of the cameras can be language-dependent. For me (in Germany). iOS 12.4.6, it was "Rückkamera" (= German for rear camera). Knowing this, I could choose the right MediaDeviceInfo, however setting it using the device-Property of the angular component had no effect!

**Comment by odahcam** [comment]
Try changing the device in the `camerasFound` hook:

```html
  <zxing-scanner [(device)]="currentDevice"
    (camerasFound)="onCamerasFound($event)"></zxing-scanner>
```

```typescript
{
  onCamerasFound($event) {
    this.currentDevice = /* choose your camera from $event */
  }
}

Maybe that helps.

**Comment by Xenoage** [comment]
Not really. Opening another issue for this.
