### ISSUE TITLE
Cannot find module  'ts-custom-error'.

### ISSUE THREAD

**Issue by tilakdewangan-gep** [zxing-js/ngx-scanner#269]
Hi Team,

I am getting 2-3 errors (see screenshot) while using this scanner. Could you please help me to fix these.

Please let me know any other information.

**Screenshots**
![image](https://user-images.githubusercontent.com/53517601/70992202-277d0a00-20ef-11ea-9ff5-8e31344ccb8e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 2.0.1

**Comment by odahcam** [comment]
Are you using the library via NPM packages?
