### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by gabrielbusarello** [zxing-js/ngx-scanner#270]
**Describe the bug**
When switching between cameras throws the error: ExpressionChangedAfterItHasBeenCheckedError.
The error throws in the stackblitz example of yours too.

In that link: https://zxing-js.github.io/ngx-scanner/

**To Reproduce**
1. Open the console
2. Select some other devices
3. See error.

**Expected behavior**
Change device without throws errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/25415068/71028136-79239580-20eb-11ea-8a7e-c41bddc8959e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10 PRO
 - Browser [e.g. chrome, safari]: Chrome.
 - Version [e.g. 22]: 79.0.3945.79

**Comment by rafaellyra** [comment]
I removed that warning by adding a setTimeout  to the reset method:
```
/**
     * Resets the scanner and emits device change.
     */
    ZXingScannerComponent.prototype.reset = function () {
        this._reset();
        setTimeout(() => {
            this.deviceChange.emit(null);
        })
    };
```

**Comment by krumholz** [comment]
> ZXingScannerComponent.prototype.reset = function () {
>         this._reset();
>         setTimeout(() => {
>             this.deviceChange.emit(null);
>         })
>     };

@rafaellyra, where do you put this code to get rid of that error?
