### ISSUE TITLE
Barebones ngx-scanner not working in Angular 7. 

### ISSUE THREAD

**Issue by JohanJarvi** [zxing-js/ngx-scanner#273]
I just created a brand new Angular 7 app using “ng new”. I then replicated your entire stack blitz code line for line and when I open the app I do not get asked to allow camera access on iOS Safari with an iPhone 7 Plus running version iOS13.3.

**To Reproduce**
1. Create new Angular 7 app
2. Include full stackblitz code from this very github repo. 
3. Run demo application.
4. Nothing happens. Does not work. 

**Expected behaviour**
I expected it to work. Prompt me for camera access and then allow me to scan a QR code. 

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS13.3
 - Browser Safari

**Comment by odahcam** [comment]
Well, that's kinda hard for me to reproduce, since it's impossible for me or anyone to do the same steps you did while copy and pasting stackblitz code. 

I rather guess that you are using a version of this library that doesn't work well with Angular 7 and suggest you to use Angular 8 instead. If you can't use Angular 8 I would say to you to downgrade this library's package version inside your project.

You can always create a StackBlitz demo of your problem and include it in here for me (or others) to take a look and try to find put whats wrong with the code or the library. :)

**Comment by JohanJarvi** [comment]
So I’ve now upgraded to angular 9 with the latest version of the scanner and it works when I’m running my angular app in Chrome. However, running it locally on an iPhone device through safari shows a blank screen. It does not access the camera and does not allow me to scan a QR code. 

You should very easily be able to reproduce this by simply trying to use your scanner with an iPhone in any angular app anywhere. Because, it doesn’t work.

**Comment by JohanJarvi** [comment]
Hey mate, I have now tried to upgrade to angular 9 but I’m having a very similar issue as I was having before. 

I unfortunately cannot you you anymore information other than that I’m running an iPhone 7 Plus at 13.3.1 version and when I open my app locally hosted through my PC the scanner opens a blank screen. 

It does not show a camera and does not ask me for permission to show the camera. 

This works fine on chrome on my pc with my web cam but unfortunately does not work on iOS in safari. 

I wish I could give you more info but it’s just blank.

**Comment by JohanJarvi** [comment]
I finally got my hands on testing through a mac and it turns out the error is "Can't get user media, this isnt supported" most likely through not having ssl when hosting in localhost, I'm going to experiment with existing solutions and let you know but it's likely that I will solve the issue now.

**Comment by JohanJarvi** [comment]
Yes so turns out this was caused by the lack of SSL when hosting the application in localhost. Once it was deployed to the server it prompted me for camera access and could scan the QR code no problem.
