### ISSUE TITLE
Camera not opening up in iOS Chrome, but it works in Safari and Android Chrome, Desktop browsers etc

### ISSUE THREAD

**Issue by iamntg** [zxing-js/ngx-scanner#275]
Hi,

The camera prompt is not showing, camera not opening in iOS Chrome browser.
but the same is working well in safari, android and desktop browsers.

while inspecting chrome in iOS,
Error showing as:
**ERROR** @zxing/ngx-scanner Can't get user media, this is not supported.

The same works well in chrome,
I believe safari and chrome shares the same engine, not sure why this issue happens only in Chrome.

Anybody have any solutions for this?

**Comment by odahcam** [comment]
Probably due to this: https://github.com/zxing-js/ngx-scanner#limitations

**Comment by iamntg** [comment]
Update:
Checked with Firefox, Opera and Edge in iOS, all having same issue as Chrome.

Dont know whether iOS gives camera access to safari only.

is there a work around for this?

**Comment by iamntg** [comment]
@odahcam ,

my iOS version is 12.3.1

**Comment by chobijaeyu** [comment]
> Probably due to this: https://github.com/zxing-js/ngx-scanner#limitations
> 
> > On iOS <= 11.2 devices camera access works only in native Safari. This is limited WebRTC support by Apple.

hi 
good day.

I know It works only in safari.
but it not working with  safari add to homescreen.
Is my problem or apple's problem?

thanks

**Comment by javitzso** [comment]
On March 4th the camera became unusable in Safari on all the iOS devices that I manage. Using Javascript ZXING.

I could pick up a different device, open Safari, use the camera to scan barcodes and then it would just stop working. The little red camera icon would disappear and it wouldn't ask for permission again.  Eventually this happened on all the iOS devices I manage.

I feel like it's related to the March 3rd HTML5 access limitations imposed by Apple.

**Comment by odahcam** [comment]
> Probably due to this: https://github.com/zxing-js/ngx-scanner#limitations
> 
> > On iOS <= 11.2 devices camera access works only in native Safari. This is limited WebRTC support by Apple.

@chobijaeyu just read man...
