### ISSUE TITLE
iOS + Safari: No camera found

### ISSUE THREAD

**Issue by boerdjamin** [zxing-js/ngx-scanner#276]
#### Problem:
The Demo on https://zxing-js.github.io/ngx-scanner/ works totally fine with the same setting, but it doesn't work on my pwa in local developement. 

#### What is the expected behavior?
Same behavior as in Safari on Mac: Question for permission > Camera found

#### What is the current behavior?
* no cameras found
* no asking for permission
* permission seems to be implicitly granted (permissionResponse is true)

#### Environment
iPhone 8, iOS13.3, Safari
"@zxing/ngx-scanner": "^2.0.1",

**Comment by boerdjamin** [comment]
Update: Did a little more research and found #156.

https://caniuse.com/#search=getusermedia

![image](https://user-images.githubusercontent.com/24297798/73075117-7b7fc900-3ebb-11ea-9cc6-d63152dc08b6.png)

**Comment by odahcam** [comment]
Yep, there are already lot's of questions about it. I think the README section that explains it needs a little more attention in order to users read it. 😕
