### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by DennisSapia** [zxing-js/ngx-scanner#278]
Hi all,

 

we are facing an issue with your Angular library.

 

What we use:
Angular CLI v8.3.0
Node v12.3.1
NPM v6.11.2
Latest @zxing/ngx-scanner release

 

We followed the exact steps of your GitHub wiki "Getting Started" section. When starting the Angular application locally we get asked for camera permission. The current camera view shows up in our Angular application. But now what doesn't work is the feature of your library. We can't scan a QR Code, barcode, etc. The Angular application doesn't do anything when trying to scan a QR Code via camera.

 

Could you please help us on this problem?

 

Kind regards
Dennis Sapia

**Comment by odahcam** [comment]
Could you setup a demo or something?

**Comment by DennisPietsch** [comment]
[
[cameraattempt2.zip](https://github.com/zxing-js/ngx-scanner/files/4133538/cameraattempt2.zip)
](url)

**Comment by odahcam** [comment]
It does works, but you are not using the decoded value for anything. You should try binding to the `scanSuccess` event like: 

```html
<zxing-scanner [formats]="..." (scanSuccess)="onScanSuccessHandler($event)"></zxing-scanner>
```

It shall do the job for ya.

**Comment by DennisSapia** [comment]
Hello,

Thank you very much for your quick response,
The Barcodescanner is working out now, at least for the most Formats.
But for some reason the Barcodescanner  won't work on Barcodes with the PDF_417 Format.
Can you help me out? May it be, that you haven't implemented the PDF_417 Format yet?
I Imported it as BarcodeFormat.PDF_417 in my TypeScript, but this won't work.
Could you give me any advice or do you have a solution for this problem?

I am Looking forward to hearing from you.

Kind regards,
Dennis Sapia

Here's a snippet of how i tried to implement the PDF_417 Format. Should be correct, i guess?
//app.component.ts
`formatsEnabled: BarcodeFormat[] = [
    /** PDF417 format. */
    BarcodeFormat.PDF_417,
  ];`

**Comment by odahcam** [comment]
[These are the suported barcode formats](https://github.com/zxing-js/library#supported-formats), PDF417 is not one of them, sorry.

**Comment by DennisPietsch** [comment]
Why you don’t support PDF 417?
And can we help you with it?

**Comment by odahcam** [comment]
> Why you don’t support PDF 417?

Because no one has written fully working PDF 417 decoding on the library.

> And can we help you with it?

Yes, you can start in here: https://github.com/zxing-js/library/issues/59
