### ISSUE TITLE
Trying to play video that is already playing.

### ISSUE THREAD

**Issue by mrcrixx** [zxing-js/ngx-scanner#279]
UPDATE. it turns out that there where no problems at all, just a simple css overrode a class making the video opacity to 0, the warn message in console appears even if everything is working fine... sorry for report

#### Bug, feature request, or proposal:
Suddenly when I enter in the page where I was using the scanner, it appears the selector to select the camera as usual but no video appears. In the console I got this error message

  | (anonymous) | @ | BrowserCodeReader.js:490
-- | -- | -- | --
  | step | @ | BrowserCodeReader.js:32
  | (anonymous) | @ | BrowserCodeReader.js:13
  | (anonymous) | @ | BrowserCodeReader.js:7
  | ZoneAwarePromise | @ | zone-evergreen.js:876
  | push../node_modules/@zxing/library/esm5/browser/BrowserCodeReader.js.__awaiter | @ | BrowserCodeReader.js:3
  | push../node_modules/@zxing/library/esm5/browser/BrowserCodeReader.js.BrowserCodeReader.tryPlayVideo | @ | BrowserCodeReader.js:484
  | videoCanPlayListener | @ | BrowserCodeReader.js:466
  | invokeTask | @ | zone-evergreen.js:391
  | onInvokeTask | @ | core.js:39680
  | invokeTask | @ | zone-evergreen.js:390
  | runTask | @ | zone-evergreen.js:168
  | invokeTask | @ | zone-evergreen.js:465
  | invokeTask | @ | zone-evergreen.js:1603
  | globalZoneAwareCallback

#### What is the expected behavior?

the video to appear then to be able to scan a qcode and get the result

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/fork/zxing-ngx-scanner<br/>

#### Is there anything else we should know?
It worked normally till now I didnt touch this page I dont know what could cause this issue.

**Comment by odahcam** [comment]
Thanks for the report, I left that message there just to collect data about when it happens, cause debug everything in the library alone is so painful. That's just a way to obtain help, as you did. And yes, the help I'm whiling to receive is to solve this issue and discover if it breaks the scan at any time. Until now, no case lead to break the lib, so your should not worry. :)
