### ISSUE TITLE
ERROR Error: Uncaught (in promise): NotReadableError: Could not start video source on Chrome

### ISSUE THREAD

**Issue by kinghaseo** [zxing-js/ngx-scanner#281]
**Describe the bug**
On Chrome the bar code scanner doesn't work consistently after web browser refresh it stop scanning sometimes.

**To Reproduce**
1. Go to (https://stackblitz.com/edit/angular-playground-cztk8r?file=app%2Fmodules%2Fdashboard%2Fdashboard.component.html)
2.  click open camera 
3. Click on Av Steam Media device
4. Spam scanning a bar code.
5. refresh browser then redo step 2 to 4 till the bar code stops showing up in the console

**Expected behavior**
Bar code should always be expected to show in the console even after refresh

**Video of the bug**
Check video below : 
https://drive.google.com/file/d/1PnI3eF6YZfY4r2xoYBGFbwrdHDlM3Y04/view?usp=sharing

the bar code is present on the console after a refresh and switching to av Stream Device i was scanning the bar code the only thing that was happening there was the dropdown opening/closing instead of printing in the console.

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 80.0.3987.106 (Official Build) (64-bit)
 - Using Angular 9

**Additional context**
Btw does the camera have to be open when initializing , i mean the purpose of using this in my project is to scan not using the camera ,but with actually using a physically bar code scanner

Another thing that bugs me is that cant' read video source error

**Comment by kinghaseo** [comment]
Seems that the scanner pastes where it is focus .

I got so bamboozled with this .

Request to update the wiki and be more informative  regarding this library.

Another Question in regards 

>  Does the camera have to be open when initializing , i mean the purpose of using this in my project is to scan not using the camera ,but with actually using a physically bar code scanner

**Comment by odahcam** [comment]
> Does the camera have to be open when initializing , i mean the purpose of using this in my project is to scan not using the camera ,but with actually using a physically bar code scanner

This library has no integration with physical devices.
