### ISSUE TITLE
Cannot read property 'camerasFound' of undefined - Angular 9

### ISSUE THREAD

**Issue by ymallikreddy521** [zxing-js/ngx-scanner#283]
Upgraded from Angular 8 to Angular 9.

#### What is the expected behavior?
Camera should display

#### What is the current behavior?
Cannot read property 'camerasFound' of undefined

"@zxing/ngx-scanner": "~2.0.1"

Code Snippet
 <zxing-scanner  #scanner  [autofocusEnabled]="true" [autostart]="false" [enable]="true"  [device]="currentDevice"
          (scanComplete)="handleScanComplete($event)" [formats]="allowedFormats"
          [tryHarder]="true"></zxing-scanner>

ngOnInit() {
    this.onPageInit();
  }

  private onPageInit(){
    this.initCamera();
    this.scanner.permissionResponse.subscribe(
      (perm: boolean) =>{
       this.hasPermission = perm;
      });
}
 private initCamera(): void {
    this.scanner.camerasFound.subscribe((devices: MediaDeviceInfo[]) => {
      this.hasDevices = true;
      this.availableDevices = devices;
      this.currentDevice = null;
      if (this.availableDevices.length > 1) {
        const defaultCamera = this.availableDevices.filter(e => e.label.toLocaleLowerCase().indexOf('back') > -1);
        if (defaultCamera !== null && defaultCamera !== undefined) {
          this.currentDevice = defaultCamera[0];
        } else {
           this.currentDevice = this.availableDevices[0];
        }
      } else {
        this.currentDevice = this.availableDevices[0];
      }
    });
  }

**Comment by royvanderwesten** [comment]
Hi,
It's saying it can't find this.scanner, obvious question but, did you define `scanner: ZXingScannerComponent;` in your component.ts?

**Comment by ymallikreddy521** [comment]
Yes. It is working in Angular 8

**Comment by ymallikreddy521** [comment]
chnaged static to true

**Comment by Tasleem-Archolad** [comment]
any progress in this issue, Actually i got the same error while trying to develop a simple zxing scanner application. [https://stackblitz.com/edit/zxing-ngx-scanner-qrbar-bgtq77?file=app%2Fapp.component.ts](url) this is the same code working fine in stackblitz but im getting "ERROR TypeError: this.scanner.camerasFound is undefined" in localhost.

Thanks in advance
