### ISSUE TITLE
Ngx-scanner in Mozilla on Android

### ISSUE THREAD

**Issue by mrdantutunaru** [zxing-js/ngx-scanner#284]
Hi there,

Thanks for this library, but I wanna ask, when scanning with Chrome on Android, it asks for permission once and after it remembers my choice, with Mozilla is not the same, I have to allow for permission every time...any suggestion on this, how can I remember the choice in Mozilla ?

Thanks

**Comment by b-mi** [comment]
Same problem

**Comment by odahcam** [comment]
No, it's a browser behavior, same happens on Safari, sorry.
