### ISSUE TITLE
Unable to scan data matrix imprinted on black surface

### ISSUE THREAD

**Issue by mac4manu** [zxing-js/ngx-scanner#285]
**Describe the bug**
I'm unable to scan the data matrix which is imprinted on black surface especially on plastic box.
Could you please suggest?

**Comment by odahcam** [comment]
Could you share a picture of that code?

**Comment by mac4manu** [comment]
I don't have the exact one, but attached the similar one which I took it from web.

https://st2.depositphotos.com/1537427/10704/v/950/depositphotos_107040320-stock-illustration-datamatrix-code-icons.jpg

Mainly the one with black background - First picture

**Comment by odahcam** [comment]
There's a little bigger step you need to take for being able to decode inverted data matrix trough this component, which I think might not be possible for now. Here's an example of what we need to do: https://github.com/zxing-js/library/issues/135#issuecomment-470430181

**Comment by mac4manu** [comment]
@odahcam  - Please let me know if you have any update on this?

**Comment by odahcam** [comment]
Nope, I did not work on this issue in the past weeks, sorry.
