### ISSUE TITLE
Online demo not work on android (actual) and Firefox (actual)

### ISSUE THREAD

**Issue by b-mi** [zxing-js/ngx-scanner#286]
**Describe the bug**
Online demo not work on android (actual) and Firefox (actual)
Appliacation ask for permissions, after confiramtion stay "No Device Selected"

**To Reproduce**
1. Go to online dem from this page

**Expected behavior**
ncx-scanner work on android firefox.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: xiaomi mi a1
 - OS: android 9
 - Browser firefox form google play downloaded today

**Additional context**

**Comment by odahcam** [comment]
I have the same device, just tested, it's working. Sorry.

**Comment by odahcam** [comment]
Maybe you denied Chrome's or Firefox's camera permission or something.
