### ISSUE TITLE
"Your browser does not support this feature, please try to upgrade it."

### ISSUE THREAD

**Issue by olopez1908** [zxing-js/ngx-scanner#292]
**Describe the bug**
I'm using the version 1.2.0 with angular 4 when I trying to use the component I getting this error on " Your browser does not support this feature, please try to upgrade it.", I have the lastest version on chrome browser 81.0.4044.92 , I'm using Linux OS, On the same Chrome window the demo is working well

**Screenshots**
![image](https://user-images.githubusercontent.com/63618332/79166994-fd410d80-7dab-11ea-84f6-92315988429e.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version  81.0.4044.92

**Comment by odahcam** [comment]
Does this text appears for you rendered in the screen?

**Comment by olopez1908** [comment]
@odahcam That text isn't rendered in the screen, I saw it when inspect on the elements, Yesterday I update my chrome to version Version 81.0.4044.92 (Official Build) (64-bit) and I has is the same behavior

**Comment by odahcam** [comment]
Then you're not getting the error. Older browsers used support only one tab using the camera device per window, maybe that's your issue.

**Comment by olopez1908** [comment]
But I has the latest version the browser and I only have one open  tab in the browser, I trying with Firefox and Chrome on the latest version each

**Comment by odahcam** [comment]
It must be another error, that message written in the source has nothing to do with your problem, if it had, it would be rendered in the screen.

**Comment by olopez1908** [comment]
Any idea what is happen? What version support angular 4?

**Comment by odahcam** [comment]
Try looking at your console to see if there's any error there.

**Comment by olopez1908** [comment]
no, I don't have error on the console everything looks good

**Comment by odahcam** [comment]
The lack of errors or any info makes it impossible for me to figure out what may be happening.

**Comment by Sireini** [comment]
@olopez1908 you found something?

**Comment by olopez1908** [comment]
@Sireini I couldn't make it run with angular 4, The solution for my issue was upgrade angular to the last version
