### ISSUE TITLE
Barcode of format CODE_128 does not get scanned correctly. 

### ISSUE THREAD

**Issue by pix1289** [zxing-js/ngx-scanner#296]
I am trying to scan CODE_128 barcode using my laptop camera. The scanner takes a long time to scan and if it does scan then the value is scanned incorrectly. 

**Expected behavior**
The scanner should scan CODE_128 barcode correctly. 

 - OS: Windows 10
 - Browser: Chrome 81
- ngx-scanner: 2.0.1

Sample barcode that I need to scan.

![barcode](https://user-images.githubusercontent.com/10397713/80584267-0c23f300-8a2f-11ea-832a-167f9feac512.PNG)

**Comment by odahcam** [comment]
What's the scanned value?

**Comment by pix1289** [comment]
Hi @odahcam,
It is not scanning at all now. Earlier I had got random 6-digit number.

**Comment by odahcam** [comment]
I could scan it in here:

![image](https://user-images.githubusercontent.com/3942006/80651735-d42ba880-8a4c-11ea-97f8-94fe72b1c731.png)

Could you share a demo on StackBlitz or something?

**Comment by pix1289** [comment]
I tried scanning the barcode using my phone camera and yes it does scan correctly. 

I tried to scan via my laptop but it wouldn't scan. Attached screenshot for the same.  Although the screenshot shows, no device selected... that is coming after I enable try harder option. Even then not able to scan. 

I need to scan via laptop camera only and not through phone. 

![Capture1](https://user-images.githubusercontent.com/10397713/80676666-e6e9c000-8ad4-11ea-8afd-6387ab2dc33f.PNG)

**Comment by pix1289** [comment]
I tried scanning the barcode using my phone camera and yes it does scan correctly.

I tried to scan via my laptop but it wouldn't scan. Attached screenshot for the same. Although the screenshot shows no device selected... that is coming after I enable try harder option. Even then not able to scan.

I need to scan via laptop camera only and not through phone.
![Capture1](https://user-images.githubusercontent.com/10397713/80677194-1d740a80-8ad6-11ea-959d-7b1d29788b77.PNG)

**Comment by odahcam** [comment]
Code 128 are the worst to read I think, be sure to use a camera that does not blurs it. Other than that I don't know what to say.

**Comment by pix1289** [comment]
Did you try using your PC camera? 

I have created a rough stackblitz demo. can you please try scanning and see if the code_128 barcode gets scanned? 

https://stackblitz.com/edit/angular-v5uz5g

**Comment by odahcam** [comment]
Looks like it works:

<img width="1392" alt="Screen Shot 2020-04-30 at 18 16 47" src="https://user-images.githubusercontent.com/3942006/80760221-f2f27380-8b0e-11ea-9ccc-7a244b0d813d.png">

**Comment by pix1289** [comment]
Yeah it started working when I held the barcode horizontally... i was trying to scan it vertically earlier. 

Thank you for your help. :) 

Closing the issue.

**Comment by odahcam** [comment]
Oh it makes sense, you need to enable the try harder flag so can read vertically aligned barcodes.

**Comment by pix1289** [comment]
Hi @odahcam ,

Is there a way to show/hide camera/scanner on a user event?  I tried with css/js but I wanted to know if there were any properties through which we can achieve the same? 

Also, if the permission is given to the camera, the scanner takes some time to load. Is there a way to solve it? 

(i did not know if this was a bug or a feature... hence commenting here!)

**Comment by odahcam** [comment]
> Is there a way to show/hide camera/scanner on a user event? I tried with css/js but I wanted to know if there were any properties through which we can achieve the same?

Nope, just use CSS, it works flawlessly.

> Also, if the permission is given to the camera, the scanner takes some time to load. Is there a way to solve it?

Nope, the camera takes some time to load and then the browser takes some time to grab the video stream and put it into the DOM element, we can try optimize it more, but there's really no fix for that other than using a faster phone.

---

You can always open new issues for asking questions.

**Comment by pix1289** [comment]
Thank you @odahcam

**Comment by odahcam** [comment]
You are welcome.

**Comment by NiranjanNithin** [comment]
Hi @odahcam ,

I have tried to implement QR code functionality in angular 2+ using the zxing-scanner plugin. It is not scanning QR code 
and application running time camera will open and closing.

The console log showed an error pasted below please check it and help me to solve it.

**"zxing scanner component: TypeError TypeError: Cannot read properties of undefined"**

Implementation referred link

https://github.com/zxing-js/ngx-scanner/wiki/Getting-Started
https://github.com/zxing-js/ngx-scanner

**Comment by Mukund2900** [comment]
Still not working for code 128 for me. Is the library not supportive or what?
