### ISSUE TITLE
Setting the device does not work (iOS 12.4)

### ISSUE THREAD

**Issue by Xenoage** [zxing-js/ngx-scanner#298]
On my iOS 12.4, setting the device property has no effect.

HTML:

```
<zxing-scanner #scanner
  [formats]="['QR_CODE']"
  [(device)]="currentDevice"
  (camerasFound)="onCamerasFound($event)"
  (scanSuccess)="onCodeScanned($event)">
</zxing-scanner>
```

TypeScript:
```
currentDevice: MediaDeviceInfo;
debugMessage = "Debug mode on";
...
onCamerasFound(devices: MediaDeviceInfo[]) {
    // Select the back camera, if there is one.
    // Try to identify it using one of the following labels
    const lbls = ["rear", "back", "environment", "rück"];

    let bestDevice: MediaDeviceInfo = null;
    for (let iDevice = 0; iDevice < devices.length; iDevice++) {
      const device = devices[iDevice];
      if (device.kind == "videoinput") {
        const label = device.label.toLowerCase();
        this.debugMessage += " Found video device " + label;
        for (let iLbl = 0; iLbl < lbls.length; iLbl++) {
          if (label.includes(lbls[iLbl])) {
            this.debugMessage += " Tried to switch to " + label;
            bestDevice = device;
          }
        }
      }
    }
    if (bestDevice)
      this.currentDevice = bestDevice;
  }
```

Debug message shows, that the right device (rear camera) was chosen, but setting it has no effect, since still the front camera is active.

**Comment by odahcam** [comment]
We have a demo currently working with this exactly `device` binding so I'll take the risk to say it's probably some error in your code. Please setup a demo so I can help you debug this code.

**Comment by Xenoage** [comment]
I had the same problem with my Android phone. It seems to me, that changing the device property directly within the camerasFound-callback has no effect. Since I wanted to add a "Switch camera" button anyway, I tried this, and now it works both on Android and iPhone.

So please consider this issue as fixed for me. Thank you.

**Comment by odahcam** [comment]
You're welcome, I'm glad you found a solution.

**Comment by joshua-classen** [comment]
You wrote Since I wanted to add a "Switch camera" button anyway, allowing the user to switch between the cameras manually, I tried this, and now it works both on Android and iPhone. @Xenoage 

but you actually want to also preselect a device on startup. I am currently struggling with this. I can not set the currentDevice on startup. I can only set the correct camera after i manually chose one from a context menu. I will provide the whole code example and paste a link here.
