### ISSUE TITLE
QR Code is not recognizing

### ISSUE THREAD

**Issue by sreejithnadesan7777** [zxing-js/ngx-scanner#299]
**Describe the bug**
i was following this page https://github.com/zxing-js/ngx-scanner/wiki/Getting-Started for the integration of ngx-scanner with my angular 9 app. its bringing the camera on my mac os, but not recognizing the QRCode

Angular version 9
Node 12.11.1

**Comment by odahcam** [comment]
Please share tbe library version you're using plus the image you can't recognize.

**Comment by nomankt** [comment]
Its not recognizing the QRCode in  angular 9.1.0
