### ISSUE TITLE
Scan several barcodes one after another

### ISSUE THREAD

**Issue by sadplace** [zxing-js/ngx-scanner#301]
Hi, First let me thank you guys for this lib. Really nice.

So, i want to scan 1 barcode, then scan another, and so on without closing the scanner.
But when i implement your lib, i scan 1 barcode and the (scanSuccess) return the string...but multiple times, it does not stop returning the same string. 
Is this the intended way of working?
If yes then how can i scan another barcode without closing/disabling the scanner?

Thanks :)

**Comment by odahcam** [comment]
Take a [look here](https://stackblitz.com/edit/zxing-ngx-scanner?file=projects%2Fzxing-scanner-demo%2Fsrc%2Fapp%2Fapp.component.ts), I think it can answer all your questions. 🙂

**Comment by sadplace** [comment]
Thanks. I believe that i try the same in your example, i just added a console.log to onCodeResult and put all barcode types and i got the same thing, sometimes read only 1 barcode, other times enters in a loop.

but i will check it today or tomorrow and then i will say something here.

Thanks again :)

**Comment by odahcam** [comment]
You're welcome, let me know if there's a bug, good luck.

**Comment by sadplace** [comment]
Ok, so from what i have tested:
On the phone everything works fine.
If i test with your example on Edge on my laptop with the camera from the laptop it self then, sometimes, it gets into a loop after reading a barcode.

So it is fine for what i need.

But now when i run my tests spec i get this error:
ReferenceError: MediaDeviceInfo is not defined
Do you know what this could be?

**Comment by odahcam** [comment]
`MediaDeviceInfo` is a class that comes from the browser APIs, if you are running any tests that access this class in Node.js you will get this error. Also, jurassic/zombie/dead browsers will probably do the same.

**Comment by sadplace** [comment]
Hey, thanks for the help. All working now :D
