### ISSUE TITLE
(@zxing/ngx-scanner) which declares ZXingScannerModule has not been processed correctly by ngcc

### ISSUE THREAD

**Issue by Yash1007** [zxing-js/ngx-scanner#304]
#### Bug, feature request, or proposal:
This is not compatible with latest angular 9?

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/fork/zxing-ngx-scanner<br/>

**Comment by Yash1007** [comment]
I resolved this by setting - "enableIvy": false,

**Comment by odahcam** [comment]
The package is not entirely tested on Ivy, so I would not be surprised if it did not works with Ivy at all.
