### ISSUE TITLE
Angular 10 doesn't support

### ISSUE THREAD

**Issue by drony** [zxing-js/ngx-scanner#305]
Package "@zxing/ngx-scanner" has an incompatible peer dependency to "@angular/core" (requires "^9.0.0 <10" (extended), would install "8.2.14").
                  Package "@zxing/ngx-scanner" has an incompatible peer dependency to "@angular/common" (requires "^9.0.0 <10" (extended), would install "8.2.14").

**Comment by odahcam** [comment]
We really don't support Angular 10 yet.

**Comment by MojioMS** [comment]
Despite the warning, it works fine for me on ng10 though.

```
  "devDependencies": {
    "@angular/core": "^10.0.2",
    "@angular/common": "^10.0.2",
    "@zxing/ngx-scanner": "^3.0.0",
    ...
  },

```

**Comment by StationedInTheField** [comment]
3.0.0 works in Angular 10
