### ISSUE TITLE
Switching Off the Camera Scanner After one successful decode

### ISSUE THREAD

**Issue by IconixES** [zxing-js/ngx-scanner#308]
**Is your feature request related to a problem? Please describe.**
I am unable to find any documentation which clearly describes how I should turn off the camera after a successful decode. Currently the camera stays on an continuously decodes QR codes, however many applications just require a single decode and then switch off the camera

**Describe the solution you'd like**
I would like a document that shows me how in the angular ionic project i can switch off the camera.

**Describe alternatives you've considered**

**Additional context**

**Comment by odahcam** [comment]
On the base library for this component we do have this method available, but in here you will have to manually disable the camera (at least for now). You can set the `[enabled]` property to `false` in the component to completely disable it after a successful scan.

**Comment by IconixES** [comment]
Thanks for the feedback Luiz, can you perhaps share the syntax to set the set Enabled to false.

Appreciate your help

**Comment by IconixES** [comment]
<zxing-scanner (scanSuccess)="onCodeResult($event)"></zxing-scanner>

<section class="results" *ngIf="qrResultString">
  <zxing-scanner  [enabled]="false"></zxing-scanner>
  <div>
    <small>Result</small>
    <strong>{{ qrResultString }}</strong>
  </div>
  <button mat-icon-button (click)="clearResult()">&times;</button>
</section>


This is what i am doing but the camera still stays on

**Comment by IconixES** [comment]
"<zxing-scanner (scanSuccess)="onCodeResult($event)"></zxing-scanner>

<section class="results" *ngIf="qrResultString">
  <zxing-scanner  [Enabled]="false"></zxing-scanner>
  <div>
    <small>Result</small>
    <strong>{{ qrResultString }}</strong>
  </div>
  <button mat-icon-button (click)="clearResult()">&times;</button>
</section>"

This is the code that I use but the camera still stays on.

**Comment by IconixES** [comment]
This is the code that I have tried but it does not work

<zxing-scanner (scanSuccess)="onCodeResult($event)"></zxing-scanner>

<section class="results" *ngIf="qrResultString">
  <zxing-scanner  [enabled]="false"></zxing-scanner>
  <div>
    <small>Result</small>
    <strong>{{ qrResultString }}</strong>
  </div>
  <button mat-icon-button (click)="clearResult()">&times;</button>
</section>

**Comment by odahcam** [comment]
I see you have a method called `onCodeResult`, so set the `enabled` property from inside that method when you finally receive a decoded result. To set the `enabled` prop, first create a property in your component (`public myEnabledControl = true;`) and bind it to the prop in the HTML, like `[enabled]="myEnabledControl"`, like you would normally do for any other property manipulation.

**Comment by IconixES** [comment]
Thank you for all the help. I have resolved the issue.

**Comment by AsjadMahmood** [comment]
I am using Angular 8.2.1 and getting the error when using [enabled] property. And setting it's value to a boolean so that i can set to false when the code is read
![image](https://user-images.githubusercontent.com/38811693/85297041-b2362b80-b4bb-11ea-9da4-95e90ca7354b.png)

**Comment by IconixES** [comment]
Hi

<div *ngIf="qrResultString; then thenBlock else elseBlock">
        </div>
        <ng-template #thenBlock>
            <zxing-scanner (scanSuccess)="onCodeResult($event)" [enable]="false">
            </zxing-scanner>
        </ng-template>
        <ng-template #elseBlock>
            <zxing-scanner (scanSuccess)="onCodeResult($event)" [enable]="true">
            </zxing-scanner>
        </ng-template>
        <section class="results" *ngIf="qrResultString">
            <button mat-icon-button (click)="clearResult()">
                &times;
            </button>
        </section>
    </div>

Below if the code that I have used. The problem is that you need to use “enable” and not enabled.

Regards,
Ashveer

**Comment by AsjadMahmood** [comment]
Thanks for the quick response. It worked.

**Comment by odahcam** [comment]
This property did changed it's name between versions a few times. I'm glad you found a way to solve this and thanks for sharing, it will be useful for future users. My best regards.
