### ISSUE TITLE
Upgrade @zxing/library^0.17.0

### ISSUE THREAD

**Issue by adam-nagle-customreg** [zxing-js/ngx-scanner#310]

**Comment by odahcam** [comment]
This is probably important for you because of added PDF417 support, am I right?

**Comment by adam-nagle-customreg** [comment]
> This is probably important for you because of added PDF417 support, am I right?

Yes, thanks.  Bingo bango bongo 👍

**Comment by odahcam** [comment]
I will see if I find some time, but a PR would be very appreciated.
