### ISSUE TITLE
[possible bug?] Can't re-enable scanner

### ISSUE THREAD

**Issue by ivantpapr2018** [zxing-js/ngx-scanner#311]
**Describe the bug**
Scanner cannot be re-enabled after being disabled

**To Reproduce**
1. Disable the scanner by doing:
````typescript
scanSuccessHandler($event) {
    //  code to retrieve from database 
      if (/* $event == data in database */) {
        // do stuff
        this.scannerEnabled = false;
      } else {
        // alert, when user press OK , execute: 
        this.scannerEnabled = true
        // end of alert
        this.scannerEnabled = false;
      }
  }
````
2. When user clicks on OK button in alert, scanner should be enabled, but I think this is the bug

**Expected behavior**
Scanner should be enabled again after it got disabled

**Screenshots**
Nil

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Home 1909 64 bit
 - Browser [e.g. chrome, safari] Version 83.0.4103.97 (Official Build) (64-bit)
 - Version [e.g. 22] Nil

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Nil
 - OS: [e.g. iOS8.1] Nil
 - Browser [e.g. stock browser, safari] Nil
 - Version [e.g. 22] Nil

**Additional context**
Nil

**Comment by odahcam** [comment]
Thanks for the very well written issue, please head to #213 for more info. Thanks.
