### ISSUE TITLE
Cannot read CODE_39

### ISSUE THREAD

**Issue by ricocynthia** [zxing-js/ngx-scanner#313]
**Describe the bug**
When I attempt to scan a barcode with code 39, it is unable to read it.

**To Reproduce**
1. Attempt to scan a code 39 barcode.
2. Observe that the scanner does not scan a code 39 barcode

P.S: I tested this with a QR code and it worked right away.

**Expected behavior**
Suppose to display the SKU of the product from the barcode

**Desktop (please complete the following information):**
 - Browser: Chrome and Brave
 - Version: 1.4.0

**Comment by MattStrybis** [comment]
Still an issue. Any action steps here? 

Thanks!

**Comment by odahcam** [comment]
The latest version of this scanner does not supports Code 39 although the [latest version of the underlying library](https://github.com/zxing-js/library) supports it.

**Comment by odahcam** [comment]
Changed from bug to feature request as this is not a bug, but may be a feature request if you like/

**Comment by SouengKimmeng** [comment]
Hello sir, I also need this library to support this code 39 as well. Please

**Comment by odahcam** [comment]
There was released a version which would allow support for this code type, but it was deprecated due to several bugs found. The latest code on master branch already supports this, we just need to finish fixing the bugs with the latest source version .

**Comment by ricocynthia** [comment]
I found another scanner that supports code 39, if any of you are interested.
https://github.com/ericblade/quagga2

**Comment by odahcam** [comment]
It should support Code 39 in the latest version.
