### ISSUE TITLE
Scanner detecting more than one camera only on Chrome

### ISSUE THREAD

**Issue by rohitxsh93** [zxing-js/ngx-scanner#315]
The scanner is detecting more than one camera only in the chrome browser and the one selected by default does not render any video feed.

1. Go to the official demo website 'https://zxing-js.github.io/ngx-scanner/' on Chrome (I am currently on Version 83.0.4103.116 (Official Build) (64-bit))
2. See the list of available cameras.

**Expected behavior**
The behavior should be the same across all the browsers and the primary camera should be selected by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/17514193/87668383-9e63a980-c789-11ea-9dd4-771b1744a032.png)

**Desktop:**
 - OS: Windows 10 (HP laptop)
 - Browser : Chrome - Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by f3l1xss** [comment]
this behavior is consistent in firefox and edge, the question is how can I produce that select dropdown for camera?

**Comment by rohitxsh93** [comment]
The dropdown is available here: https://zxing-js.github.io/ngx-scanner/ . Also it must be device-dependent too as per my understanding. On further investigation, I found out it is because of MediaDeviceInfo property only, this property was returning more than one video device only in chrome, but the problem is, is there a way the select the correct one or in other terms the working one for ex. here HP IR is selected by default which doesn't work, but HP HD works perfectly fine. My device only has one webcam so ideally MediaDeviceInfo should show only one video I/O device but there seems to be some issue with chrome, though I have not tested it extensively across a lot of browsers. But I have tested it in new Edge which is based on Chromium and it returns only one camera in the list.

**Comment by f3l1xss** [comment]
I have found an easier way to choose or preselect some camera, just listen
to onCameraFound event. It will give you MediaDeviceInfo[] so just
preselect ur camera from there

**Comment by rohitxsh93** [comment]
But the camera name will differ from device to device, in that case how will we identify which one to preselect means which one is the working one?

**Comment by f3l1xss** [comment]
How can you expect browser to know which one of ur camera is working? Show
a select element and let user choose similar to the example

**Comment by rohitxsh93** [comment]
What I mean is while other browsers are detecting only one i.e. the correct one then why only Chrome is detecting more than one.

**Comment by rohitxsh93** [comment]
Anyways this issue is no longer because of the library, so I will close it now.

**Comment by f3l1xss** [comment]
I tried but was unable to produce the behavior you mentioned. I had 3
cameras and only 1 is plugged and working yet I still see 3 cameras at all
edge, firefox and chrome.

**Comment by odahcam** [comment]
> But the camera name will differ from device to device, in that case how will we identify which one to preselect means which one is the working one?

And this is why I stopped implementing "default" cameras or selfie cameras, etc. You can't handle every scenario, so it's best if the library users do. Eventually someone will come up with a solution and I will gladly receive it. For now my life demands me  more time sleeping and less time fighting cameras 😄 .
