### ISSUE TITLE
Can not set camera

### ISSUE THREAD

**Issue by DanielWojciechowski** [zxing-js/ngx-scanner#321]
I'm testing my app on Samsung S10, by default started is wide angle camera, but its quality is not enough for barcode reading, so I want to switch it to main camera (standard angle, higher resolution).

My (simplified) solution, that won't work:

template:
` <zxing-scanner [(device)]="currentDevice" (camerasFound)="onCamerasFound($event)">   </zxing-scanner>`

typescript:
``` 
currentDevice: MediaDeviceInfo = null;
...
 onCamerasFound(devices: MediaDeviceInfo[]): void {
     this.suggestedCameras = this.getSuggestedCameras(devices);
     this.currentDevice = this.suggestedCameras[0]
    }
 }
```

I've checked, that `suggestedCameras[0]` is for sure the camera that I want. But it's still starting wide angle camera.

Also I've tested, that I can change the camera after the wide angle camera is started (for example when I change it in `onScanFailure` event handler). But it takes too much time to start one camera, make first scan and then switch to other camera.

It is possible to set desired camera before starting the wrong camera? 

Side question, according to your experience:
Is there any camera naming convention? Or is there any other way, to select the best camera that is available in given device? 
I can test some most popular devices, but how to be sure, that my app will work well on all devices?

**Comment by DanielWojciechowski** [comment]
It looks like a problem with two way data binding. 
When I changed:
`[(device)]="currentDevice"` 
to:
`[device]="currentDevice"`
 it works like I expected.

**Comment by ravibhavsar** [comment]
[device]="currentDevice" does not work for me ? Is there any other workaround ?

I have `camerasFoundHandler(cameras: MediaDeviceInfo[]) {
        this.currentCamera = cameras[0] || undefined;
    }`

`      <zxing-scanner
            [device]="currentCamera" 
            (deviceChange)="onDeviceChange($event)"
            (camerasFound)="camerasFoundHandler($event)"
        ></zxing-scanner>`

**Comment by odahcam** [comment]
Glad you found a solution @DanielWojciechowski .

Sorry @ravibhavsar I cannot tell what's wrong with only this info.

**Comment by ravibhavsar** [comment]
@DanielWojciechowski, i was not aware that i had to autostart = true once i set the camera, i.e 
Typescript
`camerasFoundHandler(cameras: MediaDeviceInfo[]) { this.currentCamera = cameras[0] || undefined; this.autoStart = true}`

Template
`<zxing-scanner [device]="currentCamera" (deviceChange)="onDeviceChange($event (camerasFound)="camerasFoundHandler($event)" [autostart]="autoStart"></zxing-scanner>`.

That is picking up the camera but it's taking time as it starts with default camera and once i set new camera, it restarts.

Is there anyway to auto start with default camera ? Any example would highly appreciated

**Comment by MaelManifacier** [comment]
Same issue, I can only set the front camera if i put a setTimeout of at least 2 seconds in the onCameraFound function...

**Comment by LPastineCorebiz** [comment]
@ravibhavsar @shreya-sawardekar @MaelManifacier I'm facing the same issue here, did you find a workaround on this? Thanks!

**Comment by Nurech** [comment]
There needs to be a significant amount of delay before it's ready to accept a device. 

I store the selected device `MediaDeviceInfo ` in `localStorage ` when the user makes a selection. Afterward upon reloading the scanner, I then set the `selectedCamera$` retrieved from localStoage info.

```javascript
// User selectes device
  onDeviceSelectChange(selected: any) {
    let selectedDevice = this.availableDevices.find(e => e.deviceId === selected.target.value)
    if (selectedDevice) {
      this.store$.dispatch(ConfigurationActions.cameraSelected({payload: selectedDevice}));
    }
  }

// Previously selected device is loaded form localStorage
selectedCamera$: Observable<any> = this.store$.select(ConfStoreSelectors.selectActiveCamera).pipe(delay(3000))

  <zxing-scanner
    [torch]="torchEnabled"
    [device]="selectedCamera$ | async"
    [autostart]="true"
    (scanSuccess)="onCodeResult($event)"
    [formats]="formatsEnabled"
    [tryHarder]="tryHarder"
    (permissionResponse)="onHasPermission($event)"
    (camerasFound)="onCamerasFound($event)"
    (torchCompatible)="onTorchCompatible($event)"
  ></zxing-scanner>
```

I wasn't able to reliably remedy this with lifecycle hooks either. 

I wish the API would emit status via `@Output` when it's ready to accept changes. E.g:

```javascript
Status : ['init','rendering','ready']

  <zxing-scanner
    (status)="onStatusChange($event)"
  ></zxing-scanner>
```

I believe this happens the way API `deviceChange` EventEmitter works. If the `selectedCamera$` is set in client code before API finalizes, the event isn't fired, and MediaDevice isn't selected. However if you fire `deviceChange` event after API has been finalized, it works as intended.
