### ISSUE TITLE
Avoid setting a device during auto-start.

### ISSUE THREAD

**Issue by BryanManfrinTS** [zxing-js/ngx-scanner#326]
**Describe the bug**
When using the camera, I get an error saying: 'Avoid setting a device during auto-start.'

**To Reproduce**
1. Open a page using the camera and the <zxing-scanner> tag.

**Expected behavior**
The feedback of the camera should appear

**Desktop (please complete the following information):**
 - OS: MacOs Cataline 10.15.5
 - Browser Chrome
 - Version 84.0.4147.135

**Additional context**
According to source code, we are setting the device during auto start:
```
private autostartScanner(devices: MediaDeviceInfo[]) {

    const matcher = ({ label }) => /back|trás|rear|traseira|environment|ambiente/gi.test(label);

    // select the rear camera by default, otherwise take the last camera.
    const device = devices.find(matcher) || devices.pop();

    if (!device) {
      throw new Error('Impossible to autostart, no input devices available.');
    }

    this.device = device; // HERE!
    // @note when listening to this change, callback code will sometimes run before the previous line.
    this.deviceChange.emit(device);

    this.isAutostarting = false;
    this.autostarted.next();
  }
```
IMPORTANT: This might help you debug my issue:
I had ^3.0.0 as a package dependency. while facing the issue I was on v 3.0.1 with your latest commit.
Fixing version to 3.0.0 solved my issue.

**Comment by PadraigGalvin** [comment]
Reverting to version 3.0.0 fixed the issue for me too.

**Comment by bvassilis** [comment]
I had the same problem.
Resolved by following the demo app structure.
The demo gives nice guidelines how to efficiently load the camera.

**Comment by lsrsilva** [comment]
> * version 3.0.1
> * Windows 10 Laptop
> * Browser: Chrome 85.0.4183.102
> 
> I had the same problem.
> Resolved by following the demo app structure.
> The demo gives nice guidelines how to efficiently load the camera.

Even use only the selector i'm getting this warning and the camera is not showing. What did you do?

**Comment by gerardcastell** [comment]
Same issue. It's not displaying any video for versions 3.0.0. nor 3.0.1. Luckily, 2.0.1. version works for me. Please notify when this bug gets fixed. Thanks!

**Comment by kzay** [comment]
Same here, not working and get the same issu with 3.0.1 and Angular 10

**Comment by coffeymatt** [comment]
I've got this working via

html:
```
<zxing-scanner
          #webScanner
          *ngIf="scanning"
          [(device)]="currentDevice"
          (camerasFound)="onCamerasFound($event)"
          (scanSuccess)="webScanFoundItem($event)"
          [tryHarder]="true">        
        </zxing-scanner>
```

and in the ts code
```
  availableDevices: MediaDeviceInfo[];
  currentDevice: MediaDeviceInfo = null;

  onCamerasFound(devices: MediaDeviceInfo[]): void {
    this.availableDevices = devices;

    if (this.availableDevices && this.availableDevices.length > 0) {
      this.currentDevice = this.availableDevices[0];
    }
  }
```

**Comment by KlausHans** [comment]
Got the same issue.
@coffeymatt Your workaround works indeed, thank you. The warning appears in the console nontheless.

**Comment by odahcam** [comment]
This should be solved in the latest version.

**Comment by r3plica** [comment]
If you set the `autostart="false"` how do you start once you have set the device?

**Comment by Daveric** [comment]
> I've got this working via
> 
> html:
> 
> ```
> <zxing-scanner
>           #webScanner
>           *ngIf="scanning"
>           [(device)]="currentDevice"
>           (camerasFound)="onCamerasFound($event)"
>           (scanSuccess)="webScanFoundItem($event)"
>           [tryHarder]="true">        
>         </zxing-scanner>
> ```
> 
> and in the ts code
> 
> ```
>   availableDevices: MediaDeviceInfo[];
>   currentDevice: MediaDeviceInfo = null;
> 
>   onCamerasFound(devices: MediaDeviceInfo[]): void {
>     this.availableDevices = devices;
> 
>     if (this.availableDevices && this.availableDevices.length > 0) {
>       this.currentDevice = this.availableDevices[0];
>     }
>   }
> ```

@coffeymatt which angular and ngx package version are you using?
