### ISSUE TITLE
Only reads barcodes after toggling "TryHarder" on or off.

### ISSUE THREAD

**Issue by Derpady** [zxing-js/ngx-scanner#333]
**Describe the bug**
On both my project and the demo I've been trying to scan a simple EAN barcode. The issue I'm having is that it doesn't read the barcode until I go to the toolbar and enable "Turn on Try-Harder". Afterwards it reads the barcode without an issue. But when I turn "Try-harder" off it also reads the barcode without an issue. The same happens in my project. Is this something to do with chrome maybe?

I've tried running my code and the demo on other browsers but I get 
"Couldn't check for devices.

    This may be caused by some security error. "
On both firefox and Edge.

So to summerize: The scanner only scans my barcodes whenever "Try-harder" is first toggled on or off. 

**To Reproduce**
1. Go to https://zxing-js.github.io/ngx-scanner/
2. Try to scan this barcode 
![image](https://user-images.githubusercontent.com/37103600/93086213-b1fa9600-f68e-11ea-83e9-eb7236e6d113.png) (or any other barcode I've found on google images).
3. Enable try-harder in the menu on the top right
4. It reads it now.
5. Disable try harder in the menu.
6. It still reads it now.

**Expected behavior**
I wish to open my barcode-scanner page and instantly have it read a barcode without having to enable/disable the "Try-harder" property

**Screenshots**
This issue is replicable fully inside of the demo, I will provide screenshots when asked for them.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (Version 85.0.4183.102 (Official Build) (64-bit))
 - Version @zxing/ngx-scanner": "^3.0.1"
- Framework: Ionic 5

**Smartphone (please complete the following information):**
Haven't tested it on a smartphone yet

**Comment by capc0** [comment]
any update or workaround here?

**Comment by odahcam** [comment]
Yes there was, it was more of a demo page issue than a library one. It should be solved in the latest version, the demo isn't updated jsut yet.
