### ISSUE TITLE
On Change of formats at runtime, the scanner gets stopped

### ISSUE THREAD

**Issue by kamalkkushwahaa** [zxing-js/ngx-scanner#334]
**Describe the bug**
On Change of formats at runtime, the scanner gets closed. For the first change of format it is working but subsequent change onwards crashes the scanner.
We have implemented format selection the similar way it is available at the demo site

**To Reproduce**
**Note: The same can be reproduced at the demo site (https://zxing-js.github.io/ngx-scanner/) as well**, hence giving steps from the demo site itself...
1. Go to demo site, it starts scanning
2. Click on three dots and select barcode format
3. Select or de-select a format for the first time
4. Scanner gets refreshed
5. Open format selection again from the menu
6. Select or de-select the format again
Scanner window disappears

**Expected behavior**
Scanner should get refreshed with the latest available format.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Multiple devices
 - OS: Android
 - Browser: Stock browser

**Additional context**

**Comment by kamalkkushwahaa** [comment]
Even calling restart() on scanner didn't help

**Comment by odahcam** [comment]
I think the latest version solves this issue.
