### ISSUE TITLE
Promise not handled when device is not capable of streaming (DOMException: Could not start video source)

### ISSUE THREAD

**Issue by rafaellyra** [zxing-js/ngx-scanner#335]
**Describe the bug**
If the default selected device is not capable of streaming the Promise error is not being handled, if a device is not capable of scanning then an error should be emitted from the component.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://zxing-js.github.io/ngx-scanner/' with a device that is not capable of streaming.
2. See the error message: "DOMException: Could not start video source" 

**Expected behaviour**
The component should handle the promise error

**Screenshots**
![stream_fail](https://user-images.githubusercontent.com/868616/93665488-265e7c00-fa77-11ea-9f85-95e74602e7c9.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 85

**Comment by mnesser** [comment]
https://zxing-js.github.io/ngx-scanner/' 
does not work on Samsung Galaxy 20 Ultra / Samsung Note 10 pluss. 
`zxing scanner component: NotReadableError DOMException: Could not start video source`
( works fine on pc having webcam)

**Comment by odahcam** [comment]
> The component should handle the promise error

The component provides a way for the developer to handle it the way it wants, it's not a bug with the library, but with the demo that did not handled it.
