### ISSUE TITLE
Camera preview works on Android but not on Mac

### ISSUE THREAD

**Issue by bkarv** [zxing-js/ngx-scanner#336]
First of all thanks for the library. After scouring the internet for a solution this is one of little few around. Below is really a question. 

**Describe the bug**
Opening ngx scanner on my mac in both Safari and Chrome prompts with permission to access the camera (expected) but then there is no camera preview showing. I can see the green light that the camera is on but the screen where the component sits is blank. If I go to inspection I can see the element there.

However if I open the app on my Samsung Android phone it works as expected.

I am using Ionic 5 and Angular 9. 

**To Reproduce**
I've done a stackblitz for both straight Angular 9 project and Ionic 5 only to show how I am coding. My stackblitz wont work on  both my mac and my android, although I still get a prompt to use the camera. But I can confirm if I access the stackblitz that is on ngx-scanner github page on my android I get the camera preview.

Angular 9
Code: https://stackblitz.com/edit/ngx-scanner-angular9?file=src/app/app.component.ts
App: https://ngx-scanner-angular9.stackblitz.io/

Ionic 5 Angular 9
Code: https://stackblitz.com/edit/ionic-5-angular9-ngxscanner?file=src/app/app.component.html
App: https://ionic-5-angular9-ngxscanner.stackblitz.io/

**Expected behavior**
Camera preview should display so scan can be made.

**Screenshots**

<img width="947" alt="Screen Shot 2020-09-23 at 11 22 02 am" src="https://user-images.githubusercontent.com/10624315/93954077-22d93680-fd90-11ea-91f8-21bd0e65b751.png">

<img width="586" alt="Screen Shot 2020-09-23 at 11 04 48 am" src="https://user-images.githubusercontent.com/10624315/93952627-a7c25100-fd8c-11ea-9926-a8180b3da021.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Browser Chrome:  85.0.4183.121,  Safari: Version 13.1.1 (15609.2.9.1.2)

**Smartphone (please complete the following information):**
 - Device: Samsung s10
 - OS: Android 10
 - Browser Chrome 85.0.4183.101

**Additional context**
Is this only meant to work on Android? Or should it work for Mac and Windows?

**Love the ZXing Angular scanner? Please consider supporting our collective:
 👉  https://opencollective.com/parcel/donate **
I have already made a small contribution as this an important powerful package and if I can get this resolved will certainly make another larger one.

**Comment by bkarv** [comment]
Ok after some further testing it looks there is an issue with my webcam itself. 

However if someone could answer why in my stackblitz why I can't access the webcam via my android but i have no issues using the official stackblitz by ngx-scanner that would be much appreciated.

If no answer in next couple of days I will also self close this.

**Comment by odahcam** [comment]
It does not work on my celphone either. The only thing I saw was this:

![image](https://user-images.githubusercontent.com/3942006/96885982-858a2480-1459-11eb-90d4-82240bb7dbab.png)

**Comment by odahcam** [comment]
Should be ok in the latest version.
