### ISSUE TITLE
Micro QR formats do not scan

### ISSUE THREAD

**Issue by Recodify** [zxing-js/ngx-scanner#339]
**Is your feature request related to a problem? Please describe.**
This library works beautifully on QR model 1 and 2 but I have been unable to get it working on micro qr codes (with one locator pattern). Are these supported? Should they work? Can they be added?

**Describe the solution you'd like**
I would like it work with micro qr formats as per:
example 1:
![image](https://user-images.githubusercontent.com/5644228/94802083-edab9480-03de-11eb-9399-971795998ed4.png)

example 2:
![image](https://user-images.githubusercontent.com/5644228/94802388-79bdbc00-03df-11eb-809d-a6fa9de20f14.png)

**Comment by odahcam** [comment]
The first image is an Aztec and the second I don't know by heart, but they aren't simply QR codes, so you need to enable the right barcode formats through the `formats` property.

**Comment by Recodify** [comment]
@odahcam Thanks for the reply. Even with the formats specified as `<zxing-scanner [formats]="['QR_CODE', 'AZTEC']"` it doesn't seem to scan a number of Aztec codes that I'm trying. No errors but no scan unfortunately

**Comment by odahcam** [comment]
I could decode it using the demo: 
![image](https://user-images.githubusercontent.com/3942006/107437773-3fdb8f80-6b0e-11eb-9e4e-7ad39d5ec655.png)

Naturally it was not very easy nor fast, but it does works (I'm using Android 10 + Chrome 88).

**Comment by veerababutekumudi5-sketch** [comment]
Sorry

**Comment by ramaramjakhasar9-a11y** [comment]
> **Is your feature request related to a problem? Please describe.** This library works beautifully on QR model 1 and 2 but I have been unable to get it working on micro qr codes (with one locator pattern). Are these supported? Should they work? Can they be added?
> 
> **Describe the solution you'd like** I would like it work with micro qr formats as per: example 1: ![image](https://user-images.githubusercontent.com/5644228/94802083-edab9480-03de-11eb-9399-971795998ed4.png)
> 
> example 2: ![image](https://user-images.githubusercontent.com/5644228/94802388-79bdbc00-03df-11eb-809d-a6fa9de20f14.png)
