### ISSUE TITLE
Poor Perfermance with angular 6

### ISSUE THREAD

**Issue by smarzouki** [zxing-js/ngx-scanner#340]
the place where i work have an app developed in angular 6. We use ngx-scanner to scan some Barcode: Code 128, QRCode, DataMatrix, Code39
it takes a long time to recognize the Barcode specially DataMatrix and QRCode.
I tried an app developed by ZXing team from the Playstore. the app does not seem to be slow and it have a high recognition rate.
Is this normal that the library ngx-scanner is slow ??
what can i do the improve it ? the option tryHarder didn't make it better.

**Comment by werthdavid** [comment]
Well, a native zxing is always faster than the browser version. How long does the recognition take?

**Comment by werthdavid** [comment]
Have you tried the input-parameter "timeBetweenScans"?

**Comment by smarzouki** [comment]
Hallo @werthdavid 
the problem is that it often does not recognize the code. i use use the library to scan QR, DtaMatrix and 39 Barcodes. Often when the Picture of the Code is a litte small it does not recognize it and when i then try to scan another Codewhich is bigger, it does not recognize it. If i restart my site and scan the same big Code it recognizes it.
The Lib has always Problems with small Codes, even when i gave the zxing-Component a bigger resolution in my CSS File.
how can i modify "timeBetweenScans"?

**Comment by odahcam** [comment]
> even when i gave the zxing-Component a bigger resolution in my CSS File.

**Comment by odahcam** [comment]
> even when i gave the zxing-Component a bigger resolution in my CSS File.

This does not affects the scan at all. To be able to improve the video stream quality we need to apply some constraints to the `MediaStreamTrack`, which is an API that's not available at the moment on our libs.

> how can i modify "timeBetweenScans"

The scanner has a property called `timeBetweenScans` where you can pass custom int values and `delayBetweenScanSuccess` for changing the time delay after a scan success.
