### ISSUE TITLE
If camera already in use: AbortError: Starting video failed

### ISSUE THREAD

**Issue by KlausHans** [zxing-js/ngx-scanner#341]
**Describe the bug**
I found no way to catch the error if the camera ngx-scanner wants to access is already in use. It also appears in the ngx-scanner demo. The "scanError" handler does not fire in this case.

**To Reproduce**
1. Have a device with one camera e.g. Laptop
2. Use this camera in another programm e.g. some video chat software
3. Open the ngx-scanner demo
4. See error in console

**Expected behavior**
The scanner component offers an error handler to catch the error and inform the user properly.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9212982/95344490-ff4adb80-08b9-11eb-9d9d-5747148d00f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 81.0

**Comment by odahcam** [comment]
Nice, what's the way you found?

**Comment by bcawrse** [comment]
I'm seeing this error when running @zxing/browser from my Galaxy Note s10 phone. No issues from my laptop w/ an extra camera plugged in.

It occurs when swapping cameras within a '_group_'. I know this is ngx-scanner but adding comment as they may be related.

So if I swap from a front to back camera on the phone, all is well, if I swap from front -> front or back -> back, they share a groupId in the videoDeviceList and fail with this error.
