### ISSUE TITLE
Can't make the scanner work

### ISSUE THREAD

**Issue by harrispap03** [zxing-js/ngx-scanner#343]
Hey there.  First of all I want to make it clear that I'm a newbie.  

I've been trying to make the module work.  I even tried turning the "tryHarder" on and off and I still can't make it work.  Everytime I open the scanner page on a phone the browser asks the permissions normally but then nothing happens.  The only thing I see is an empty page with the same color I have in the rest of my app.  

Any ideas?  

Here's a link to the component: 
https://github.com/harrispap03/fieldID/tree/master/src/app/qr-scanner

**Comment by werthdavid** [comment]
Are you testing on a computer? Or mobile?

**Comment by harrispap03** [comment]
mobile, from 2 different phones

**Comment by werthdavid** [comment]
iOS or Android?
When using iOS make sure that you use Safari (any other browser is NOT supported due to Apple restrictions) and HTTPS!

**Comment by harrispap03** [comment]
> iOS or Android?
> 
> When using iOS make sure that you use Safari (any other browser is NOT supported due to Apple restrictions) and HTTPS!

Yeah, I'm using safari on iOS and chrome on android.  The thing is that I'm not even getting the camera view.  Just an empty screen.  I might have made a huge mistake in my code or something.

**Comment by werthdavid** [comment]
I will take a look into your repo when I find some time

**Comment by harrispap03** [comment]
Awesome.  Thank you very much!

**Comment by harrispap03** [comment]
Just a little update.  After you updated the library and made it fully compatible with Angular 10 I get a little border in my scanner but I still dont get a camera view
