### ISSUE TITLE
Focus box for barcode in middle portion of image

### ISSUE THREAD

**Issue by GaryHyland** [zxing-js/ngx-scanner#356]
**Is your feature request related to a problem? Please describe.**
Devices with high res cameras tend to have an image with high res and auto focus. The barcode tends to typically be focussed when at a certain range from the camera but I find that at that range the barcode only occupies a small part of the actual image then. So lots of background clutter which makes detection difficult and slow.

**Describe the solution you'd like**
Would be great to just process the middle x % (say 30%) of the image/video for barcodes.
A lot of true mobile apps will typically make the borders that are not scanned obscured ie opaque or have a scan box overlaid, so fit the barcode within the scan box. Think this, along with ability to select a higher res eg. 1024 width would significantly improve the detect.

**Describe alternatives you've considered**
I could do myself by adding overlays (z-index and opacity 0.5) around the border of the image and on scan frequency get just the reqd middle portion of the image and scan.
Could add params:
imageScanMiddlePortion = 30    - to scan just the middle 30% of the image.
Would make the scan box square I think or could even better allow for 1D codes as well by using imageScanMiddleXPortion, imageScanMiddleYPortion?
Sample display
![barcode scan](https://user-images.githubusercontent.com/39715655/97252761-b85f5e80-1845-11eb-8b7a-f195b75f7cb4.png)

**Additional context**
BTW.. this project is AWESOME.. great to see the recent activity on it. Now gotta upgrade my app to Angular 10.

**Comment by odahcam** [comment]
Until it doesn't get implemented, you could use some of the ideas in #365 as a workaround.
