### ISSUE TITLE
Camera is not turning Off

### ISSUE THREAD

**Issue by JoshuvaGeorge03** [zxing-js/ngx-scanner#358]
#### Bug:

After upgrading to 3.1.1, the Camera is not turning off if I go out of that page. The camera is not turning off even the ngOnDestroy event fired. And when switching between cameras, the previous camera I used is still on. 

Both not presented in previous versions.

#### What is the expected behavior?
The camera should turn off once the component is destroyed. And when switching between cameras, the previous camera should turn off, after the next camera should turn on.

#### What is the current behavior?
After upgrading to 3.1.1, the Camera is not turning off if I go out of that page. The camera is not turning off even the ngOnDestroy event fired. And when switching between cameras, the previous camera I used is still on. 

Both not presented in previous versions.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/fork/zxing-ngx-scanner<br/>

#### Which versions of Angular, `ngx-scanner`, OS, TypeScript, browsers are affected?

 @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.1.0
   @angular/cli                  : 10.2.0
  NodeJS : v12.18.4 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10
"@zxing/browser": "0.0.3",
    "@zxing/library": "^0.18.2",
    "@zxing/ngx-scanner": "^3.1.1",

**Comment by odahcam** [comment]
Previous versions used to kill the device's stream and reset the video element where the stream were attached to, that may be a workaround for now. It's important to notice that this behavior seems to happen only in production builds.

**Comment by JoshuvaGeorge03** [comment]
Could you please advise, how can I fix this issue?

You can automatically kill the streams before switching the camera and in ngOnDestroy. Or you can give us a method to kill the stream manually.

Please let me know the fix.

**Comment by odahcam** [comment]
Please, follow #359.
