### ISSUE TITLE
Camera doesnt turn off

### ISSUE THREAD

**Issue by mrcrixx** [zxing-js/ngx-scanner#360]
Tried in new version 3.1.1 and 3.1.2

Using angular 10.1.5 on PC, when I destroy the component with the scanner the cam keep to be active, no way to turn it off, I tried with reset(), and any other way but no luck. This didnt happen with the previous version (3.0.0).

**To Reproduce**
install an angular 10+ app, use the ngx-scanner and try to use the reset() function or any other way to turn off the cam. In my case there is no way to do it.

**Expected behavior**
when I leave the component or "onDestroy" the supposed behavior is that the cam turn off

Used on pc with chrome

**Comment by pieterdb4477** [comment]
I have the same issue and decreased the version until the bug was gone. v3.0.1 seems to be the latest version without this bug.

"@zxing/browser": "0.0.3",
"@zxing/library": "^0.18.2",
"@zxing/ngx-scanner": "3.0.1",
"@angular/xxx": "^10.2.0",

**Comment by odahcam** [comment]
Yes this is known issue and already reported, thanks guys. The versions v3.1.x are deprecated and we will stick with 3.0.x until we have good fixes for the new ones.
