### ISSUE TITLE
export declare class ZXingScannerModule

### ISSUE THREAD

**Issue by psteja96** [zxing-js/ngx-scanner#362]
Getting below error in Angular 10 project, after installation

 ERROR in node_modules/@zxing/ngx-scanner/lib/zxing-scanner.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (@zxing/ngx-scanner) which declares ZXingScannerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by odahcam** [comment]
Please, can you at least share the nix-scanner version you're using?

**Comment by MatehElismar** [comment]
@odahcam Hi, on npmjs.org, it says the version 3.1.2 is deprecated.  Is this project stil maintained? Should I use another version??

**Comment by odahcam** [comment]
You should use v3.0.x. Thanks!

**Comment by MatehElismar** [comment]
Thanks! Keep up the great work!
