### ISSUE TITLE
Firefox Android requires permissions that are not prompted for

### ISSUE THREAD

**Issue by Recodify** [zxing-js/ngx-scanner#363]
**Describe the bug**
Firefox on android requires 'Storage' and 'Camera' permissions to show the scan preview, storage is not prompted for. 
Chrome only requires Camera, which is prompted for. 

Android 10. Firefox 82.1.3

**To Reproduce**
Open the demo site in firefox on android, security error is shown until all of the above permissions are given via android, user is not prompted.

**Expected behavior**
User should be prompted for these permissions, if they are actually required or the required permissions should be tailored to just the ones that are need. I don't think these permissions should actually be required though as if I use a pure html5 camera version such as: https://makitweb.com/demo/webcam/ then storage permissions are not required.

**Screenshots**
![image](https://user-images.githubusercontent.com/5644228/98815753-8b06d900-241f-11eb-8fd6-675466500721.png)
![image](https://user-images.githubusercontent.com/5644228/98815775-935f1400-241f-11eb-9123-224a7122fb91.png)

**Smartphone (please complete the following information):**
 - Device: moto g8 power
 - OS: android 10
 - Browser firefox
 - Version 82.1.3

**Comment by odahcam** [comment]
Why does Firefox requires storage permission?
