### ISSUE TITLE
scanError event not working while scan any invalid QR code or in any invalid case

### ISSUE THREAD

**Issue by amirSohel007** [zxing-js/ngx-scanner#366]
**Describe the bug**
I want to catch error while scanning QR code, If it is invalid or if it throws any error it should catch in an event so for that i am using scanError but it is not calling anymore.

**To Reproduce**
You can scan any Invalid QR code or any other code

**Expected behavior**
 If QR code throws any error 'scanError' should call

or can someone please tell me when this scanError will trigger?

**Comment by odahcam** [comment]
`scanError` is intended to give you `Error`s which in JavaScript are kindof `Exceptions`, things that normally shouldn't happen, unexpected behaviors, etc. For catching decode attempts that failed and stuff, please use `scanFailure`: https://github.com/zxing-js/ngx-scanner/blob/42e6ad4f58fd235bd15d688d36050a4ea25fdc01/projects/zxing-scanner/src/lib/zxing-scanner.component.ts#L137-L141

You can also use `scanComplete` to catch both success and failure events and also receiving a bit more info: https://github.com/zxing-js/ngx-scanner/blob/42e6ad4f58fd235bd15d688d36050a4ea25fdc01/projects/zxing-scanner/src/lib/zxing-scanner.component.ts#L149-L153
