### ISSUE TITLE
'zxing-scanner' is not a known element

### ISSUE THREAD

**Issue by enricobenedos** [zxing-js/ngx-scanner#369]
**Describe the bug**
We started a new Angular project and we import the library using [Getting Started](https://github.com/zxing-js/ngx-scanner/wiki/Getting-Started) wiki page. 
The scanner works on our PCs (using WebCam) but there is this annoying vs code reported problem.

```
'zxing-scanner' is not a known element:
1. If 'zxing-scanner' is an Angular component, then verify that it is part of this module.
2. If 'zxing-scanner' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Expected behavior**
We expect that there are no errors reported with basic package usage

**Screenshots**
![image](https://user-images.githubusercontent.com/12233746/103276802-d40eee80-49c7-11eb-8ed2-d00b2bab6832.png)

**Desktop (please complete the following information):**
```
Angular CLI: 11.0.5
Node: 14.15.3
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

``` 

Is that an expected behavior? How can we correctly solve it?

**Comment by raptortrx** [comment]
+1 same here

**Comment by dev-ivd** [comment]
We have this issue as well. This happened after updating from 3.0.0 to 3.1.2.

**Comment by CodyAlexanderDev** [comment]
Same issue as well with 3.1.2 and Angular 11.

**Comment by odahcam** [comment]
Can you confirm the issue stills valid on v3.1.3?

**Comment by raptortrx** [comment]
@odahcam 

Hi, updated from 3.0.0 to v3.1.3, the "'zxing-scanner' is not a known element:" error is gone. On build i got a dependeny error and had to install @zxing/browser and @zxing/library, then everything worked fine. The bundle size of my angular app increased by ~300kb 😐

**Comment by odahcam** [comment]
Nice, unfortunatelly the bundle may in fact increase. We will work on that on the future.

**Comment by sovushka-utrom** [comment]
`"@zxing/ngx-scanner@^3.1.3": version "3.1.3"` & Angular 10.
Still getting this error message, even after reinstalling all 3 modules. 
Got several warnings as well.
On installing:
`ngx scanner has incorrect dependency @zxing/browser^0.0.5` (I have installed @latest as per doc)
On building:
```
WARNING in ...\node_modules\@zxing\ngx-scanner\__ivy_ngcc__\fesm2015\zxing-ngx-scanner.js depends on '@zxing/library'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
WARNING in ...\node_modules\@zxing\ngx-scanner\__ivy_ngcc__\fesm2015\zxing-ngx-scanner.js depends on '@zxing/browser'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Also, got for the first time a 'lack of memory' message on project build after integrating these libs (had to set sourceMap to false to make it work again, but that negatively affects the debugging process).

**Comment by ca-milin15** [comment]
> @odahcam
> 
> Hola, actualizado de 3.0.0 a v3.1.3, el error "'zxing-scanner' no es un elemento conocido:" desapareció. En la compilación obtuve un error de dependencia y tuve que instalar @ zxing / browser y @ zxing / library, luego todo funcionó bien. El tamaño del paquete de mi aplicación angular aumentó en ~ 300kb😐

Could you show @zxing/browser and @zxing/library, please?

**Comment by atorres16** [comment]
This happened to me because I was using Angular version 12, I updated to Angular 14 and it worked
