### ISSUE TITLE
Differents values detecting for the same barcode ngx-scanner : 3.0.0 and Angular 8

### ISSUE THREAD

**Issue by LekshmiC** [zxing-js/ngx-scanner#370]
I am trying to scan EAN 13 barcode using android and ios devices, sometimes it will give the correct numbers but most of the time giving random 10-12 digit numbers and sometimes 4-6 digit numbers.

Is there any max distance? 
How can I improve the performance :| 

https://user-images.githubusercontent.com/29917551/103346696-cdad6f00-4aba-11eb-9b37-8ae4e6ba7177.mp4

**Comment by odahcam** [comment]
The best way for improving performance is to implement your own scanner component using the @zxing/browser or even @zxing/library packages. This component is currently not very performant and you can't choose what reader to use in here.

Other option would be specifying only the barcode formats you wanna decode and use multiple scanner components one for each barcode type.
