### ISSUE TITLE
Cannot read property 'stop' of undefined

### ISSUE THREAD

**Issue by Stefku** [zxing-js/ngx-scanner#373]
With @zxingjs/ngx-scanner 3.1.2

I integrated ngx-scanner in a simple component. When I run the app locally everything is alright.
When I deploy it I get the following exception
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'stop' of undefined
TypeError: Cannot read property 'stop' of undefined

...long stacktrace. maybe interesting part:

  | listVideoInputDevices | @ | main-es2015.6a9b4c4….js:3
  | (anonymous) | @ | main-es2015.6a9b4c4….js:3
  | (anonymous) | @ | main-es2015.6a9b4c4….js:3
  | D | @ | polyfills-es2015.77f…be5d023dc27ebb.js:1
  | i | @ | main-es2015.6a9b4c4….js:3
  | updateVideoInputDevices | @ | main-es2015.6a9b4c4….js:3
  | (anonymous)


```
I debugged that and it seems that it fails here: https://github.com/zxing-js/ngx-scanner/blob/85c6d9d082af9e59bedecfdd3c36abaf740cd2fc/projects/zxing-scanner/src/lib/zxing-scanner.component.ts#L556
Very strange.
Has anybody an idea what the problem could be?

I tried on
* Mac with Safari, Chrome
* iOS with safari

PS: I use angular version 11.0.3 and I had to install ngx-scanner with --force because it needed angular version 10. Don't know if this could cause a problem on production environment.
PPS: When I build the app locally with --production and run it, I get the same error.

**Comment by Stefku** [comment]
I played around a bit with the build and found out, that disabling optimization in angular.json fix the problem.
This is just a workaround, because size of distribution increases.
I try to dive further, trying to find the root of the problem. If anybody has an idea, don't hesitate to comment.

**Comment by visurel** [comment]
Experiencing the same using Angular 10.2.1 and @zxingjs/ngx-scanner 3.1.2. Not happening in development builds or when using `ng serve`. Only for production builds. 
Usage:
```html
<zxing-scanner [autostart]="true" [(device)]="activeCamera"></zxing-scanner>
```

Reverting back to 3.0.1 fixes the issue.

**Comment by Stefku** [comment]
I also reverted to 3.0.1.

**Comment by Giorgio-gatti** [comment]
same here.

**Comment by odahcam** [comment]
> With @zxingjs/ngx-scanner 3.1.2

This is deprecated.
