### ISSUE TITLE
Angular 11 Compatibility

### ISSUE THREAD

**Issue by iamoku** [zxing-js/ngx-scanner#374]
I am trying to add the scanner to a new app built that is using angular 11 but npm has an error because it's requesting the @angular/common@"^10.1.5

Is it possible to upgrade it?

Thanks a lot,

Mauro

**Comment by odahcam** [comment]
Update to the latest version, you're welcome.

**Comment by pwqw** [comment]
Support Angular 11 is needed because ionic 5 only works with angular 11.
