### ISSUE TITLE
Browser does not stop camera mode

### ISSUE THREAD

**Issue by Stefku** [zxing-js/ngx-scanner#377]
With @zxingjs/ngx-scanner 3.1.2

The tab of the browser still shows camera in use, even when stop scanning.

I tried a lot of thing from task #267 inclusive debugging and calling MediaStreamTrack.stop(). My guess is, that MediaStreamTracks has been cloned and not stopped. But I could not find out while debugging.

I reverted to 3.0.1.

**Comment by odahcam** [comment]
> With @zxingjs/ngx-scanner 3.1.2

This version is deprecated due to big amout of errors when running with Ivy.
