### ISSUE TITLE
Updating to angular 11 make it stop working on some devices

### ISSUE THREAD

**Issue by jakubpeksa** [zxing-js/ngx-scanner#380]
After updating to angular 11 with newest 3.13 ngx-scanner it stopped working, it detects devices (4 cameras) but video tag is not displaying anything.

That's happening on newest chrome on samsung s20, any chance I could get a working example with angular 11? 
Those demos are on 10 and 7

**Comment by pfeigl** [comment]
Having the same problem. Does not work on Angular 11. Demos (stackblitz) do work, but those are on Angular 7.

Also tried the native zxing-js library without the angular wrapper and that seems to work. So it really seems to be a problem with ngx-scanner.

**Comment by pfeigl** [comment]
Was just about fixing the problem but it actually worked in the sample application.

I think the reason for this is, that in the current master, ivy is disabled. This is the corresponding commit:
https://github.com/zxing-js/ngx-scanner/commit/71e397e69e24f1dff63b4af50862a0cfcf900dd8

So I guess, (while updating angular to 11.2 would also be nice) - what is actually needed is only a push of the latest version to npm, because 3.1.3 was just but the ivy change.

**Comment by rulaman123** [comment]
I have newest Angular 11.2.1 and the camera is working with this scanner. But don't scan anything. No QR or Ean Codes. Nothing. Is this a bug with the newest Angular Version? Or did i do something else wrong?

**Comment by odahcam** [comment]
What you mean? The latest version already is on NPM. Angular libraries cannot be published with Ivy enabled anymore. Are you saying that for version 11 Ivy should be enabled?

**Comment by pfeigl** [comment]
![image](https://user-images.githubusercontent.com/237891/109232626-dffd0e00-77c8-11eb-924d-ab0ef8bb4c01.png)
This gave me the impression, that the disable of ivy is actually missing in `3.1.3`

**Comment by payamss** [comment]
same error on angular 11.1.1
![image](https://user-images.githubusercontent.com/6679765/109416586-63d71600-79d4-11eb-8ed7-3df2cbba5399.png)

**Comment by jakubpeksa** [comment]
up

**Comment by C0ZEN** [comment]
@AurelienLoyer

**Comment by mrazvanalex** [comment]
The problem is that Angular 11 is now using Typescript 4 only.  The whole codebase needs an update to Typescript 4 and Dependencies bumped to Angular 11.x

**Comment by fabiolooo** [comment]
same Problem here with Angular 11:
`zxing scanner component: TypeError TypeError: Cannot read property 'stop' of undefined`

**Comment by JoshuvaGeorge03** [comment]
same problem

**Comment by obikanubi** [comment]
got it to work with angular 11 by installing:

"@zxing/browser": "0.0.5",
"@zxing/library": "^0.18.3"
"@zxing/ngx-scanner": "^3.1.3",

**Comment by Jonbeckas** [comment]
i create a pull request to update to Angular 11. #398

**Comment by pwqw** [comment]
Angular 11 support is a necessity.

**Comment by pwqw** [comment]
**Angular 11 support is a necessity.**

> got it to work with angular 11 by installing:
> 
> "@zxing/browser": "0.0.5",
> "@zxing/library": "^0.18.3"
> "@zxing/ngx-scanner": "^3.1.3",

wont work for me.

**Comment by lookMyCode** [comment]
> got it to work with angular 11 by installing:
> 
> "@zxing/browser": "0.0.5",
> "@zxing/library": "^0.18.3"
> "@zxing/ngx-scanner": "^3.1.3",

It work, thank you!
Angular 12

**Comment by mazero** [comment]
Not for me with Angular 12.0.1 and  
"@zxing/browser": "^0.0.9",
    "@zxing/library": "^0.18.6",

**Comment by lookMyCode** [comment]
> Not for me with Angular 12.0.1 and
> "@zxing/browser": "^0.0.9",
> "@zxing/library": "^0.18.6",



> Not for me with Angular 12.0.1 and
> "@zxing/browser": "^0.0.9",
> "@zxing/library": "^0.18.6",

I made this steps:
1. Deleted forder `node_modules`
2. In file `package.json` in `dependencies` replaced versions:
- `"@zxing/browser": "0.0.5",`
- `"@zxing/library": "^0.18.3",`
- `"@zxing/ngx-scanner": "^3.1.3",`

You have another versions.

It was test in Angular versions: 9.1.4 and 12.0.5

![image](https://user-images.githubusercontent.com/46138135/130196853-d89d343b-e668-47a1-a2eb-9aa1cfc84ea8.png)

**Comment by payamss** [comment]
what about angular 13.0.3

**Comment by AreyXo** [comment]
![image](https://user-images.githubusercontent.com/28868973/152107981-4ef9fd2c-78ba-4b06-a06f-2baabe3ff046.png)
It solved it for Angular 13 as well.
