### ISSUE TITLE
Scans to slow/takes several attempts

### ISSUE THREAD

**Issue by rulaman123** [zxing-js/ngx-scanner#381]
Hi. I build an mobile app with Ionic (Angular 11.2).
But the scanner fails to scan on some Ean 13 codes or it takes several attempts. If i scan codes from my PC screen instead of a book or stuff like that its working fine.
What's the problem? 

Edit: ok i see #340 have the same problem

**Comment by kubalakowski** [comment]
What helped me was version downgrade. I've upgraded for a while to 3.2.0 and started to have issues similar to yours. After few hours of tweaking with configuration I gave up and reverted to 3.0.0. Now it scans in a blink of an eye.
