### ISSUE TITLE
QR not scanable if x and y modules are swapped

### ISSUE THREAD

**Issue by FelixBurkhard** [zxing-js/ngx-scanner#383]
**Is your feature request related to a problem? Please describe.**
I am working on a project where we use [qrCode-svg](https://github.com/papnkukn/qrcode-svg) to create a QR Code which we later scan again thanks to this great project. Unfortunatly I was not able to scan the created QR Code with ngx-scanner while it there were not problems with other scanners. After a while I figured out that I needed to set the swap [option](https://github.com/papnkukn/qrcode-svg#options). I am not sure what excatly it does since I am not really familiar with QR Codes but it looks like it just mirrors the the code along an axis from top left to bottom right.

**Describe the solution you'd like**
It would be best if ngx-scanner were able to read the QR Code independent of the x-y modules.

**Describe alternatives you've considered**
 As a 'quickfix' I propose you could add this information to the limitations of the wiki so its easy to find.

**Additional context**

This is not scanable:
![notWorking](https://user-images.githubusercontent.com/38423129/110325371-8cd05a00-8017-11eb-81ec-865d4ca8a5c5.png)
This is scanable:
![works](https://user-images.githubusercontent.com/38423129/110325374-8d68f080-8017-11eb-855f-ea84d68c2751.png)

**Comment by pandiyaavps** [comment]
I am also same problem while using QR Code Styling to generate QR

**Comment by odahcam** [comment]
Hello! It should not be a limitation at all, we are actually facing some instability in the QR code and PDF417 readers in which I gonna work in the next weeks. Thanks for getting in touch guys.
