### ISSUE TITLE
Bump npm to 6.x

### ISSUE THREAD

**Issue by amoscatelli** [zxing-js/ngx-scanner#386]
**Is your feature request related to a problem? Please describe.**
Please bump to last npm version (I believe 6.x or greater) to have "lockfileVersion": 2 in packagelock and support for peer dependencies

If you don't, any project with recent npm version will have to use --force flag to install your library due to this error :

PS C:\Users\amoscatelli\Documents\Visual Studio Code\optoplus-view> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: optoplus-view@1.0.8
npm ERR! Found: @angular/common@11.2.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"11.2.1" from the root project
npm ERR!   peer @angular/common@"11.2.1" from ngx-visiontech-material@0.2.218
npm ERR!   node_modules/ngx-visiontech-material
npm ERR!     ngx-visiontech-material@"0.2.218" from the root project
npm ERR!   10 more (@angular-material-components/datetime-picker, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! node_modules/@zxing/ngx-scanner
npm ERR!   @zxing/ngx-scanner@"3.1.3" from the root project
npm ERR!   peer @zxing/ngx-scanner@"3.1.3" from ngx-visiontech-material@0.2.218
npm ERR!   node_modules/ngx-visiontech-material
npm ERR!     ngx-visiontech-material@"0.2.218" from the root project

Thank you in advance

**Comment by PadraigGalvin** [comment]
I believe this is fixed by https://github.com/zxing-js/ngx-scanner/pull/398.
