### ISSUE TITLE
Angular 12 support

### ISSUE THREAD

**Issue by dbrils** [zxing-js/ngx-scanner#406]
**Describe the bug**
When attempting to upgrade my Angular 11 solution to Angular 12 with `ng update @angular/core@12 @angular/cli@12` I get presented the following error:

![image](https://user-images.githubusercontent.com/28647803/119819238-71773b80-bef0-11eb-80f9-981a8d74e27c.png)

**To Reproduce**
1. Have an Angular `11.2.14` solution with the following packages installed:
```json

    "@zxing/browser": "0.0.9",
    "@zxing/library": "^0.18.5",
    "@zxing/ngx-scanner": "^3.1.3",
```
2. Attempt to upgrade to Angular 12 with `ng update @angular/core@12 @angular/cli@12`.

**Expected behavior**
I expect the most recent version of this package to be compatible with Angular 12. If I force the update to Angular 12 and attempt to use the plugin I get the following error:
```
onScanError TypeError: Cannot read property 'stop' of undefined
    at zxing-ngx-scanner.js:56
    at loop (BrowserCodeReader.js:1108)
    at BrowserMultiFormatContinuousReader.push.77461.BrowserCodeReader.scan (BrowserCodeReader.js:1125)
    at BrowserMultiFormatContinuousReader.<anonymous> (BrowserCodeReader.js:705)
    at step (BrowserCodeReader.js:43)
    at Object.next (BrowserCodeReader.js:24)
    at fulfilled (BrowserCodeReader.js:15)
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28667)
    at ZoneDelegate.invoke (zone.js:371)
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by wesself** [comment]
Experiencing the same issues, had to put my Angular upgrade on hold due to this package dependency.

**Comment by chronikum** [comment]
Same for me.

**Comment by kevintroko** [comment]
I have the same experience

**Comment by lidi** [comment]
bump

**Comment by darvids0n** [comment]
Has this release been pushed to npm? I can't install it :(

**Comment by werthdavid** [comment]
Latest should be 3.2.0
What problems do you have?

**Comment by darvids0n** [comment]
> Latest should be 3.2.0
> What problems do you have?

Per this issue, incompatible peer dependency with angular 11.x when trying to upgrade to 12.x
It looks like the 3.2.1 release was the first to have Angular 12 support

I've rolled my project back to Angular 11 in order to maintain compatibility for now

**Comment by shabnamahmed** [comment]
why ngx-scanner is not working when try to access from private network

**Comment by werthdavid** [comment]
> why ngx-scanner is not working when try to access from private network

What do you mean with private network? Make sure you run the App with HTTPS to be sure there are no issues (iOS requires HTTPS for accessing webcam)
