### ISSUE TITLE
Doesnt work with angular version above 12.0.4 

### ISSUE THREAD

**Issue by martijnhiemstra** [zxing-js/ngx-scanner#432]
I installed the latest angular version namely version 12.2.8. I then get this error:

npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"~12.2.8" from the root project
npm ERR!     peer @angular/common@"^11.2.11 || ^12.0.4" from @zxing/ngx-scanner@3.2.0

**Comment by rvalitov** [comment]
I use Angular 12.2.9. It works. Perhaps this may help you: https://github.com/zxing-js/ngx-scanner/issues/428#issuecomment-937800191
