### ISSUE TITLE
BrowserMultiFormatContinuousReader.releaseAllStreams is not a function

### ISSUE THREAD

**Issue by ydamato** [zxing-js/ngx-scanner#450]
**Describe the bug**
On last version (3.3.0), an error occurs when trying to scan a QR code.
BrowserMultiFormatContinuousReader.releaseAllStreams is not a function.

Issue is triggered in OnDestroy
https://github.com/zxing-js/ngx-scanner/blob/master/projects/zxing-scanner/src/lib/zxing-scanner.component.ts#L543

The problem is that the function is called on an Class (shouldn't it be on an instance of this class?) which doesn't contain this function.
https://github.com/zxing-js/ngx-scanner/blob/master/projects/zxing-scanner/src/lib/browser-multi-format-continuous-reader.ts

**To Reproduce**
1. Try to scan a QR code

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 93.0.4577.82

**Comment by PierreLucB** [comment]
I've the same error, when I want to destroy the component.

**Comment by artursoareshsv** [comment]
Same error in my app too.

**Comment by pette9** [comment]
@PierreLucB @artursoareshsv @ydamato. This function is available in the browser module 0.0.10 or higher. It was not available in the previous versions. So make sure you have ` "@zxing/browser": "0.0.10"` in your `package.json`.

**Comment by ydamato** [comment]
Thank you @pette9, it's working fine now with `"@zxing/browser": "0.0.10"`
