### ISSUE TITLE
ReferenceError: navigator is not defined at new NgxZxingComponent

### ISSUE THREAD

**Issue by odahcam** [zxing-js/ngx-scanner#46]
Some node applications may throw this exception when rendering in server-side.

I think that by just checking if the navigator is defined on the component's constructor should be enough to kill this issue.

**Comment by odahcam** [comment]
I think that https://github.com/werthdavid/ngx-scanner/commit/172561ecc6efb57eb29ef3436b695bda3fe689ed should do the trick. I could not test it yet, my current environment is based on the angular-universal-starter template.

**Comment by odahcam** [comment]
I noticed that this was breaking some SSR, also this could be an error with my polyfills.

**Comment by csutorasr** [comment]
Try [this](https://angular.io/api/common/isPlatformBrowser). If it is a browser do not load anything.

E. g. [this line](https://github.com/zxing-js/ngx-scanner/blob/e246632b41c0fdb7ada6880e10ab7caf277b649e/src/app/modules/zxing-scanner/zxing-scanner.component.ts#L31) should be moved to the ctor.

**Comment by odahcam** [comment]
> E. g. this line should be moved to the ctor.
Agreed.

I could reduce that behavior by checking `typeof navigator` before using it, but it stills buggy sometimes.

**Comment by csutorasr** [comment]
The first link helps how to realize if it is a browser. You don't need the navigator object for that. (`navigator` may be tree-shaken and the build will remove it during AOT build.)

**Comment by odahcam** [comment]
I've implemented that in a new branch, but I couldn't test it in server-side yet.

**Comment by odahcam** [comment]
Fixed in #78.
