### ISSUE TITLE
with zxing plugin camera is starting but QR code scan is not happening

### ISSUE THREAD

**Issue by TCS-BHAVESH** [zxing-js/ngx-scanner#480]
https://stackblitz.com/edit/angular-qr-reader?file=app%2Fapp.component.ts

By using the above URL, the camera is opening on mobile but the QR code scan is not working.

Guidance to resolve the above issue will be appreciable.

**Comment by Sanch9s** [comment]
Hi, why are you trying to subscribe explicitly to component events?
The first major problem I see that in `ngOnInit()` hook you don't have component available yet, so you must see errors in the console - something like `Cannot read property scanSuccess of undefined`.
The second problem, well, that is not really a problem, but you should use component outputs to receive events you are subscribing on.

**Comment by TCS-BHAVESH** [comment]
@Sanch9s can you share any working example for the same? that will be helpful.

my requirement is very simple, open the camera & read the QR code, fetch the output from same.

**Comment by TCS-BHAVESH** [comment]
I resolve the issue
