### ISSUE TITLE
This Package is Broken

### ISSUE THREAD

**Issue by everton-auth** [zxing-js/ngx-scanner#497]
After reinstalling my project's dependencies, while i serve my Angular application that's error occurred

![image](https://user-images.githubusercontent.com/78753257/203567364-ba194692-bb1e-401c-a88e-a9f9b34b7588.png)

See the dependencies (package.json):

 "dependencies": {
    "@angular/animations": "^14.2.1",
    "@angular/cdk": "^14.2.1",
    "@angular/common": "^14.2.1",
    "@angular/compiler": "^14.2.1",
    "@angular/core": "^14.2.1",
    "@angular/flex-layout": "^14.0.0-beta.40",
    "@angular/forms": "^14.2.1",
    "@angular/material": "^14.2.1",
    "@angular/platform-browser": "^14.2.1",
    "@angular/platform-browser-dynamic": "^14.2.1",
    "@angular/router": "^14.2.1",
    "@angular/service-worker": "^14.2.1",
    "@meddv/ngx-pinch-zoom": "^14.0.0",
    "@ngrx/effects": "^14.3.2",
    "@ngrx/entity": "^14.3.2",
    "@ngrx/router-store": "^14.3.2",
    "@ngrx/store": "^14.3.2",
    "@types/node": "^18.7.15",
    "@zxing/browser": "^0.1.1",
    "@zxing/library": "^0.19.1",
    "@zxing/ngx-scanner": "^3.8.0",
    "material-icons": "^1.11.5",
    "ngx-webstorage": "^10.0.1",
    "rxjs": "^7.5.7",
    "tslib": "^2.4.0",
    "zone.js": "^0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.2",
    "@angular/cli": "^14.2.2",
    "@angular/compiler-cli": "^14.2.1",
    "@types/jasmine": "~3.8.0",
    "@typescript-eslint/eslint-plugin": "^5.28.0",
    "@typescript-eslint/parser": "^5.28.0",
    "browser-sync": "^2.27.10",
    "eslint": "^8.17.0",
    "eslint-config-google": "^0.14.0",
    "jasmine-core": "~3.8.0",
    "karma": "^6.4.0",
    "karma-chrome-launcher": "^3.1.1",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "^4.0.2",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "^4.8.4"
  }

**Comment by bdtkevin** [comment]
Hi, I have exactly the same problem on my project after the updated of angular 14 (14.2.12 currently).
Do you know how fix that ? It's really critical for my projet, impossible for us the deploy our application.

concerned dependencies -
    "@angular/cdk": "^14.2.7",
    "@angular/common": "^14.2.12",
    "@angular/compiler": "^14.2.12",
    "@angular/core": "^14.2.12",
    "@angular/flex-layout": "^14.0.0-beta.41",
    "@angular/cli": "^14.2.10", (devDependencies)
    "@angular/compiler-cli": "^14.2.12", (devDependencies)
    
    "@zxing/browser": "^0.1.1",
    "@zxing/library": "^0.19.1",
    "@zxing/ngx-scanner": "^3.6.2"
    
    Regards,

**Comment by bdtkevin** [comment]
> if i remove the last property at line 305, it's works
> 
> Doesn't work: ![image](https://user-images.githubusercontent.com/78753257/203636796-8b672240-6eb9-41a6-b790-b4362e0b8391.png)
> 
> Working: ![image](https://user-images.githubusercontent.com/78753257/203637162-8a1a65e4-eac3-4acf-be64-8f5085140433.png)

We had the same problem on our application and fixed it by removing version 3.8.0 of the package which is made for angular 15 and installing version 3.6.2 (latest version for angular 14)

Regard,

**Comment by everton-auth** [comment]
> > if i remove the last property at line 305, it's works
> > Doesn't work: ![image](https://user-images.githubusercontent.com/78753257/203636796-8b672240-6eb9-41a6-b790-b4362e0b8391.png)
> > Working: ![image](https://user-images.githubusercontent.com/78753257/203637162-8a1a65e4-eac3-4acf-be64-8f5085140433.png)
> 
> We had the same problem on our application and fixed it by removing version 3.8.0 of the package which is made for angular 15 and installing version 3.6.2 (latest version for angular 14)
> 
> Regard,

It works!
