### ISSUE TITLE
Error when using zxing with angular 15

### ISSUE THREAD

**Issue by matpie33** [zxing-js/ngx-scanner#515]
Error: node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:305:91 - error TS2344: Type '{ autofocusEnabled: { alias: "autofocusEnabled"; required: false; }; timeBetweenScans: { alias: "timeBetweenScans"; required: f
alse; }; delayBetweenScanSuccess: { alias: "delayBetweenScanSuccess"; required: false; }; ... 7 more ...; tryHarder: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"autofocusEnabled"' is incompatible with index signature.
    Type '{ alias: "autofocusEnabled"; required: false; }' is not assignable to type 'string'.
"@zxing/ngx-scanner": "^3.9.1",
 "@angular/compiler-cli": "^15.1.0",

**Comment by matpie33** [comment]
The error is in line    static ɵcmp: i0.ɵɵComponentDeclaration<ZXingScannerComponent, "zxing-scanner", never, { "autofocusEnabled": { "alias": "autofocusEnabled"; "required": false; }; "timeBetweenScans": { "alias": "timeBetweenScans"; "required": false; }; "delayBetweenScanSuccess": { "alias": "delayBetweenScanSuccess"; "required": false; }; "autostart": { "alias": "autostart"; "required": false; }; "previewFitMode": { "alias": "previewFitMode"; "required": false; }; "device": { "alias": "device"; "required": false; }; "formats": { "alias": "formats"; "required": false; }; "videoConstraints": { "alias": "videoConstraints"; "required": false; }; "torch": { "alias": "torch"; "required": false; }; "enable": { "alias": "enable"; "required": false; }; "tryHarder": { "alias": "tryHarder"; "required": false; }; }, { "autostarted": "autostarted"; "autostarting": "autostarting"; "torchCompatible": "torchCompatible"; "scanSuccess": "scanSuccess"; "scanFailure": "scanFailure"; "scanError": "scanError"; "scanComplete": "scanComplete"; "camerasFound": "camerasFound"; "camerasNotFound": "camerasNotFound"; "permissionResponse": "permissionResponse"; "hasDevices": "hasDevices"; "deviceChange": "deviceChange"; }, never, never, false, never>;


I think there is conflict with angular core:
 export declare type ɵɵComponentDeclaration<T, Selector extends String, ExportAs extends string[], **InputMap extends {
    [key: string]: string;**
}, OutputMap extends {
    [key: string]: string;
}, QueryFields extends string[], NgContentSelectors extends string[], IsStandalone extends boolean = false, HostDirectives = never> = unknown;

What is the proper angular version for zxing 3.9.1?

**Comment by werthdavid** [comment]
Angular 16. Use 3.9.0 für 15. But actually 3.9.1 should work with 15 as well..

**Comment by matpie33** [comment]
Confirmed, upgrading to angular 16.0.1 fixed the problem for me.
