### ISSUE TITLE
Problems with Angular 15 and 3.9.1

### ISSUE THREAD

**Issue by TTParticipant** [zxing-js/ngx-scanner#521]
After running npm install and ng serve 
the error im getting is:

node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:305:91 - error TS2344: Type '{ autofocusEnabled: { alias: "autofocusEnabled"; required: false; }; timeBetweenScans: { alias: "timeBetweenScans"; required: false; }; delayBetweenScanSuccess: { alias: "delayBetweenScanSuccess"; required: false; }; ... 7 more ...; tryHarder: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"autofocusEnabled"' is incompatible with index signature.
    Type '{ alias: "autofocusEnabled"; required: false; }' is not assignable to type 'string'.

305     static ɵcmp: i0.ɵɵComponentDeclaration<ZXingScannerComponent, "zxing-scanner", never, { "autofocusEnabled": { "alias": "autofocusEnabled"; "required": false; }; "timeBetweenScans": { "alias": "timeBetweenScans"; "required": false; }; "delayBetweenScanSuccess": { "alias": "delayBetweenScanSuccess"; "required": false; }; "autostart": { "alias": "autostart"; "required": false; }; "previewFitMode": { "alias": "previewFitMode"; "required": false; }; "device": { "alias": "device"; "required": false; }; "formats": { "alias": "formats"; "required": false; }; "videoConstraints": { "alias": "videoConstraints"; "required": false; }; "torch": { "alias": "torch"; "required": false; }; "enable": { "alias": "enable"; "required": false; }; "tryHarder": { "alias": "tryHarder"; "required": false; }; }, { "autostarted": "autostarted"; "autostarting": "autostarting"; "torchCompatible": "torchCompatible"; "scanSuccess": "scanSuccess"; "scanFailure": "scanFailure"; "scanError": "scanError"; "scanComplete": "scanComplete"; "camerasFound": "camerasFound"; "camerasNotFound": "camerasNotFound"; "permissionResponse": "permissionResponse"; "hasDevices": "hasDevices"; "deviceChange": "deviceChange"; }, never, never, false, never>;

this can be fixed by making some changes to the static variable but has to be done by everyone, it also runs on a build server which makes this not very practicable.

im running the versions:
"@zxing/browser": "0.1.3",
    "@zxing/library": "^0.20.0",
    "@zxing/ngx-scanner": "^3.9.1",
on angular 15.2.9
   I also tried 3.8.0 but the same thing happens when u run "npm install" it just rewrites the component to the variable which throws this error.

**Comment by werthdavid** [comment]
Please try "3.9.0" (without ^)

**Comment by TTParticipant** [comment]
This fixed my problem. Thank you for the quick response!
