### ISSUE TITLE
Read barcode numbers (not scan)

### ISSUE THREAD

**Issue by umeshshende** [zxing-js/ngx-scanner#527]
I want to know does ngx-scanner support to read manually entered barcodes numbers and display result,

**Comment by werthdavid** [comment]
The component doesn't display anything at all. It only outputs the scanned result. If you want to somehow display the numbers you have to do that in your App anyways.

**Comment by umeshshende** [comment]
Okay, it means ngx-scanner only scan the image not the manually entered barcodes numbers?

**Comment by werthdavid** [comment]
Yes
