### ISSUE TITLE
 Property '"autofocusEnabled"' is incompatible with index signature.

### ISSUE THREAD

**Issue by sayeedmohammad** [zxing-js/ngx-scanner#536]
getting below error after setting up:

Error: node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:309:91 - error TS2344: Type '{ autofocusEnabled: { alias: "autofocusEnabled"; required: false; }; timeBetweenScans: { alias: "timeBetweenScans"; required: false; }; delayBetweenScanSuccess: { alias: "delayBetweenScanSuccess"; required: false; }; ... 8 more ...; tryHarder: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"autofocusEnabled"' is incompatible with index signature.
    Type '{ alias: "autofocusEnabled"; required: false; }' is not assignable to type 'string'.

309  

**Package Version:**
"@zxing/browser": "^0.1.4",
 "@zxing/library": "^0.20.0",
 "@zxing/ngx-scanner": "^16.1.0",

**Angular Version**
 "@angular/cli": "~15.2.5",

**Comment by werthdavid** [comment]
For angular 15 use ngx-scanner 3.9.0 (not 3.9.1!)

**Comment by sayeedmohammad** [comment]
> For angular 15 use ngx-scanner 3.9.0 (not 3.9.1!)

Thanks @werthdavid , it works :)

**Comment by RogierVC** [comment]
`npm i @zxing/ngx-scanner@3.9.0` produces the following error (Angular: 15.2.10):

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: app@5.19.1
npm error Found: @zxing/library@0.21.3
npm error node_modules/@zxing/library
npm error   peer @zxing/library@"^0.21.0" from @zxing/browser@0.1.5
npm error   node_modules/@zxing/browser
npm error     peer @zxing/browser@"^0.1.3" from @zxing/ngx-scanner@3.9.0
npm error     node_modules/@zxing/ngx-scanner
npm error       @zxing/ngx-scanner@"3.9.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @zxing/library@"^0.20.0" from @zxing/ngx-scanner@3.9.0
npm error node_modules/@zxing/ngx-scanner
npm error   @zxing/ngx-scanner@"3.9.0" from the root project
...
```
