### ISSUE TITLE
when you open a scanner multiple times the CPU usage gets to 100%

### ISSUE THREAD

**Issue by mehrzadrezvani** [zxing-js/ngx-scanner#551]
when you are using ngx-scanner component and open the scanner component multiple times it doesn't free up CPU usage and turns into a CPU leakage problem

**Comment by mehrzadrezvani** [comment]
this issue resolved in [this pull request](https://github.com/zxing-js/ngx-scanner/pull/550)

**Comment by werthdavid** [comment]
Thanks for the PR! Please test with 17.0.1

**Comment by mehrzadrezvani** [comment]
thanks, it is fixed in this release
