### ISSUE TITLE
Turn on flashlight

### ISSUE THREAD

**Issue by csutorasr** [zxing-js/ngx-scanner#58]
The feature request is about to having the ability to turn on the flashlight on mobile devices.

According to [this post](https://stackoverflow.com/questions/37848494/is-it-possible-to-control-the-camera-light-on-a-phone-via-a-website) the stream is needed which is [private](https://github.com/zxing-js/ngx-scanner/blob/e0f1e517718bb60ff84713a2dcc70f053827e623/src/app/modules/zxing-scanner/browser-code-reader.ts#L62) at the moment, so we need a function to be able to set the state of the flashlight.

[This function](https://github.com/zxing-js/ngx-scanner/blob/e0f1e517718bb60ff84713a2dcc70f053827e623/src/app/modules/zxing-scanner/browser-code-reader.ts#L114) should be modified. Then the data should be binded to the component.

Is PR accepted on develop branch?

**Comment by csutorasr** [comment]
Sorry, as stream is being saved, only a new function is needed called setTorch. It should contain the code to set the torch on and off.

It would be better, if the startDecode function would be separated into private parts like bindSrc, bindEvents, checkTorchCombatibility (as it is needed to be checked once). A property could be saved to show torch compatibility.

setTorch checks if torch can be activated through the variable and sets on/off it.

Maybe instead of a variable an event would be better, as from the component it is easier to bind values to events.

**Comment by odahcam** [comment]
> Sorry, as stream is being saved, only a new function is needed called setTorch. It should contain the code to set the torch on and off.

I like that.

> I would add it into the scanner, as it is really a workaround to set/get values of components in Angular. A compontent should not be modified from outside.

I did not remember very well how their logic is separated, sorry, I gotta take a look again to see what insights I will have. xD

I work with a lot of things at the same, so sorry if I misundertood.

**Comment by odahcam** [comment]
Closing as merged.
