### ISSUE TITLE
Remove `cssClass` attribute

### ISSUE THREAD

**Issue by odahcam** [zxing-js/ngx-scanner#60]
As said in: https://github.com/zxing-js/ngx-scanner/issues/55#issuecomment-378918988
...And confirmed in: https://github.com/zxing-js/ngx-scanner/issues/55#issuecomment-379035505

The attribute will be removed from `zxing-scanner` component.

We have to add docs to explain how to style the inner elements without the class and with `::ng-deep` virtual shadow piercing.

**Comment by csutorasr** [comment]
Please DO NOT do that. ::ng-deep is [deprecated](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep).

Use max-width attribute instead or something like that.

**Comment by csutorasr** [comment]
Yes it must be removed. I posted some parts at the wrong issue. I add a stackblitz to the other issue.

**Comment by werthdavid** [comment]
@csutorasr thanks for the example, looks very clean in deed.
I'd suggest to go with this solution, I think we're making our life harder by introducing more Inputs.
If somebody doesn't understand how to properly use that syntax he can still (for now) use the hacky `/deep/` workaround but I don't like the idea of more complexity with Inputs just b/c some people might not understand it
