### ISSUE TITLE
Support of full-screen mode on iOS

### ISSUE THREAD

**Issue by andrewyan** [zxing-js/ngx-scanner#66]
Hi, I'd like to know if there's a possibility of supporting
`<meta name="apple-mobile-web-app-capable" content="yes">` on iOS devices? The preview video stopped working on my iPhone Safari after I added this to my page. My Android Chrome work fine with the above tag though. Any idea?

Thanks again for this great QR scanning library! Great job!!

**Comment by werthdavid** [comment]
I can reproduce the behavior but that seems to be a problem with iOS itself and not this component. Or can you run any other WebRTC examples in full-screen mode with camera?

**Comment by andrewyan** [comment]
@werthdavid I believe you're right. I read the docs [here](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html) and it says Safari is not used to render the page when the _apple-mobile-web-app-capable_ tag is enabled. I don't know what's being used to render the page but it seems that camera access is not supported by it. Does that make sense?

**Comment by werthdavid** [comment]
It does indeed (unfortunately).
See [here](https://github.com/zxing-js/ngx-scanner#Limitations) and [here](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW1)

**Comment by andrewyan** [comment]
Thanks for the answer, @werthdavid !

**Comment by odahcam** [comment]
Locked because there's no solution. For futher issues, please fell free to open a new one.
