### ISSUE TITLE
Undefined error in prepareCaptureCanvas method, if scanner is closed within scanDelay time after scanning a QR code successfully

### ISSUE THREAD

**Issue by xtj7** [zxing-js/ngx-scanner#71]
#### Bug, feature request, or proposal:
What am I trying to do: I open an overlay to scan the QR code and when it was scanned successfully, I want to immediately close it. If I do that through the scanSuccess callback, it will throw an error that "this.imageElement.naturalWidth" is undefined

#### What is the expected behavior?
After a successful scan, I want to be able to immediately stop scanning and/or hide the entire scanner without any errors being thrown. 

#### What is the current behavior?
After a successful scan, if I stop scanning immediately, it will throw an error "Cannot read property 'naturalWidth' of undefined" in the prepareCaptureCanvas method on the imageElement. This is because of 

#### What are the steps to reproduce?
Here you can test both scenarios, once with the delay and once without, to see that the same code works as long as I wait after scanning and it does not, once I immediately stop scanning.
https://zxing-ngx-scanner-n5hoke.stackblitz.io/

#### Which versions of Angular, `ngx-scanner`, OS, TypeScript, browsers are affected?
Tested with Angular 4 and Angular 5, ngx-scanner 1.0.5
OS, TS version and browser are no factor.

#### Is there anything else we should know?
A suggestion on how to "fix" it, is to let it silently fail in the beginning of the decode method, if neither videoElement nor imageElement are found, e.g.:
`if (undefined === this.videoElement && undefined === this.imageElement) return;`

**Comment by odahcam** [comment]
Nice find!

I think the proper solution would be to `clearTimeout(this.timeoutHandler)` on `stop`, this way the scan will be really stopped.

**Comment by xtj7** [comment]
Thanks :) 
But this is already happening, as far as I see. On change of scannerEnabled, the resetScan method of the scanner component is called, which in turn calls the reset method of the codeReader. The codeReader's reset method calls the stop method, which already clears the timeout of the timeoutHandler, if it is set.

**Comment by xtj7** [comment]
Actually after a little investigation, it seems that the zone task is still running after the timeout was already cleared. This may be a bit trickier than it initially seemed. 
scheduleTask in zone is called, clearTask is not. 

I was not able to find much information on that topic and I don't have in-depth zone knowledge. So I can't really say why clearTask is not called.

**Comment by odahcam** [comment]
Maybe we should open a issue on their repository and provide a demo for they to investigate with us. 🤔 
Do you think it really could be a issue with zone?

**Comment by xtj7** [comment]
Yes, I could confirm that is the issue. It work as intended if replaced as per my proposal. I have updated my PR to reflect this. Using that patch I can no longer reproduce the error. 
Maybe you can check if this could have any other side effects and was an intentional deviation, but I could not see any.

**Comment by odahcam** [comment]
Wow! This looks soo wrong. 😨

@werthdavid can ya take a look at this? I think the only "why" this timeout is there could be to wait for the decode to end it's first attempt.

Even if it should be there, I can refactor the two functions to work nicely together. I will to that in the future anyway. 😅

**Comment by xtj7** [comment]
Once the scanner started, it will always be triggered through the timeout, so while the executed code within the `decode` method itself is synchronous, the entire `decode` method runs asynchronous in relation to the `stop` method. So it is still susceptible to race conditions.

If you run `stop` while `decode` has started, it will try to remove the timeout stored in the `timeoutHandler` (which has expired by that point), decode does not care about that and will - once it is done with the execution - call `decodeWithDelay` again and the scanner will keep on running in the background. The component gets removed and we get the same issue that we have right now. That is of course limited to this particular edge case, where the `stop` method needs to be called after `decode` was called, but before `decode` calls the `decodeWithDelay` method. Otherwise it works as intended.

It is purely theoretical at this point though. I was not able to force it to behave like that and writing a test for it may prove to be very tricky.

**Comment by odahcam** [comment]
Too much performatic, let's make it slower. 😄 

That's ok David, I think we can deal with that now, also by improving the method implementation we can do some new tricks, like some 1d code reading. 🙂 

I've merged #72 to develop just now. Thanks @xtj7.

**Comment by xtj7** [comment]
Thanks a lot guys! And also: great work on the ngx-scanner :)
