### ISSUE TITLE
Is it possible remove all console.log()?

### ISSUE THREAD

**Issue by rastajpa** [zxing-js/ngx-scanner#76]
Hello! :)

Your scanner is amazing, thank you!

But ... Is it possible that you delete all the console.log()? Because sometimes it is difficult to debug the application when another error occurs and the camera is scanning. Thanks in advance!

**Comment by odahcam** [comment]
Sure it is, also, we already have none. 😅

We have just one `console.debug`.

What browser are you using? I'm sure if it is Chrome >= 58, you can disable verbose level:
![image](https://user-images.githubusercontent.com/3942006/38890572-2e714618-4258-11e8-8891-c1d9f190787d.png)

As long as we have the possibility to debug TypeScript code trought VSCode, I do think we can remove the debug method, but I will have to configure at least one environment and document it for future contributors first.

**Comment by rastajpa** [comment]
Yes, sure. You're right. Thanks for answer me!

I think it's not a good solution because the logs for console.debug() are still there but hidden. So, maybe it's a best solution if you comment this line for users and uncomment only when you need fix or improve somethings.

Some applications use loggers and that makes impossible to read logs.

After a few seconds I see this in console:
![bitpay_-_secure_bitcoin_wallet](https://user-images.githubusercontent.com/10969512/38892630-30253ee6-425e-11e8-8de1-dab77e5b8b15.png)

Anyway, I hope this observation also helps someone else! Thanks for all! :)

**Comment by Gamboster** [comment]
Hello @odahcam Excellent work with the scanner! 
I think like @rastajpa. I'm trying to use it in an important project and it's impossible because of the amount of unnecessary logs. I would appreciate if they deleted, or at least commented on the lines they print on the console. I do not want to be forced to change the scanner module, since this is the best one for angular 4 of the ones I've tested.

Thank you and regards!

**Comment by odahcam** [comment]
Don't worry! I just didn't knew if I would be able to make this change until v1.1, but please, that's too much log! So I'll remove it at v1.1 anyway.

**Comment by odahcam** [comment]
Logs removed in [v1.1.0-dev.c38faf](https://github.com/zxing-js/ngx-scanner/releases/tag/v1.1.0-dev.c38faf).

Wiki not ready yet.

Please, if someone has some step-by-step on how to debug in some IDE, please make a PR. 😉
