### ISSUE TITLE
Not working with Edge

### ISSUE THREAD

**Issue by werthdavid** [zxing-js/ngx-scanner#77]
#### Bug, feature request, or proposal:
Edge gives an error after asking for permissions

#### What is the expected behavior?
Should work as in Chrome, FF, ...

#### What is the current behavior?
Console-output
zxing-scanner askForPermission InvalidAccessError
[object DOMException]: {code: 15, message: "InvalidAccessError", name: "InvalidAccessError"}
zxing-scanner ngAfterViewInit It was not possible to check for permissions.

#### What are the steps to reproduce?
Access the Demo-URL or starting the component locally with Angular-CLI

#### What is the use-case or motivation for changing an existing behavior?
Support all major Browsers

#### Which versions of Angular, `ngx-scanner`, OS, TypeScript, browsers are affected?
Latest Develop-branch, Latest release

**Comment by werthdavid** [comment]
I've found the issue (Edge somehow only accepts null as srcObject and not undefined....).
Will be fixed in the next release

**Comment by odahcam** [comment]
Dear JS
![image](https://user-images.githubusercontent.com/3942006/39183423-4dc081da-4796-11e8-9e26-7c5516aa5aeb.png)

**Comment by odahcam** [comment]
Published in [v1.1.0-dev.c38faf](https://github.com/zxing-js/ngx-scanner/releases/tag/v1.1.0-dev.c38faf).
