### ISSUE TITLE
Create directive for using with video elements

### ISSUE THREAD

**Issue by odahcam** [zxing-js/ngx-scanner#83]
#### Bug, feature request, or proposal:
proposal

#### What is the expected behavior?
Full customizable preview.

#### What is the use-case or motivation for changing an existing behavior?
People has trouble to customize.

#### Is there anything else we should know?
I have no time to implement this now. 😟

**Comment by odahcam** [comment]
Yes and the directive would give to the code reader it's own `ElementRef` (`HTMLVideoElement`) to be used as a preview instead of creating a new one.

There are just a few things we may need to put in a service or another class so both directive and component can use common methods; like torch control, device changing, etc.

**Comment by csutorasr** [comment]
By creating a video element I meant using own or the given. (`<video *ngIf="videoElement" #videoElement></video>`)

Ping me if the blocking tasks are done.

**Comment by odahcam** [comment]
All right, I will notify here when we can start coding this. Thx.

**Comment by csutorasr** [comment]
To set the width:

app.component.html:

```HTML
<zxing-scanner [previewElementRef]="videoRef" ...></zxing-scanner>
<video #video></video>
```

app.component.ts:

```TypeScript
    @ViewChild('video')
    videoRef: ElementRef;
```

app.component.css:

```css
video {
    max-width: 60%;
}
```

**Comment by odahcam** [comment]
But that's not a directive. 🤔 
If there's any reason would like to explain why not to use a directive?

**Comment by odahcam** [comment]
I think this is **really** unecessary, because I work with the width of the preview element since the first version of the package with just SCSS. I can't understand the use case for that template thing. :(

**Comment by csutorasr** [comment]
I think this needs no explaination. This is faster. Why to use a directive? How will that be better?

How do you set the width with scss without specifying cssClass (that is deprecated) or using ng-deep?

**Comment by odahcam** [comment]
> I think this needs no explaination. This is faster.

This is faster to code, not on runtime, we already have enough bindings at runtime. We have time to create a good thing and if you wanna "go horse" just go with `::ng-deep` which is even faster to code and causes no impact on performance.

> Why to use a directive? How will that be better?

Directives are created to do this kinda job, they're gonna be faster, cleanner and will require less code 
from the user. Angular devs already know how to use directives, they use it all the time.

> How do you set the width with scss without specifying cssClass (that is deprecated) or using ng-deep?

I use `::ng-deep`, but most of the cases the video will fit perfectly on the screen.

**Comment by csutorasr** [comment]
`:;ng-deep` is deprecated, that is why we removed the `cssClass` also.

We could use [ContentChildren](https://angular.io/api/core/ContentChildren) if it is a better option for you.

**Comment by odahcam** [comment]
The idea behind the scanner, is that you shouldn't need to touch any element inside it, but just style the `zxing-scanner` component. `object-fit` should cover all use cases and will be a lot faster than a template binding, then we can spend time creating the directive thing or alternatives like `ContentChildren` that honestly I've never seen before.

`::ng-deep` is in fact deprecated but it is solving a problem for a `v0.x.x` version, no one gonna need that on `>= 1.0.0`.
