### ISSUE TITLE
Update Angular version and dependencies

### ISSUE THREAD

**Issue by odahcam** [zxing-js/ngx-scanner#89]
#### Bug, feature request, or proposal:
proposal

Update to Angular 6.

#### What is the use-case or motivation for changing an existing behavior?
People should update, we have a version running on Ng5 and lower. Ng6 will bring lots and lots of improvements to us. 😄 

#### Which versions of Angular, `ngx-scanner`, OS, TypeScript, browsers are affected?
Ng5, Scanner 1.2

#### Is there anything else we should know?
https://cdn.vox-cdn.com/thumbor/NxAy8t4lNE4Gmjyt_GsHWwKXouE=/0x84:1024x767/1200x800/filters:focal(0x84:1024x767)/cdn.vox-cdn.com/uploads/chorus_image/image/46791980/Windows_Insider_Ninjacat_Trex-1024x768__627224_.0.0.png

**Comment by cre8** [comment]
Adding the package `rxjs-compat` removes this error (similar to this one: https://github.com/angular/flex-layout/issues/693) while using angular 6.

**Comment by odahcam** [comment]
Sure it does! I use it myself, thanks for adding this note.

My plan to update is to make things better at all, not because any compatibility issue.

But do you think that we shouldn't update to ng6? 🤔

**Comment by cre8** [comment]
@odahcam it would be really cool if it would work then for ng5 and ng6 since not all people have upgraded yet.

**Comment by odahcam** [comment]
They can still make use of our LTS version. 🙂

At least v2 gotta be in ng6, I can't give support for a very modern tool like that with outdated dependencies.

I can also make a transition version, like 1.3 so people can update easily.

**Comment by odahcam** [comment]
None of our APIs changed, so you just need to upgrade to Angular 6 and than update ngx-scanner. 😄
