### ISSUE TITLE
Crashing entire app on IE and Edge

### ISSUE THREAD

**Issue by devgrigor** [zxing-js/ngx-scanner#93]
**Describe the bug**
When project is opened in IE11 or Edge it's freezing on loading page. The error is at `eval('BrowserCodeReader ...')` It happens only if `ZXingScannerModule.forRoot()` was called. There is n way to even put a try catch there, because eval is happening in vendor, and even conditionally  calling forRoot() is causing the issue e.g.
```
if(!isIEorEdge) {
      imports.push(ZXingScannerModule.forRoot())
}
```

**To Reproduce**
1. Open project with plugin in IE11 or Edge

**Expected behavior**
Throw an error that can be handled or show warning.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser IE-11 and Edge
 - Version any

**Smartphone (please complete the following information):**
 - Probably windows phone will cause the same, not tested

**Additional context**
I know that this plugin is not supporting Edge and IE, but issue is not about support it's about crashing entire app.

**Comment by odahcam** [comment]
Have you tryied w/o `.forRoot()`?

**Comment by devgrigor** [comment]
Not before you mentioned it, now I did and still same error. I guess it's the import not the forRoot() that matters

**Comment by odahcam** [comment]
Are you using Angular 6?

**Comment by devgrigor** [comment]
No. Angular 5.2

**Comment by devgrigor** [comment]
1.1.0-dev06cf75

**Comment by odahcam** [comment]
Could you update to the latest version ans try again?

**Comment by werthdavid** [comment]
There is a (known) issue with IE11 in (zxing-library )[https://github.com/zxing-js/library/issues/7] but Edge should be working.. I can take a look tmrw

**Comment by devgrigor** [comment]
I'll try to update, but I thought this is the latest version, installed about 2-3 weeks ago. @werthdavid  Edge is not working as well

**Comment by odahcam** [comment]
No problem, at this moment LTS is `npm i -S @zxing/ngx-scanner@1.1.0`

**Comment by devgrigor** [comment]
ok. Installed LTS, but issue still occurs

**Comment by odahcam** [comment]
I think the component is trying to iterate the devices w/o devices.

**Comment by devgrigor** [comment]
I'm not sure that this is the error I'm getting. My error comes from eval of 'class BrowserCodeReader' probably es6 issue, but I included all polyfills of angular and still got error. I'll try to reproduce same issue on new angular project to be more accurate in report

**Comment by odahcam** [comment]
Check your `tsconfig` and look for your build targets, maybe you are building your app for modern JS only. The component shouldn't break your app at Edge at least, IE does have a problem.

**Comment by devgrigor** [comment]
Small note in my vendor I see usage of 
```"../../../../@zxing/library/esm5/browser/BrowserCodeReader.js"```
which is in es6 format e.g. starts with `class BrowserCodeReader`

**Comment by odahcam** [comment]
Dunno if it's bad or good, but it could be a problem with the library at all. Do you re-checked Edge? It seems to be working here, I'm curious about this different behavior. 🤔

**Comment by devgrigor** [comment]
Yes rechecked Edge version 20 it throws error in main.bundle.js at this code ```e.default = class{etc.}``` I actually found the `ngx-scanner/esm5/zxing-ngx-scanner.js`  that contains correct classes like BrowserCodeReader in es5 standard. I just don't understand why it's not working with that file

**Comment by odahcam** [comment]
I can confirm that esm5 are es6 classes; ~damn~

![image](https://user-images.githubusercontent.com/3942006/40120962-cbfb2638-58f6-11e8-96ae-4b24e6e811d7.png)

I think this issue should be transfered to @zxing-js/library, what you think @werthdavid ?

**Comment by odahcam** [comment]
Also, I noticed that zxing-ngx-scanner.js is using ES6 imports syntax while in ES5 files, this is so wrong. 👀 
![image](https://user-images.githubusercontent.com/3942006/40121426-ed410d52-58f7-11e8-8d16-8c9152db0eb1.png)

**Comment by Danieliverant** [comment]
any news on that?

**Comment by odahcam** [comment]
I published a dev version so the reporter could test if it solved his case, but I didn't get any feedback on that. I'm not supporting IE currently, so I would be glad if anyone test it, cause I won't test any soon because of my current project environment.

But we made some progress with the scanner issues and we certainty gonna solve it by next month btw.

**Comment by devgrigor** [comment]
I tested `1.1.1-dev.ca33ea` version and it worked on IE. Thanks for that. @Danieliverant   just don't forget to add `import 'core-js/es6/typed';` at polyfills

**Comment by devgrigor** [comment]
@Danieliverant https://www.npmjs.com/package/@zxing/ngx-scanner/v/1.1.1-dev.ca33ea

**Comment by odahcam** [comment]
```
npm i -S @zxing/ngx-scanner@1.1.1-dev.ca33ea
```

**Comment by Danieliverant** [comment]
Thank you!! I will test it on Monday

**Comment by ninjaonsafari** [comment]
@odahcam there is still some es6 thingy left in the [GlobalHistogramBinarizer](https://github.com/zxing-js/library/blob/c6be426127ac5511ad92690d080217da8318c79e/src/core/common/GlobalHistogramBinarizer.ts#L41).

This is my version 1.2.0-dev.9e43af of the scanner.

**Comment by odahcam** [comment]
Shouldn't a polyfill cover'em?

**Comment by odahcam** [comment]
Oh, I see that it's from the `library` package, can we discuss that there (https://github.com/zxing-js/library/issues/7)?

**Comment by ninjaonsafari** [comment]
oh gah damn... 
Sorry this one's mine...
I thought I had all polyfills in place but i forgot `core-js/es6/typed`

![](https://media.giphy.com/media/evCzUJ9kVbG7K/giphy.gif)

**Comment by odahcam** [comment]
Everyone makes mistakes, even ninjas. 🐱‍👤 _(ninjacat Windows's emoji)_
