### ISSUE TITLE
Add object-fit control for the video element

### ISSUE THREAD

**Issue by odahcam** [zxing-js/ngx-scanner#94]
**Is your feature request related to a problem? Please describe.**
Users claim that the video cannot be sized.

**Describe the solution you'd like**
The object-fit control on ht etop of the component would allow users to set the video resizing method and everything would be controlled be the component itself.

**Describe alternatives you've considered**
Another issues had mentioned them: #55, #60, #83.

**Additional context**
I think this solution would kill all the referenced problems.

**Comment by csutorasr** [comment]
https://github.com/zxing-js/ngx-scanner/issues/55#issuecomment-379115091

The solution is found there. I will create a PR for this.

**Comment by odahcam** [comment]
I prefer the idea of using a directive over a `<video>` element than creating a new binding on the component. If you make a directive to be used in the `HTMLVideoElement` I could gladly accept a PR. 🙂

**Comment by odahcam** [comment]
I can't assign you to, but there's #83 .
