### ISSUE TITLE
We've built a veeeery cool Wiki (404) for you!

### ISSUE THREAD

**Issue by wiedikerli** [zxing-js/ngx-scanner#98]
We've built a veeeery cool Wiki for you!
Wiki doesnt exist anymore. I get a 404.

**Comment by ninjaonsafari** [comment]
When i click on the link in the readme i get the 404.
When i navigate via the tab it works :+1: 

ps. why the hate against microsoft? :rofl:

**Comment by odahcam** [comment]
I fixed few hours ago. 😄 

ps. GitHub is great as being itself, now other ideas will enter in the company, things gonna change and GitHub will not be what it was anymore, GitHub will just be a Microsoft product. GitHub shouldn't be owned by any of the giant companies. Microsoft is also unstable in ideas, so what can we expect from future? nothing? I loved GitHub for years, now I'm not against M$, I'm just afraid of what they gonna do with the octocat. 😖
